### PR TITLE
Display custom welcome message for admins.

### PR DESCRIPTION
**Pull request by mrpau-eugene**
## Summary

Displays a custom welcome message to the admin after their first login, given that they modify the `~/.kalite/settings.py` first..

image

## TODO

If not all TODOs are marked, this PR is considered WIP (work in progress)

- [ ] Has documentation been written/updated?
- [ ] Have you written release notes for the upcoming release?

## Issues addressed
#5522

### CODE REVIEW

**Comment by benjaoming** [comment]
Great work!

We need to write a custom welcome message that isn't about RACHEL, I'll get a hold of the imps team and request that they write it, since they might be opinionated about it.

First draft:

> ## Need help? Connect with other users!
> 
> KA Lite is community-driven and relies on help and experience which you can both share and receive in our community.
> 
>  * [KA Lite community at Learning Equality](http://community.learningequality.org/)
>    `http://community.learningequality.org/`
>  * [Help program KA Lite at Github](http://github.com/learningequality/ka-lite/)
>    `http://github.com/learningequality/ka-lite/`
>  * [Sign up for emails about new releases](https://groups.google.com/a/learningequality.org/forum/#!forum/dev)
>     `https://groups.google.com/a/learningequality.org/forum/#!forum/dev`

Notice that the URLs of the links appear in the text -- this is on purpose.

**Comment by jamalex** [comment]
Are we going to show this message unconditionally, whether or not they have internet? Given the fact that most RACHEL usage is totally offline (and doesn't need to go online for setup, as the videos are preloaded), would it be better to frame the message differently if no internet is available and the links won't work?

For the default (non-RACHEL) admin login, there's a greater chance the first install will be online (to load videos), but still not necessarily the case.

**Comment by laurenlichtman** [comment]
I'm not sure if we need a RACHEL-specific version. One of the reasons we did this was to also learn about how people are using KA Lite and/or add it to the map. I've added LE so it makes sense "why LE" is in the links.

Suggested edit (sorry about the formatting) cc: @jeepurs.

You are running an instance of KA Lite, developed by the edtech nonprofit organization, Learning Equality. KA Lite is community-driven and relies on help and experience from our online community.

- Support the KA Lite community at Learning Equality
http://community.learningequality.org/

- Share your implementation of KA Lite on the map
https://learningequality.org/ka-lite/map/ (Click on "Add your story!")

- Sign up for emails about new releases
https://groups.google.com/a/learningequality.org/forum/#!forum/dev

- Help program KA Lite at Github
http://github.com/learningequality/ka-lite/

**Comment by benjaoming** [comment]
> I'm not sure if we need a RACHEL-specific version.

It's configurable, so anyone can setup their own welcome message... RACHEL was the specific case for this because of a concern that we get a lot of RACHEL-specific support questions, so we'll ask them to customize this message in their devices.

**Comment by benjaoming** [comment]
@jamalex 

>  would it be better to frame the message differently if no internet is available and the links won't work

That's why the URLs are displayed - regardless, we are only showing the message on the first login. Deployments with preseeded databases might have already set the flag so the message doesn't get displayed.

**Comment by benjaoming** [comment]
Made some amendments to above suggestion...

@jamalex changed the text so it's addressing both on and offline scenarios

@laurenlichtman I've added the map as the first item, it should totally be there, thanks

**Comment by jeepurs** [comment]
@benjaoming does that mean the default is non-RACHEL and that the RACHEL users will have to configure it?

> It's configurable, so anyone can setup their own welcome message

**Comment by benjaoming** [comment]
@jeepurs 
> @benjaoming does that mean the default is non-RACHEL and that the RACHEL users will have to configure it?

Yes -- just not the RACHEL _users_, but the pre-configuration that RACHEL ships with should contain a different welcome message that they decide and design for their wishes.

**Comment by mrpau-eugene** [comment]
@benjaoming is this supposed to be the default message for non-RACHEL users?

> ## Need help?
> 
> KA Lite is community-driven and relies on help and experience which you can both share and receive in our community.
> 
>  * Offline help: Use the "Docs" button in the top menu to get help
> 
> Online help:
> 
>  * Share your implementation of KA Lite on the map and find other KA Lite users in your country
>    https://learningequality.org/ka-lite/map/ (Click on "Add your story!")
>  * [Give and receive KA Lite support in the Learning Equality community](http://community.learningequality.org/)
>    `http://community.learningequality.org/`
>  * [Help program KA Lite at Github](http://github.com/learningequality/ka-lite/)
>    `http://github.com/learningequality/ka-lite/`
>  * [Sign up for emails about new releases](https://groups.google.com/a/learningequality.org/forum/#!forum/dev)
>     `https://groups.google.com/a/learningequality.org/forum/#!forum/dev`

**Comment by benjaoming** [comment]
> @benjaoming is this supposed to be the default message for non-RACHEL users?

Yes, but I think you should make **Offline help** a sub-heading, too, so it aligns with **Online help**

**Comment by benjaoming** [comment]
Seems like something weird happened with the version history, making it a bit hard to review.

@mrpau-eugene could you:

1. Create a new PR with a fresh branch off from current `0.17.x` ?
1. Introduce your changes from your old feature branch as a single commit? See: https://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit
1. Move the default `KALITE_WELCOME_MESSAGE` to `kalite.project.base` ?

**Comment by laurenlichtman** [comment]
@benjaoming any action needed from me on this? Would like to flag to the WP team when it's ready. Thanks!

**Comment by benjaoming** [comment]
@laurenlichtman - good call, yes the action item would be to advice about using the new configuration in RACHEL. It's not out yet because of another bug. Will get back once released!

**Pull request closed without merging**
