### PR TITLE
hotfix for colors: header/footer bg, logo leaf, and footer FLE button #2922

### PR DESCRIPTION
**Pull request by benjaoming**
No drama, just minor tweaks that unify the experience with the current FLE website and avoids the nasty clash with new green vs. old green.

Look, I washed the green to make it look shinier!

### CODE REVIEW

**Comment by benjaoming** [comment]
#2922

**Comment by aronasorman** [comment]
Screenshots @benjaoming?

**Comment by benjaoming** [comment]
blah

**Comment by benjaoming** [comment]
blah2

**Comment by benjaoming** [comment]
@aronasorman the test is failing because of an unrelated issue noted in #2919 -- it can be merged if screenshots are okay

**Comment by aronasorman** [comment]
Alright, but we should get that fixed real soon @benjaoming

**Comment by Antrikshy** [comment]
New blue is gorgeous! Looks like some parts of the admin area were not using the `.faded-green-bg` class and now look totally inconsistent.

screen shot 2015-02-01 at 4 22 24 pm

But don't worry. I have been working on cleaning that whole thing up lately. I'll make everything match up.

And maybe I will rename the class to `.faded-blue-bg` everywhere in the code too :) .

**Comment by benjaoming** [comment]
@Antrikshy nice man, look forward to seeing the new look. Protip: Never name CSS classes according to their look, but always according to their function or structural position :)

**Pull request merged**
