### PR TITLE
Remove unused management commands and content data

### PR DESCRIPTION
**Pull request by rtibbles**
This PR cleans up now defunct management commands, and removes all content data from the repo.

This content data is now generated on the content pack maker repo.

Putting up for review, to show what would be removed. But, let's not merge it until the dust has settled on #4802 .

### CODE REVIEW

**Comment by benjaoming** [comment]
Great stuff, but `init_content_items` is supposed to be staying, no?

**Comment by rtibbles** [comment]
This is why I put it up for review - this is what I want to remove. If init_content_items stays, then all the json files have to stay too, and some other stuff.

**Comment by benjaoming** [comment]
@rtibbles could you open up this PR but for develop as @iCHAIT is intending to factor out some of the stuff in  #3974 that may already be factored out by this PR?

**Comment by rtibbles** [comment]
Wilco.

**Pull request closed without merging**
