### PR TITLE
Default kalite user should now have a shell

### PR DESCRIPTION
**Pull request by benjaoming**
## Summary

Since https://github.com/learningequality/installers/issues/368 is getting fixed, we can make this slight simplification.

### CODE REVIEW

**Comment by benjaoming** [comment]
Sorry about the new silly branch.. the change is pretty straight-forward so possibly just merge and delete the branch after.

**Comment by MCGallaspy** [comment]
You tested this out?

**Comment by benjaoming** [comment]
I've tried the command manually, yes:

screenshot from 2016-04-18 19 25 52

If you upgrade from a previous debian installation that already created a shell-less 'kalite' user, then the message will be mis-leading... but I would rule that people who have installed previous versions should be aware of the issue.

**Comment by benjaoming** [comment]
Small change, self-merging. Is that even a word?

**Pull request merged**
