### PR TITLE
propagate the request language in user progress.

### LINKED ISSUE #4650: Some translated strings still being displayed in English
**Version**: 0.15

The Spanish translations page shows that 0.15 is translated at 99%. But some words still in English.
- In the tabular report, the titles for the themes are not translated; but they are shown translated in the topic-tree from the sidebar. Also, the word "Question" is still not translated.
  selection_016
- The string "I'd like another hint" is not translated in the plural form. But it is translated as seen in the [CrowdIn page](https://crowdin.com/translate/ka-lite/28881/en-es#1984757)
  selection_020
- The topic name and description isn't translated from the recommendations section in the home screen.
  selection_018

### PR DESCRIPTION
**Pull request by aronasorman**
Fixes #4650. Partially at least. CC @jinchuika

screen shot 2015-11-17 at 09 32 58

I still couldn't get the exercise text translated, despite propagating the language in `get_exercise_cache` too. Any ideas @rtibbles?

### CODE REVIEW

**Comment by aronasorman** [comment]
@jinchuika

**Comment by jinchuika** [comment]
Great to see some progress here!

Did this part got translated as well?

selection_016

**Comment by rtibbles** [comment]
@aronasorman Have you checked that 'language' is getting passed into the user_progress_detail method?

**Comment by aronasorman** [comment]
@rtibbles yup, still the same case. Based on the image above translation happens for exercises I already started, not for the ones I'm not doing yet. Is it a separate code path from this? https://github.com/learningequality/ka-lite/pull/4673/files#diff-73b6e133dd1741559880c6ce3bb4b8e4R210

**Comment by aronasorman** [comment]
Hi @jinchuika, I've solved the progress report issue and am now working on the issue you linked to in your image.

**Comment by jinchuika** [comment]
Great! Will this be a system update or a language pack update? I think it's a system update for 0.15.1, right?

**Comment by aronasorman** [comment]
screen shot 2015-11-18 at 09 24 40

@rtibbles this is ready for review. The rest of the untranslated strings in these pages are just missing strings in our po files now. I'll reupload a new one once this is merged.

**Comment by aronasorman** [comment]
@jinchuika it will be both; there will be new strings in crowdin that will eventually bubble down to the language packs, plus a system update (0.15.1) to make sure those strings are read by KA Lite.

**Comment by rtibbles** [comment]
Works for me.

**Pull request merged**
