### PR TITLE
Remove deprecated scripts

### PR DESCRIPTION
**Pull request by MCGallaspy**
They're just a source of confusion, now.

### CODE REVIEW

**Comment by rtibbles** [comment]
Do any of these get used by the windows installer at all?

**Comment by rtibbles** [comment]
@ruimalheiro ^

**Comment by ruimalheiro** [comment]
@rtibbles, start/stop and add/remove_systemstart_task are still related with with both the installer and the gui. They will not be necessary once the binary starts being used.

**Comment by aronasorman** [comment]
Closing this, as it's too late for 0.13.x now. Can you merge this against develop instead?

**Pull request closed without merging**
