### PR TITLE
Remaining issues on kalite command fixing #2919

### PR DESCRIPTION
**Pull request by benjaoming**
Do not merge yet... aggregating stuff for closing tasks in #2919

### CODE REVIEW

**Comment by aronasorman** [comment]
We've been getting occasional race conditions whenever we run `bin/kalite`, and I think you've put in a fix here. Maybe we can merge this in now (once the tests are passing) and then continue on another PR?

**Comment by benjaoming** [comment]
Sure, better get things merged and tested, I can move on to a new PR :)

**Comment by benjaoming** [comment]
@aronasorman please do merge! now there's another critical commit in the mix :)

**Comment by aronasorman** [comment]
Noooo, them tests :(

**Comment by benjaoming** [comment]
We know, but we decided to skip them since last time we tried, Travis got a timeout anyways..

https://travis-ci.org/learningequality/ka-lite/builds/49281736

**Pull request merged**
