### PR TITLE
reactive sidebar

### PR DESCRIPTION
**Pull request by 66eli77**
this is for demo, no need to merge, in the future maybe : )

### CODE REVIEW

**Comment by 66eli77** [comment]
screen shot 2015-06-02 at 4 23 37 pm
react is on the left

**Comment by rtibbles** [comment]
There are definite improvements here - does seem like we still have more bang for buck performance improvements to wring out of the 2s scripting delays (on a fast system, which is surely much longer on Android).

Hopefully some of the optimization and conditional file loading we are planning to bring in with the browserify build process will help with that.

**Comment by rtibbles** [comment]
For reference, this is the read out (on my machine) for the learn tab on develop:
image

If we don't force the browser to load all other assets (and only load sidebar assets for first render of the sidebar), we get something like this:

image

So, just by more intelligently handling our assets, we could get a doubling in performance for the first load of the sidebar, rather than slightly marginal performance improvements by switching to react.

**Comment by 66eli77** [comment]
why not combine the new asset loading with react, make it even faster...
react's not only about faster painting and rendering but also shorter coding, potential easier feature borrowing integration from khan academy in the future.

**Pull request closed without merging**
