### PR TITLE
 Fix non-deterministic behaviour for search autocomplete behave test

### PR DESCRIPTION
**Pull request by rtibbles**
Summary of changes:
* Wait for search autocomplete JSON blob to load before proceeding.
* Search for 'basic' rather than 'basic addition'.

Let's see what our circular overlord says!

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Re: the content rating availability issue, I wonder if it might be helpful to create a test-only topic tree with test-friendly paths? Something like:

```
/learn/khan-exercise
/learn/assessment-item/available
/learn/assessment-item/unavailable
/learn/video/available
...
```

**Comment by MCGallaspy** [comment]
@rtibbles can't say why the content rating stuff is now failing, it passes locally. My hypothesis is that it's truly just taking a long time for the page to completely load. As for the other old-style test, again it seems to be a long page load.

**Comment by rtibbles** [comment]
Yeah, this definitely worked for me too locally.

**Comment by MCGallaspy** [comment]
Let's merge in #4412 and re-run the tests, in order to observe the screencast for failing tests. Will provide clues.

**Comment by MCGallaspy** [comment]
I'll bet if we merge this https://github.com/learningequality/ka-lite/pull/4416, then everything will work beautifully.

**Pull request merged**
