### PR TITLE
Use js reverse urls

### LINKED ISSUE #3788: Attempting to download language pack results in error
On `develop`.
Steps to reproduce: log in as admin, attempt to download a language pack. Results in a bubble alert on the page with the text `Unexpected error; contact FLE with the following information: 200` along with the html for the language pack download page.

Screenshot:
ss

### PR DESCRIPTION
**Pull request by MCGallaspy**
Fixes #3788. There are more urls in this file that need to be similary fixed; incoming fix.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
That ought to do the trick.

**Comment by rtibbles** [comment]
2.6 build error. Restarted.

**Comment by rtibbles** [comment]
Are any of these variables still being defined in templates? Could you make this PR about hunting down and finding all of them? (at least all that aren't Tastypie. DAMN YOU TASTYPIE!)

**Comment by rtibbles** [comment]
This is working, so I will leave the remaining url hunting for other PRs.

**Pull request merged**
