### PR TITLE
Build pex file and separate windows installer pipeline

### PR DESCRIPTION
**Pull request by mrpau-eugene**
test PR to see if it autobuilds on buildkite

### CODE REVIEW

**Comment by benjaoming** [comment]
It does!! :tada: :smile:

**Comment by benjaoming** [comment]
@mrpau-eugene I think this looks very useful already, maybe if we can get a thumbs up from @radinamatic that the built artifacts (can be found on Buildkite ATM) are working, then we could merge.

@mrpau-eugene One very nice to have would  be if we can have the artifacts available same way as for Kolibri (in the build status), so people don't have to login to see them on Buildkite. Do you know how to do this?

**Comment by mrpau-eugene** [comment]
> One very nice to have would be if we can have the artifacts available same way as for Kolibri (in the build status), so people don't have to login to see them on Buildkite. Do you know how to do this?

@benjaoming I'm not quite sure how but I got some reference from kolibri repo. @rtibbles pointed me to this code on Kolibri https://github.com/learningequality/kolibri/blob/develop/.buildkite/upload_artifacts.py#L123 but I need an access token that has the right permissions (not quite sure which permissions are needed) in order to have something like that.

**Comment by benjaoming** [comment]
Oh right, you mean this line? `ACCESS_TOKEN = os.getenv("GITHUB_ACCESS_TOKEN")`

**Comment by benjaoming** [comment]
@mrpau-eugene I have set both `GOOGLE_APPLICATION_CREDENTIALS` and `GITHUB_ACCESS_TOKEN`, in case they don't work, let me know by PM.

**Comment by mrpau-eugene** [comment]
@benjaoming yup! that's pretty much it. I also want to know how to build the debian installers manually. Can you give me some help?

**Comment by mrpau-eugene** [comment]
@benjaoming github status and being uploaded to google cloud is working now

**Comment by benjaoming** [comment]
GREAT WORK @mrpau-eugene :tada:

**Comment by mrpau-eugene** [comment]
@benjaoming Thanks 😄 

Btw, we should change the access token as soon as LE Bot is ready..

**Comment by benjaoming** [comment]
@mrpau-eugene yes, did someone say they would create it btw? otherwise, I can do that today!

**Comment by mrpau-eugene** [comment]
@benjaoming I think it was @rtibbles who mentioned it that they were talking about creating an LE bot

**Pull request merged**
