### PR TITLE
Docs screenshots fixup

### LINKED ISSUE #4296: Develop docs screenshots issues
Tried to build the docs with screenshots in order to commit them, on `develop`. Got the error:

```
ERROR:kalite:Error taking screenshot:
ERROR:kalite:Message: $(...).qtip is not a function
```

With maybe more to come once that's resolved. But at any rate we should aim to fix up screenshots a bit during the 0.15 bug bash cycle, at least well enough to build and commit screenshots from _someone's_ machine if not the build server itself.

### PR DESCRIPTION
**Pull request by MCGallaspy**
Starts to fix #4296. Docs now build with screenshots when `screenshots_create = True` in `docs/conf.py`. But they need to be debugged -- they've gotten out of sync with the changes in the app. At the same time, we should add new screenshots to the docs where appropriate.

Find three commits:
* A squashed commit of many changes I made to get screenshots working. See the message for details.
* A commit with new screenshots -- as I said above, they need to be debugged.
* Increase timeout on a test that presumably started failing because I changed a browser_mixin method.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
I'm sure the test failure is because this failed: `kalite start --traceback -v2 returned exit code 1`

Investigating why.

**Comment by MCGallaspy** [comment]
Funny, the same command works fine for me.

**Comment by MCGallaspy** [comment]
ooops. I merged develpo instead of 0.15.x. Let me revert that.

**Comment by jamalex** [comment]
Haven't reviewed the code, but great that they're working again. Probably good to fix the ones that are messed up (missing highlighting, giving 404's, etc) before we merge this?

**Comment by MCGallaspy** [comment]
> Probably good to fix the ones that are messed up (missing highlighting, giving 404's, etc) before we merge this?

Agreed. Will work on it.

**Comment by MCGallaspy** [comment]
Replaced by #4433. See that.

**Pull request closed without merging**
