### PR TITLE
Raspberry Pi Installation Updated Documentation

### PR DESCRIPTION
**Pull request by rajnikumbh**
## Summary

Raspberry Pi Installation Updated Documentation

## TODO

If not all TODOs are marked, this PR is considered WIP (work in progress)

- [ ] Have **tests** been written for the new code? If you're fixing a bug, write a regression test (or have a really good reason for not writing one... and I mean **really** good!)
- [ ] Has documentation been written/updated?
Yes
- [ ] New dependencies (if any) added to requirements file

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed
#5228 

List the issues solved or partly solved by the PR

## Screenshots (if appropriate)

*They're nice. :)*

### CODE REVIEW

**Comment by rajnikumbh** [comment]
@benjaoming .. here is the follow up PR.  Let me know if this time it is fine.

**Comment by rajnikumbh** [comment]
@benjaoming 
I had missed adding the install_main.rst 
I wanted to update the commit here but couldn't find an option. Here is the file attached. I tried looking for a way to do that. But I am not sure if there is an easy way.

I have added a single line at the bottom of the file install_main.rst
 "Raspberry Pi Updated Installation <rpi_install>"

**Comment by benjaoming** [comment]
Hi @rajnikumbh 

Thanks for the contribution, it's really well-written. I will merge it, and in case you have additional changes, we can also work on them after! I'll ping you in a follow-up PR (pull request) with my changes. Maybe wait until then if you have more changes.

After merging, changes will show up here:

ka-lite.readthedocs.io/en/develop/installguide/rpi_install.html

You can read more about Git and Github online, for instance this free book: https://git-scm.com/book/en/v2 <- it's how over 14 million people are collaborating!

**Comment by rajnikumbh** [comment]
@benjaoming 
OK fine. I missed adding a file in my previous commit, so it woudn't show up as a link.

Anyways I will wait  for your merging of changes as you have suggested.

**Pull request merged**
