### PR TITLE
Added ARIA landmarks

### PR DESCRIPTION
**Pull request by radinamatic**
Diving into WCAG from the outward - added main ARIA landmark roles.
http://www.w3.org/TR/WCAG20-TECHS/ARIA11

ka_aria_landmarks

### CODE REVIEW

**Comment by radinamatic** [comment]
Just realized that a change from another branch that I'm still working on "sneaked" into this PR. Feel free to cherry-pick-it-out if necessary.

**Comment by radinamatic** [comment]
BTW, would it be possible to have a proper "a11y" label for issues and PRs?  
Should I post an issue for that? :P

I'm unsure if I could actually use the label myself, but it should definitely be available.

**Comment by radinamatic** [comment]
@aronasorman, thanks for the label! 
I don't know if the color was intentional, but I like it... :)

**Comment by rtibbles** [comment]
Och, this is going to get messy as @jtamiace and I are backbonifying the homepage.

Be aware of this as you build, @jtamiace!

**Comment by rtibbles** [comment]
All good. Merging.

**Comment by radinamatic** [comment]
@rtibbles In case I have to work again on homepage, anything I should keep in mind regarding the backbonifying?

**Comment by rtibbles** [comment]
No - you just keep on going with what you're doing. Just shout at us if we happen to revert any of your changes!

**Comment by radinamatic** [comment]
Gottit! :)

**Pull request merged**
