### PR TITLE
Fixed #2876: Colors on Admin tab

### LINKED ISSUE #2876: Colors on Admin tab
image

### PR DESCRIPTION
**Pull request by Antrikshy**
#2876 can now be closed.

Looked like someone had made the new fresh green versions of the .png icons. But I went ahead and replaced them with these new icons for maintainability (future color changes). I left the images in there. I could not find an icon for the `.units` tab, so I let it be.

Some icon tabs are only visible in some variations of KA Lite (Nalanda's Playlists, Tests...), so I have not tested everything by eye. But I have still replaced the code, following patterns for the normal tabs. They should be fine, but someone should make sure.

Useless screenshot (because nothing seems to have changed):

screen shot 2015-02-01 at 5 10 19 pm

### CODE REVIEW

**Comment by rtibbles** [comment]
Fixed. Tests pass. Merging.

**Comment by benjaoming** [comment]
Thumbs up! Please do delete the old icons for clarity :)

**Comment by benjaoming** [comment]
Btw. just scanned the codebase. You can delete the icons, there are no references left.

Except this one:
    ack-grep --html --css --js "images/distributed/.*icon.png"
    
    distributed/static/css/distributed/khan-lite.css
    
    227:    background: url("../../images/distributed/units-icon.png") no-repeat;
    232:    background: url("../../images/distributed/units-active-icon.png") no-repeat;

@Antrikshy 
You might wanna check if that's missing from the new icon set?

**Comment by Antrikshy** [comment]
The units icon seems to be missing. I couldn't see that part of the UI anyway so I got lazy, but I can swap that too if @jtamiace looks into this.

**Comment by benjaoming** [comment]
@Antrikshy you will find it used here:

    static/perseus/ke/exercises/solid_geometry.html
    153:                <p><span class="sol" data-type="decimal"><var>DEPTH * BASE * HEIGHT / 2</var></span> cubic units</p>
    268:                <p><span class="sol" data-type="decimal"><var>LENGTH * WIDTH * HEIGHT</var></span> cubic units</p>

    distributed/static/perseus/ke/exercises/solid_geometry.html
    153:                <p><span class="sol" data-type="decimal"><var>DEPTH * BASE * HEIGHT / 2</var></span> cubic units</p>
    268:                <p><span class="sol" data-type="decimal"><var>LENGTH * WIDTH * HEIGHT</var></span> cubic units</p>

    distributed/templates/distributed/base_teach.html
    19:                <li class="teacher-only units {% block current_unit_active %}{% endblock current_unit_active %}"><a href="{% url 'current_unit' %}" id="nav_current_unit" title="{% trans 'See list of current units for the facilities.' %}"><div>{% trans "Units" %}</div></a></li>

**Pull request merged**
