### PR TITLE
Adds node sort order

### LINKED ISSUE #4811: No sort order on content items
Currently there is no way for determining which order items at the same level and under the same parent in the topic tree should be sorted.

This was not apparent previously, due to the particular idiosyncratic way in which init_content_items sorted through the nodes. Due to this, the order of the ids (which I believe defines the default sort order) happened to coincide with the original sort order of the nodes.

This will no longer be the case when the content packs are imported.

### PR DESCRIPTION
**Pull request by rtibbles**
Fixes #4811

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Do you have to make a migration for this?

**Comment by rtibbles** [comment]
No, it's not in the django db.

**Comment by aronasorman** [comment]
@rtibbles you forgot to add the import for `FloatField`: https://circleci.com/gh/learningequality/ka-lite/1783

**Comment by rtibbles** [comment]
This is what happens when I code during all hands.

**Pull request merged**
