### PR TITLE
Fix #4186: Make sure stamping uses the right dir.

### LINKED ISSUE #4186: Unable to load localized exercises in Spanish (404 error)
**Branch**: 
*KALiteSetup-0.14.0.exe* compiled on Jul 24 14:13, tested on Windows 8 & XP
*0.14 alpha12 - ka-lite-bundle* installed from PPA, tested on Ubuntu 15.04

**Spanish set as Default language**
On all installations, for exercises that appear as available in the sidebar, most of them load in English but few (that I suspect ARE localized), give 404 error.

**Windows XP:**
miss-es

**Ubuntu 15.04:**
miss-es-linux

### PR DESCRIPTION
**Pull request by aronasorman**
Makes sure that exercises are searched on the `localized_exercise_dirpath`.

### CODE REVIEW

**Comment by aronasorman** [comment]
@radinamatic can you pull this and test it out?

**Comment by radinamatic** [comment]
Didn't work off-the-shelf, so I deleted and I'm re-downloading the language packs now, and it's taking time.

Did you try deleting that `.kalite/exercises/` and testing without it?

**Comment by benjaoming** [comment]
#4186

**Comment by radinamatic** [comment]
Yeah, that one finally put the things in their rightful place!

**Pull request merged**
