### PR TITLE
Unburden __init__.py for profiling

### PR DESCRIPTION
**Pull request by MCGallaspy**
@rtibbles @aronasorman I moved all the stuff out of topic_tools' `__init__.py`. Seems to have marginally improved performance, but perhaps it'd be beneficial to take an average of several runs. Results from this PR using same filters as in [this comment](https://github.com/learningequality/ka-lite/pull/3586#issuecomment-98014805):

```
   Ordered by: cumulative time
   List reduced from 2654 to 265 due to restriction <0.1>
   List reduced from 265 to 15 due to restriction <'kalite'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   86.974   86.974 ./kalitectl.py:278(manage)
        1    0.128    0.128   26.240   26.240 ./kalite/settings/__init__.py:1(<module>)
        1    0.056    0.056    0.912    0.912 ./kalite/updates/__init__.py:7(<module>)
        1    0.018    0.018    0.739    0.739 ./kalite/updates/models.py:2(<module>)
        1    0.000    0.000    0.715    0.715 ./kalite/updates/models.py:13(UpdateProgressLog)
        1    0.098    0.098    0.487    0.487 ./kalite/caching/__init__.py:19(<module>)
        1    0.113    0.113    0.186    0.186 ./kalite/distributed/settings.py:1(<module>)
        1    0.112    0.112    0.124    0.124 ./kalite/i18n/__init__.py:10(<module>)
        1    0.022    0.022    0.116    0.116 ./kalite/updates/videos.py:2(<module>)
        1    0.076    0.076    0.087    0.087 ./kalite/topic_tools/api.py:22(<module>)
        1    0.039    0.039    0.084    0.084 ./kalite/settings/base.py:1(<module>)
        1    0.017    0.017    0.080    0.080 ./kalite/facility/__init__.py:1(<module>)
        1    0.030    0.030    0.063    0.063 ./kalite/facility/models.py:2(<module>)
        1    0.021    0.021    0.056    0.056 ./kalite/playlist/__init__.py:1(<module>)
        1    0.018    0.018    0.041    0.041 ./kalite/legacy/i18n_settings.py:15(<module>)
```

Notice the difference for `./kalite/settings/__init__.py:1(<module>)`:
```
        1    0.126    0.126   30.984   30.984 ./kalite/settings/__init__.py:1(<module>)
```

And not restricted to `kalite`:
```
   Ordered by: cumulative time
   List reduced from 2654 to 27 due to restriction <0.01>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   86.974   86.974 ./kalitectl.py:278(manage)
        1    0.000    0.000   59.245   59.245 ./python-packages/django/core/management/base.py:213(run_from_argv)
        1    0.000    0.000   59.242   59.242 ./python-packages/django/core/management/base.py:240(execute)
        1    0.000    0.000   57.962   57.962 ./python-packages/django/core/management/commands/runserver.py:42(handle)
        1    0.000    0.000   57.962   57.962 ./python-packages/django/core/management/commands/runserver.py:72(run)
        1    0.000    0.000   57.962   57.962 ./python-packages/django/utils/autoreload.py:136(main)
        1    0.000    0.000   57.962   57.962 ./python-packages/django/utils/autoreload.py:110(python_reloader)
        1    0.000    0.000   57.962   57.962 ./python-packages/django/utils/autoreload.py:99(restart_with_reloader)
        1    0.000    0.000   57.962   57.962 /usr/lib/python2.7/os.py:565(spawnve)
        1   57.961   57.961   57.961   57.961 {posix.waitpid}
        1    0.000    0.000   29.382   29.382 ./python-packages/django/core/management/__init__.py:350(execute)
        1    0.000    0.000   27.712   27.712 ./python-packages/django/utils/autoreload.py:92(TemporaryUploadedFile)
   131/83    0.001    0.000   27.546    0.332 ./python-packages/django/utils/importlib.py:18(import_module)
   970/88    8.879    0.009   27.545    0.313 {__import__}
```
Notice the difference for `{__import__}`:
```
989/107   11.087    0.011   34.123    0.319 {__import__}
```

Can we tentatively conclude that unburdening the various `__init__.py`s seems to be on the right track? I'll try to make some statistics to investigate this claim.

### CODE REVIEW

**Comment by rtibbles** [comment]
Not sure I am reading this right - is the block of data the one from this PR, and the single line the point of comparison from before?

**Comment by MCGallaspy** [comment]
Yes.

**Comment by rtibbles** [comment]
Even if the performance increases are only marginal, unburdening the `__init__.py`s is going to make our code cleaner and more Pythonic if nothing else.

**Comment by MCGallaspy** [comment]
From this branch, cumulative results (restricted to `kalite`) of starting the server and waiting for 100s, 10 times:
```
Fri May  1 23:05:18 2015    cumulative_server_start_stats.dat.tt_alt

         2269744 function calls (2204763 primitive calls) in 966.694 seconds

   Ordered by: cumulative time
   List reduced from 2656 to 266 due to restriction <0.1>
   List reduced from 266 to 16 due to restriction <'kalite'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.001    0.000  966.764   96.676 ./kalitectl.py:278(manage)
       10    2.638    0.264  509.433   50.943 ./kalite/settings/__init__.py:1(<module>)
       10    0.941    0.094   15.414    1.541 ./kalite/updates/__init__.py:7(<module>)
       10    0.333    0.033   13.064    1.306 ./kalite/updates/models.py:2(<module>)
       10    0.002    0.000   12.508    1.251 ./kalite/updates/models.py:13(UpdateProgressLog)
       10    1.760    0.176    7.853    0.785 ./kalite/caching/__init__.py:19(<module>)
       10    2.528    0.253    4.742    0.474 ./kalite/distributed/settings.py:1(<module>)
       10    0.471    0.047    2.797    0.280 ./kalite/facility/__init__.py:1(<module>)
       10    0.940    0.094    2.555    0.256 ./kalite/settings/base.py:1(<module>)
       10    0.671    0.067    2.327    0.233 ./kalite/facility/models.py:2(<module>)
       10    0.565    0.057    2.279    0.228 ./kalite/playlist/__init__.py:1(<module>)
       10    1.791    0.179    2.000    0.200 ./kalite/i18n/__init__.py:10(<module>)
        9    0.270    0.030    1.402    0.156 ./kalite/updates/videos.py:2(<module>)
       10    1.157    0.116    1.332    0.133 ./kalite/topic_tools/api.py:22(<module>)
       10    0.365    0.036    1.177    0.118 ./kalite/legacy/i18n_settings.py:15(<module>)
       10    0.225    0.023    1.163    0.116 ./kalite/distributed/__init__.py:15(<module>)
```
Data from the other branch coming soon...

I'd really like to see standard deviations, but it's not built in to pstats. :(

**Comment by MCGallaspy** [comment]
From my `profiler` branch. Disappoint results :(
```
Fri May  1 23:28:37 2015    cumulative_server_start_stats.dat.profile

         2277590 function calls (2212570 primitive calls) in 978.116 seconds

   Ordered by: cumulative time
   List reduced from 2655 to 266 due to restriction <0.1>
   List reduced from 266 to 15 due to restriction <'kalite'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.001    0.000  978.162   97.816 ./kalitectl.py:278(manage)
       10    1.893    0.189  310.326   31.033 ./kalite/settings/__init__.py:1(<module>)
       10    0.658    0.066   10.192    1.019 ./kalite/updates/__init__.py:7(<module>)
       10    0.166    0.017    8.090    0.809 ./kalite/updates/models.py:2(<module>)
       10    0.003    0.000    7.778    0.778 ./kalite/updates/models.py:13(UpdateProgressLog)
       10    0.899    0.090    4.861    0.486 ./kalite/caching/__init__.py:19(<module>)
       10    1.468    0.147    2.787    0.279 ./kalite/distributed/settings.py:1(<module>)
       10    0.272    0.027    1.432    0.143 ./kalite/updates/videos.py:2(<module>)
       10    0.525    0.053    1.344    0.134 ./kalite/settings/base.py:1(<module>)
       10    1.221    0.122    1.338    0.134 ./kalite/i18n/__init__.py:10(<module>)
       10    0.161    0.016    1.053    0.105 ./kalite/facility/__init__.py:1(<module>)
       10    0.224    0.022    0.973    0.097 ./kalite/playlist/__init__.py:1(<module>)
       10    0.258    0.026    0.892    0.089 ./kalite/facility/models.py:2(<module>)
       10    0.751    0.075    0.855    0.086 ./kalite/topic_tools/__init__.py:22(<module>)
       10    0.160    0.016    0.613    0.061 ./kalite/distributed/__init__.py:15(<module>)
```

**Comment by MCGallaspy** [comment]
In light of the profiler results (unless I'm misinterpreting them) it doesn't seem like this is actually a performance gain. Close this PR @rtibbles @aronasorman, or is there enough merit in moving stuff out of `__init__.py` to justify it?

**Comment by MCGallaspy** [comment]
This PR is irrelevant. No performance improvement, and I think the longer term plan is to replace this module entirely.

**Pull request closed without merging**
