### PR TITLE
0.15.0

### PR DESCRIPTION
**Pull request by aronasorman**
The intention of this PR is to take a look at all the changes made, as well as allow our users to monitor the progress of 0.15. They can subscribe to this PR and be alerted as to when it's merged to master. I also intend to put a summary of new features here in this description.

### CODE REVIEW

**Comment by benjaoming** [comment]
@aronasorman could you add a comment about the intention of this PR?

**Comment by aronasorman** [comment]
@benjaoming added in description.

**Comment by benjaoming** [comment]
Thanks!! :)

**Comment by benjaoming** [comment]
@aronasorman we could draft the release notes in the comments section of this PR?

**Comment by aronasorman** [comment]
@benjaoming sounds good. I can start the release notes later this week once all the bugfixing has settled, but feel free to do so as well.

**Comment by benjaoming** [comment]
How did these 3 latest commits arrive? Directly or through a PR? @cpauya ?

**Comment by MCGallaspy** [comment]
Uh-oh, merge conflicts. This is on my TODO list tomorrow, as I think we are actually really ready to release 0.15.0 now.

**Comment by benjaoming** [comment]
both modified:      data/version.yml
	both modified:      kalite/main/api_resources.py
	both modified:      kalite/settings/base.py
	both modified:      kalite/version.py

**Comment by benjaoming** [comment]
#4621 is resolving conflicts

**Pull request merged**
