### PR TITLE
Migrate to CircleCI

### PR DESCRIPTION
**Pull request by aronasorman**
Tests should now be passing in CircleCI. Changes:

- delete tests that are skipped in Travis. Addresses #3914.
- Rebased from #3817 to get some behave tests fixed.
- Tweaked circle.yml to get it up-to-date with travis.yml and the latest develop.

### CODE REVIEW

**Comment by aronasorman** [comment]
Supersedes #3817.

**Comment by aronasorman** [comment]
Rebased to develop.

**Comment by aronasorman** [comment]
I'm getting behave errors again after rebasing to develop.

**Comment by rtibbles** [comment]
Guessing these are related to the errors @benjaoming was getting on his pr that was merged earlier today?

**Comment by benjaoming** [comment]
Yes that sounds plausible! I was looking previously at slowness of certain api_view functions that only happen with `runserver` and DEBUG=True but not with `kalite start`... if there's any kind of hint in that.

**Comment by aronasorman** [comment]
After a bit more testing, I noticed that running our behave tests in different ways (i.e. just distributed tests vs. coachreports vs. all the tests) results in different tests failing each time.

I feel right now that our behave tests need more isolation with each other, if we wanna move forward with just making a more robust test suite in general. Shifting to another CI service won't change that.

However, I still see an advantage to switching to CircleCI, mainly because:
1. We can SSH in to the containers.
2. We have 4 containers available PER USER (so we can either make a build run faster by splitting it up, or run more concurrent builds)
3. We can pay to add more containers. Travis doesn't allow you to pay if you're open source.

Right now the plan is to split our tests 2 ways -- run behave tests in one container, run the rest in another. That would mean each build occupies 2 containers, and we can run 2 builds concurrently.

**Comment by aronasorman** [comment]
By per user I mean if you register on CircleCI. Organizations also have 4 containers.

**Comment by benjaoming** [comment]
And Circle builds faster than Travis?

**Comment by aronasorman** [comment]
Without the split it does, but then that's because we've dumped 2.6 at this point. With the split between behave tests and other tests I'm expecting it to be faster, since we're running tests in parallel.

**Comment by benjaoming** [comment]
If it's already evidently faster, I would recommend to remove Travis so we can start benefiting from this new fast CI :)

**Comment by aronasorman** [comment]
Here's the latest build: https://circleci.com/gh/aronasorman/ka-lite/63

CircleCI has a degraded performance right now, which might explain why a majority of the behave tests are suddenly failing.

**Comment by aronasorman** [comment]
So I feel that there are more pressing issues for me to solve now. There are still some test failures, but hey at least tests run a bit faster now :)

I'll leave this up to you guys to merge. Once it's done we can then turn off travis and fully migrate to CircleCI.

**Comment by MCGallaspy** [comment]
I'm ready to merge this, like I mentioned in the other threads. We're pretty confident the features work as intended. That said, merging this will introduce test failures into develop. My suggestion is that we live with this for now (and maybe disable them so we don't wash out other potential legitimate failures) with the promise to revisit them after 0.14 release. And just to be explicit, I'm the one promising to revisit them.

**Comment by benjaoming** [comment]
Agreed, and Travis is already failing on develop: https://travis-ci.org/learningequality/ka-lite/branches

**Pull request merged**
