### PR TITLE
Made 'show scratchpad' more prominent in exercises

### PR DESCRIPTION
**Pull request by Antrikshy**
This targets part of issue #2312. The "show scratchpad" button is hard to find. Since the exercises widget is not loading correctly in the develop branch, I was not able to find a better spot to put the button inside the exercises widget. So I put it at the top, and it looks fine to me.

This is what my version looks like:

screen shot 2015-01-14 at 3 38 41 pm

Here's the before:

screen shot 2015-01-14 at 3 41 58 pm

### CODE REVIEW

**Comment by aronasorman** [comment]
@mikewray will be happy to see this.

**Comment by jamalex** [comment]
Cool! I might recommend having this below the exercise area, so it doesn't push the exercise area off the bottom of the screen for tablet users.

**Comment by Antrikshy** [comment]
Okay, I'll move it to the bottom and maybe make the button color more prominent after my class.

**Comment by Antrikshy** [comment]
Whaddya guys think about this? I just found existing button classes and tweaked some spacing to get this.

screen shot 2015-01-14 at 5 53 11 pm

I'm also working on updating that disabled version of the button.

**Comment by Antrikshy** [comment]
I left that 'not available' message as a `span` instead of a `button` because the JS selecting it may expect it to be a `span`. I added classes to make it a disabled button, but I can't test it until the exercises load up properly.

**Comment by aronasorman** [comment]
Looks good to me.

**Pull request merged**
