### PR TITLE
Issue and PR templates

### PR DESCRIPTION
**Pull request by benjaoming**
Retargeting #4866

Supposed to do a merge of master into 0.16.x, then into develop.

### CODE REVIEW

**Comment by radinamatic** [comment]
Could we have this on other repos (Installers, Kolibri...)?
@MCGallaspy @benjaoming

**Comment by benjaoming** [comment]
@radinamatic sounds like a good idea, you are most welcome to do the honours of a PR with your own adaptations :)

**Comment by radinamatic** [comment]
Yeah, trying to do it now... :)
I remembered in the GitHub blog post about it was mentioned only maintainers can add these templates, so not sure if I have the powers, but will certainly try! @benjaoming

**Comment by benjaoming** [comment]
@radinamatic only maintainers can add stuff to repos, yes :) So if you have merge rights to a repo, you can add files, for instance `.github/ISSUE_TEMPLATE.md`

**Pull request merged**
