### PR TITLE
Docs screenshots fixup

### PR DESCRIPTION
**Pull request by MCGallaspy**
Replaces #4404. I created a weird history after accidentally merging develop instead of 0.15.x and continuing to work on top of it. This should incorporate all the changes.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Two more things. Need to build the screenshots with:

* An internet connection, or the server configured to detect a local running instance of the central server. Otherwise some (registration) pages display incorrectly.
* A downloaded language pack, so that the delete button is visible for a screenshot. Or fiddle around with screenshot settings or setup process to make the server _think_ a language pack is downloaded. @aronasorman any advice on how to make a language pack appear to be downloaded without actually downloading it? Ideally a method which is future proof.

**Comment by MCGallaspy** [comment]
Oh, and I will resolve #4432 and remove cruddy screenshots from the commit history before building and committing a good set.

**Comment by aronasorman** [comment]
re: language pack -- you just need to create a json file in a folder named after the language code. If you wanna fake es:

```
locale/
  es/
     - es_metadata.json

> cat locale/es/
{}
```

That should be the minimal way to fool `kalite` that a language is installed.

**Comment by MCGallaspy** [comment]
Are there any caveats? Does it need to be done before the server starts? Is there any guarantee it won't change in the future, quietly breaking the screenshot again?

**Comment by aronasorman** [comment]
If you do it after server restart you need to force a cache invalidation. There should be functions for that. 

re: guarantee -- we're not planning any huge i18n refactoring soon, and that part of i18n doesn't change much. So it should be stable in the short term.

**Comment by MCGallaspy** [comment]
Empty es_metadata.json as you've described doesn't work -- instead I get a bunch of errors when it fails to find some key from that file. I think for now I will simply actually download a language pack.

**Comment by aronasorman** [comment]
Were you trying to view the `update language packs` page? It should only fail in that page. Otherwise you can fill it with these details:

```
{"num_dubbed_videos": 0, "code": "de", "native_name": "Deutsch", "subtitle_count": 1761, "ka_ntranslations": 184935, "language_pack_version": 17, "package_size": 8777710, "approved_translations": 185679, "percent_translated": 88.96293989411399, "zip_size": 3546260, "software_version": "0.15", "beta": false, "kalite_nphrases": 1435, "num_exercises": 0, "kalite_ntranslations": 744, "name": "German", "phrases": 208715, "ka_nphrases": 207280}
```

**Comment by MCGallaspy** [comment]
It also failed on startup because it lacked the keys `name` and `code`.

**Comment by MCGallaspy** [comment]
But yes, I was trying to "view" that page with a WebDriver, to take screenshots.

**Comment by jamalex** [comment]
> remove cruddy screenshots from the commit history before building and committing a good set.

this sounds like the main remaining piece to me -- I skimmed the code, and nothing popped out (though I'm not really familiar with that code

:+1:

**Comment by MCGallaspy** [comment]
Everything seems to work ok. Probably good to take another pass at it closer to release.

**Pull request merged**
