### PR TITLE
Don't display loginModalView when SuperUserCreateModalView is displayed

### LINKED ISSUE #4834: "Login" modal on top of "Create Admin Account" modal
How to recreate:

1) Have a clean installation w/o user accounts
2) Hit a url that's login protected, for instance: http://localhost:8008/update/videos/

Result:
screenshot from 2016-02-10 19 56 29

Expected result: The "Create Admin Account" is always on top.

### PR DESCRIPTION
**Pull request by 66eli77**
Fixes #4834

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Please use a more descriptive name than "fix for issue #4834" -- the PR name should indicate explicitly what it's fixing, like "Fix error in PlaylistProgress.user_progress method". It makes searching tickets and PRs much easier!

Please reference the issue using the phrase "Fixes #4662" in the body of the PR. It causes the ticket to be closed automatically when the PR is merged.

I also highly recommend writing a test for this -- I know we're troubled by browser tests, but I think the cost of not writing tests is ultimately greater than working out the false positives that we *do* have.

**Comment by benjaoming** [comment]
Everything what @MCGallaspy just said!

**Comment by 66eli77** [comment]
do you want me to write a browser test or unit test for this PR @MCGallaspy

**Comment by MCGallaspy** [comment]
Sadly, we don't have a way to unit test javascript code in KA Lite (unless something has changed very recently @rtibbles). So I recommend writing a browser test. I'm happy to work with you to complete this.

**Comment by 66eli77** [comment]
sounds good, let me know when you want to work on this.

**Comment by rtibbles** [comment]
Yeah, still no unit tests for JS in KA Lite.

I could change this, but I don't want to for 0.16 at the very least.

**Comment by benjaoming** [comment]
Seeing the timeout as unrelated, trying a rebuild..

**Comment by benjaoming** [comment]
Wondering why Circle isn't building 6c582f2, @66eli77 try doing some kind of reset and `push -f` to squash everything into a single commit and see if Circle wants to rebuild?

Something like this: http://makandracards.com/makandra/527-squash-several-git-commits-into-a-single-commit

**Comment by 66eli77** [comment]
@benjaoming how can you tell circle isn't building?

**Comment by benjaoming** [comment]
@66eli77 there was no status icon next to the commit here on Github, and there were no builds with the commit hash on Circle... no idea what was going on.

**Comment by benjaoming** [comment]
Brilliant PR, very concise, has regression tests, neatly done!

**Comment by benjaoming** [comment]
Garh, I'm afraid that after this PR, you can't show the login modal first time you created an admin account.

**Pull request merged**
