### PR TITLE
Fix Unclean shutdown in OS X installer.

### LINKED ISSUE #5211: Unclean shutdown in OS X installer
## Summary

I can install it successfully and start the server but when I load it in browser the server will quit. 

## Branch or installer method

 - Installer: OSX
 - Version: 0.16.7b3
 - Branch: 0.16.x

## Screenshots
f052b7f2-3e69-11e6-9087-7492e24338db

### PR DESCRIPTION
**Pull request by arceduardvincent**
## Summary

Hi @aronasorman and @benjaoming .
I try to upgrade the `requests` base on the suggestion of @cpauya .
I base my upgrade to a higher version of this [requests v0.14.2] (https://github.com/learningequality/ka-lite/blob/v0.16.5/python-packages/requests/__init__.py#L45) since the `requests==2.10.0` has an issue on our `pyrun`. 

## Issues addressed

This fixes #5211 .

## Screenshots (if appropriate)

screen shot 2016-07-27 at 3 04 41 am

## Test Checklist
**Web page:**
- [x] Homepage
- [x] Teach page
- [x] Manage page
- [x] Learn page
- [x] Docs page
- [x] Admin page
- [x] Facility page
- [x] Video download page
- [x] Language Download page

**Functionality:**
- [x] Video download
- [x] Language download
- [x] Register device
- [x] Play Video
- [x] i18n

### CODE REVIEW

**Comment by arceduardvincent** [comment]
This is still work on progress. Don't merge it yet
I want to test it further on my machine using the python2.7.11 in my machine.

**Comment by benjaoming** [comment]
Why version 1.2.3?

**Comment by benjaoming** [comment]
Please see #5138 and #5126

**Comment by arceduardvincent** [comment]
Hello @benjaoming thanks for the pointers. I will test it thoroughly.
I try to use requests v2+ then the `unclean shutdown` is propagated and the `pyrun` crashed.
screen shot 2016-07-27 at 5 40 52 pm

If I use requests v1+ this issue will not occur.

**Comment by benjaoming** [comment]
Is it related to a worker thread downloading videos? It says "Crashed Thread: 5" in your stack trace...

**Comment by arceduardvincent** [comment]
It is not related to a worker thread downloading videos. As you can see in my image attachment the video download is working and the playing the video is ok. 
screen shot 2016-07-27 at 9 51 47 pm
screen shot 2016-07-27 at 9 58 49 pm

**Comment by arceduardvincent** [comment]
`Unclean shutdown/pyrun crashed `manifested on this urls:
`hompage` , `video download page`,  `language download`, `regsiter device`.

Working urls:
`admin`, `learn page`, can view `topic tree`, `docs`.

**Comment by benjaoming** [comment]
The issue with the unclean shutdown is that... the shutdown is unclean :) But how do you experience it? Does KA Lite crash or is it only related to when you deliberately stop KA Lite?

What happens inside KA Lite is that when starting it, it will check the current status.  Checking the status means reading the .pid file, if it's there then we try to verify (with `requests`) that the running server is actually alive.. if this fails, we assume that a server has died and not cleaned up properly.. hence, "unclean shutdown".

**Comment by arceduardvincent** [comment]
@benjaoming as what I experience  on the unclean shutdown the server started but if we access some urls like `home page`,  `video download page` and `language page` the `unclean shutdown` will occur.

If I try to restart the server again and navigate directly on the `learn page`, `management page`, `admin  page` the `pyrun` will not crashed and the unclean shutdown will not occur.

**Comment by arceduardvincent** [comment]
Hi @benjaoming created  .gif file to illustrate the issue. 
This issue manifested on some urls that I mentioned above.
untitled

**Comment by benjaoming** [comment]
@arceduardvincent - can you check the `server.log` file?

**Comment by benjaoming** [comment]
@arceduardvincent any chance the Mac installer also leaves behind pyc files when updating from previous versions as we saw it in #5188?

I'm not convinced this is the issue, but please try to have a go :)

**Comment by arceduardvincent** [comment]
Here's the `server.log` 
```
[INFO] [2016-07-28 17:51:03,984] django.request: HTTP Request /api/content/khan/count-to-100/ - Response: 200
[INFO] [2016-07-28 17:51:04,000] cherrypy.access.4386242896: 127.0.0.1 - - [28/Jul/2016:17:51:04] "GET /static/js/distributed/bundles/bundle_exercise.js HTTP/1.1" 304 - "http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/count-to-100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[INFO] [2016-07-28 17:51:04,358] django.request: HTTP Request /api/cherrypy/getpid - Response: 200
[INFO] [2016-07-28 17:51:04,816] cherrypy.access.4386242896: 127.0.0.1 - - [28/Jul/2016:17:51:04] "GET /static/js/distributed/perseus/ke/genfiles/calculator.js HTTP/1.1" 304 - "http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/count-to-100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[INFO] [2016-07-28 17:51:04,851] cherrypy.access.4386242896: 127.0.0.1 - - [28/Jul/2016:17:51:04] "GET /static/js/distributed/perseus/ke/utils/init-calculator.js HTTP/1.1" 304 - "http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/count-to-100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[INFO] [2016-07-28 17:51:07,322] django.request: HTTP Request /api/assessment_item/x6c066f22fe3c32c9/ - Response: 200
[INFO] [2016-07-28 17:51:07,941] django.request: HTTP Request /images/throbber.gif - Response: 302
[INFO] [2016-07-28 17:51:07,994] cherrypy.access.4376410768: 127.0.0.1 - - [28/Jul/2016:17:51:07] "GET /content/assessment/khan/f8b/f8bff3dd0faa3b170f2afc668c889e8542bfd930.png HTTP/1.1" 200 40444 "http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/count-to-100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[INFO] [2016-07-28 17:51:08,006] cherrypy.access.4386242896: 127.0.0.1 - - [28/Jul/2016:17:51:08] "GET /static/images/throbber.gif HTTP/1.1" 200 3208 "http://127.0.0.1:8008/learn/khan/math/early-math/cc-early-math-counting-topic/cc-early-math-numbers-120/count-to-100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
[INFO] [2016-07-28 17:51:09,210] django.request: HTTP Request /api/cherrypy/getpid - Response: 200
```

It seems there is no error in the log file because the `pyrun` crashed and not able to log the error.
screen shot 2016-07-28 at 5 57 05 pm

**Comment by arceduardvincent** [comment]
I try your suggestion to delete the `*.pyc` but there is no luck. I got the same error.

**Comment by arceduardvincent** [comment]
I added some checklist above. So that I can monitor the `ulrs` and the `functionalities` that is ok.

**Comment by benjaoming** [comment]
@arceduardvincent out of curiosity, can you run KA Lite fine if you just get it from pip and don't use pyrun?

**Comment by benjaoming** [comment]
Also, can you with your pyrun environment try running the kalite command directly from command line? I'm not sure how it works on your Mac.. but try locating `kalitectl.py` and running `pyrun kalitectl.py start --foreground` and see how it works. If possible, try replacing `requests 2.10.0` with `requests 2.9.0`.

**Comment by benjaoming** [comment]
I can't reproduce this on Ubuntu 64bit...

```
➜  ka-lite git:(0.16.x) PYTHONPATH="$PYTHONPATH:/home/benjamin/code/ka-lite/python-packages:/home/benjamin/.virtualenvs/kalite/lib/python2.7/site-packages" /home/benjamin/Desktop/pyrun/bin/pyrun kalitectl.py start --foreground
```

Running KA Lite with the above command gives me a working server where I can navigate the same steps that are shown to crash in the .gif above.

**Comment by arceduardvincent** [comment]
@benjaoming if we use `pip` instead of `pyrun`installing  `ka-lite-static` it works because I am using my native python.

The purpose why we use `pyrun` is to isolate a working environment and not worrying a buggy python setup on the user.

**Comment by arceduardvincent** [comment]
If we use `kalite start --foreground` our application will not crash on `pyrun`.  Using `kalite start` and navigating to a certain `urls` this `unclean shutdown` will replicate.

**Comment by aronasorman** [comment]
@benjaoming @arceduardvincent the main reason we're using pyrun is that the builtin mac python is a very important piece of software for macOS -- a lot of system utilities depend on it, it has some special modules specific to mac OS, and it's generally not recommended that we modify the packages installed there. It's also potentially out of date, depending on the OS version.

If pyrun won't work, can you try installing python from the python.org website and see if it still crashes? Note that `/usr/bin/python` is the mac built in python, and `usr/local/bin/python` is the newly installed python executable.

**Comment by arceduardvincent** [comment]
Hi @benjaoming yeah we can use pyrun run the kalite command directly from the command line. 

Mac Process:
We install the `kalite-static` in our pyrun. Once it installed, we symlink the  `kalite` excutatble into the `/usr/local/bin/kalite`. Now we will able to run `kalite` command in our command line.

If I used `requests 2.x.x` our `pyrun` crashes so that I try to replace  the lower version of the request is which requests 1.x.x`

**Comment by arceduardvincent** [comment]
@aronasorman Yeah If we installed python from the python.org website. It will work. I try it on my machine I already installed python from the python.org website

However there some case scenario that our app might not work. 
Like you mention above this might happen:
* `python` potentially out of date, depending on the OS version.
* They are using python3 which might  not work on our app.
* There python environment might be buggy.

**Comment by benjaoming** [comment]
@arceduardvincent it would be nice if we would know exactly what call to `requests` that crashes pyrun.

There is very little usage of `requests` in KA Lite so it shouldn't be hard. Perhaps you can try to call the below function from `kalite/version.py`?

```
def user_agent():
    """
    HTTP User-Agent header string derived from version, used by various HTTP
    requests sent to learningequality.org for stats
    """
    from requests.utils import default_user_agent
    "ka-lite/%s " % VERSION + default_user_agent()
```

**Comment by benjaoming** [comment]
...might be better to call it from `kalite shell` and then `from kalite.version import user_agent; user_agent()`

**Comment by arceduardvincent** [comment]
Fix in ths `PR` [Downgrade requests because of pyrun issue](https://github.com/learningequality/ka-lite/pull/5241#issuecomment-237217761).

**Pull request closed without merging**
