### PR TITLE
Translate content titles and descriptions with the language requested.

### LINKED ISSUE #4472: Exercise title and assessment item content not translated
Branch: 0.15.x
Ubuntu/Chrome

Expected Behaviour: Both exercise title and assessment item content should be translated.
Current Behaviour: Neither are.

image

### PR DESCRIPTION
**Pull request by aronasorman**
... not with what's available in the dubmap. Fixes #4472.

Previously, we used content_lang for translating content titles and
descriptions, which may or may not have the language being
requested. NOw, we use language for translating that.

I think the reason why this was working properly on 0.14 and not here, was that we switched to using the content cache, which wasn't translating titles and descriptions properly. 0.14 used the topic tree data is my guess.

### CODE REVIEW

**Comment by aronasorman** [comment]
Looks like exercises aren't fixed yet. Will take a look at that.

**Comment by aronasorman** [comment]
Videos:

screen shot 2015-09-23 at 15 37 13

Exercises:

screen shot 2015-09-23 at 15 43 51

Ready to merge.

**Comment by rtibbles** [comment]
Code looks good, will test.

**Comment by rtibbles** [comment]
This works - bad news though, assessment items are still not getting translated, and frankly, it looks like there is no way they could possibly be translated in 0.14 onwards. We dun' messed up badly.

Putting in a PR to your branch that fixes this.

**Comment by aronasorman** [comment]
I'll cherry pick the commit to 0.14.x.

**Comment by rtibbles** [comment]
Will merge when tests pass.

**Pull request merged**
