### PR TITLE
Export defaults to all users

### PR DESCRIPTION
**Pull request by MCGallaspy**
"Fixes" #4668 -- however I'd like to take a closer look and see if this whole page can be polished up a bit. Consider this PR a statement of intent.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
See commit message, perhaps more could be done:

```text
Refactor export view, fix bug where Facility selector is disabled …
I dug through the commit messages to determine that the intent was
to disable the Facility selector when the requesting user is a
FacilityUser (not an admin). Instead of a conditional in the
View's render function, I tried to make the intent more explicit
by exposing a new context variable and putting the disable logic
in the View's is_disabled function.

Also fixes a bug where the Facility selector is erroneously
disabled when some resources are selected.
```

**Comment by benjaoming** [comment]
@MCGallaspy You stated an intention to polish up something in the description? Is that still relevant or should this be merged in time for 0.16.4?

**Comment by MCGallaspy** [comment]
I don't intend to push any more changes for now, but I have identified this page as an area for potential improvement.

**Comment by benjaoming** [comment]
Would you say the current changes are merge-able?

**Comment by MCGallaspy** [comment]
Yes, but as always a second pair of eyes helps.

**Comment by benjaoming** [comment]
Agreed, as I'm not the expert in this department of the codebase, perhaps @66eli77 can have a quick look?

**Comment by benjaoming** [comment]
Perhaps @66eli77 can have a quick look?

**Comment by benjaoming** [comment]
Perhaps @66eli77 can have a VERY QUICK quick look? :)

**Comment by 66eli77** [comment]
Yes, looking

**Comment by 66eli77** [comment]
seems fixed the issue described in #4668 , merged

**Comment by benjaoming** [comment]
Coolios, at least then there's a new feature in 0.16.6 :)

**Pull request merged**
