### PR TITLE
Coverage.io third or fourth stab, will it work?

### PR DESCRIPTION
**Pull request by benjaoming**

### CODE REVIEW

**Comment by aronasorman** [comment]
merge conflict.

**Comment by MCGallaspy** [comment]
Probably because it's been sitting around for so long. What is this PR even all about?

**Comment by rtibbles** [comment]
I imagine it is to get us integrated with coverage.io in order to give a badge that estimates our test coverage.

**Comment by benjaoming** [comment]
Yeah, sorry, will work on this as I recover... made it to Bruxelles airport now!

**Pull request closed without merging**
