### PR TITLE
Preseed dist with content item db

### PR DESCRIPTION
**Pull request by benjaoming**
Fix for #4802

### CODE REVIEW

**Comment by benjaoming** [comment]
@rtibbles would you be able to comment on the most recent test failure?

**Comment by rtibbles** [comment]
Seems to be flakiness in the Item Rating Behave tests - @MCGallaspy any ideas?

**Comment by rtibbles** [comment]
Otherwise, nothing hugely problematic here, except that content data should be coming from an external source, not our old json files.

If we want to just have a content database to seed the dist with, we should probably just have a dummy fixture - as none of the content will be available, except the Khan Exercises (not Perseus).

**Comment by MCGallaspy** [comment]
> Seems to be flakiness in the Item Rating Behave tests - @MCGallaspy any ideas?

I guess it times out waiting for some condition to be fulfilled. Same step passes in another test. I say merge anyway, and we'll address the test separately.

**Comment by benjaoming** [comment]
There were issues about this approach, so we need to implement content DBs from the content packs before this can be used. Manually merging stuff from this PR into #4865.

**Pull request closed without merging**
