### PR TITLE
fix for #4429

### PR DESCRIPTION
**Pull request by 66eli77**
fix No indicator in the topic tree for a specific video after a successful download. #4429

### CODE REVIEW

**Comment by 66eli77** [comment]
@rtibbles feel free to pass the torch to @aronasorman

**Comment by rtibbles** [comment]
Just tested this, @66eli77, and didn't see any change in behaviour.

**Comment by 66eli77** [comment]
@rtibbles you mean the indicator still not change accordingly after successful download or delete?

**Comment by rtibbles** [comment]
Yeah,it stayed exactly the same.

**Comment by rtibbles** [comment]
Oh,sorry, just tried again to double check. Worked this time. Must have had cached JS or something.

**Pull request merged**
