### PR TITLE
Sidebar fix with test

### LINKED ISSUE #3221: Sidebar rendering bug
Browser: Firefox 35
Branch: latest develop as of 10 Mar 2015 13:12 PST
Language: German

screen shot 2015-03-10 at 1 11 46 pm

Opening the exercise given in the url, and then opening the sidebar makes the CSS all wrong. The scrollable area only extends up to a certain point, not the entire sidebar.

### PR DESCRIPTION
**Pull request by MCGallaspy**
Fixes #3221 in `develop`. Opened a separate PR to include a test, instead of waiting for `0.13.x` to be merged back into `develop`. Work in progress, but I felt lazy and wanted Travis to run the tests for me.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
@rtibbles no idea why this test is failing. Any insight?

**Comment by rtibbles** [comment]
Screenshot: https://cloud.githubusercontent.com/assets/8888020/7209316/70bb9fb2-e4fc-11e4-8192-c4eceb574f26.png

**Comment by MCGallaspy** [comment]
Still at a loss. Should I cherry pick the fix without the test @rtibbles?

**Comment by MCGallaspy** [comment]
@rtibbles this has been languishing for so long.

**Comment by rtibbles** [comment]
The main fix is merged in 0.13.x right? What here is not already included from the merge of that to develop?

**Comment by MCGallaspy** [comment]
An attempt at a test. I couldn't get it to run and I haven't revisited it. Is it worth the effort, given that we have bigger problems with JS testing right now?

**Comment by rtibbles** [comment]
Let's leave it. If there is any additional useful code in here, cherry pick
it out and we'll merge it.

**Comment by MCGallaspy** [comment]
Stale. Will pick out the fixes without the test in a new branch targeting 0.13.x, given that #3511 has not been merged either.

**Pull request closed without merging**
