### PR TITLE
Redirect download videos help information to the new FAQ page

### LINKED ISSUE #3619: Bulk-Download Videos link directs to the old FAQ
The link under "Help for downloading videos" directs to https://learningequality.org/ka-lite/faq/ while we now use https://learningequality.org/docs/faq.html 

screen shot 2015-05-08 at 9 58 04 am

### PR DESCRIPTION
**Pull request by foolchan2556**
Fixes #3619  
Replaces the old url with new faq url. As not to hard write the url, central_server_domain is imported.

### CODE REVIEW

**Comment by aronasorman** [comment]
You have merge conflicts @foolchan2556.

**Comment by aronasorman** [comment]
Manually merged.

**Comment by foolchan2556** [comment]
Thanks a lot! BTW, what might cause the conflicts?

**Comment by aronasorman** [comment]
@foolchan2556 conflicts happen when two people work on a piece of code at the same time. In this case, the conflict happened on this line: https://github.com/aronasorman/ka-lite/blob/51c180494f016c3abaf466eb897e50deb6b2bad0/kalite/updates/templates/updates/update_videos.html#l87

I think what happened here was you had an old version of 0.13.x, and someone edited that same general area of the code too.

**Pull request merged**
