### PR TITLE
Paginate Search

### LINKED ISSUE #3244: No way to show all the results in the search page
branch: develop

So we limit the number of results for each content type to 25 items, but then how do I see all the results? There's no button anywhere to expand the search to more than 25 items.

screen shot 2015-03-10 at 2 34 21 pm

Steps to reproduce:
1. Search "mat" in search box and press enter before autocomplete shows up.

### PR DESCRIPTION
**Pull request by rtibbles**
Fixes #3244

Summary of changes:
* Use generator expressions to produce search results
* Paginate search results by 'page' GET parameter
* Add page indicator and 'previous' and 'next' navigation.

image

Note: This has room for improvement, but this is for a first pass to fix up for 0.14.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
This is more of a curiosity than a concern, but some page values (e.g. `?query=diff&page=-1`) cause a `ValueError`.

**Comment by MCGallaspy** [comment]
Also, taking a closer look, we handle some GET parameters (category, max_results) that the user has no way to input, aside from editing the url. Beyond the scope here, but perhaps worth a look in 0.15.

**Comment by MCGallaspy** [comment]
Looks great, I'm happy to merge it, but I'll leave it to @rtibbles in case he wishes to address my comment above (https://github.com/learningequality/ka-lite/pull/3797#issuecomment-109640160) first.

**Comment by rtibbles** [comment]
Yes, would be better to handle the ```ValueError``` more gracefully, will fix before merge.

**Comment by MCGallaspy** [comment]
I'll assume the test succes -> failure is caused by current issues on develop, and the change looks safe. Merging.

**Pull request merged**
