### PR TITLE
Develop to central-develop

### PR DESCRIPTION
**Pull request by aronasorman**

### CODE REVIEW

**Comment by aronasorman** [comment]
Some test failures. Could you try fixing the tests @MCGallaspy?

**Comment by MCGallaspy** [comment]
Regarding the js linting error, that file `kalite/coachreports/static/js/coachreports/exercise_mastery_view.js` exists on `central-develop` but not `develop`... Meaning these branches diverged at some point? `develop` is not simply a fast-forwarded version of `central-develop`? @aronasorman if you initiated this merge through the web interface then I think github attempts a --no-ff merge, which is probably not what we want here.

**Comment by MCGallaspy** [comment]
We should try to merge `central-develop` with `develop` locally, and then submit that as a PR.

**Comment by aronasorman** [comment]
Nondeterministic test failures (again). Merging this manually.

**Pull request merged**
