### PR TITLE
0.16.7b1

### PR DESCRIPTION
**Pull request by benjaoming**
**WARNING!** Merging this, merges and closes all PRs contained in this PR, and they may have a separate review process and amendments following. So don't merge this PR!! :)

New release, manually brewing the distributions:

 * [x] [ka-lite on pypi](https://pypi.python.org/pypi/ka-lite)
 * [x] [ka-lite-static on pypi](https://pypi.python.org/pypi/ka-lite-static)
 * [x] [ka-lite on Launchpad PPA](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite)
 * [ ] OSX installer
 * [ ] Windows installer

## Known issues

See release notes

## Included PRs

#5186 
#5191 
#5192 

## Installer links

  * Debian/Ubuntu: [ka-lite](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite_0.16.7~b1-0ubuntu1_all.deb) | [ka-lite-bundle](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-bundle_0.16.7~b1-0ubuntu1_all.deb) | [ka-lite-raspberry-pi](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-raspberry-pi_0.16.7~b1-0ubuntu1_all.deb)
  * [Windows]() TODO
  * [Mac]() TODO

### PyPi

    pip install ka-lite --pre

or

    pip install ka-lite-static --pre  # bundled dependencies

### CODE REVIEW

**Comment by benjaoming** [comment]
Since there's currently a corrupted file on Pantry, I'm building this beta with 0.16.6 assessment items, and they may indeed not have changed anyways!

**Comment by benjaoming** [comment]
@radinamatic Debian packages now available!

**Comment by radinamatic** [comment]
@benjaoming: Thanks, will test today! :+1:

**Comment by djallado** [comment]
@arceduardvincent locally build windows installer based from this PR and I tested it on IE11 Windows 7. It's working properly.
Here's the snapshot:
screen shot 7b

**Comment by radinamatic** [comment]
Tested the deb installer from Launchpad PPA on Ubuntu 0.16.7 and it seems good to go!

**Comment by djallado** [comment]
I also build OS X installer locally based on this PR. I can install it successfully and start the server but when I load it in browser the server will quit. 
Here's the snapshot:
screen shot mac

**Comment by amodia** [comment]
Hi @benjaoming & @aronasorman We are still working on the `unclean shutdown` issue when running locally built KA Lite OS X Installer based on this PR.

**Comment by aronasorman** [comment]
Closed, as we're on 0.16.7b3 now. I'll open a 0.16.7 PR very soon.

**Pull request closed without merging**
