### PR TITLE
raspberry pi install instruction

### PR DESCRIPTION
**Pull request by j-schwartz**
downloading file is not named ka-lite-raspberry-pi

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Truly? I followed this link (from the docs): https://learningequality.org/r/deb-pi-installer-0-15

And the filename is indeed `ka-lite-raspberry-pi-0.15.0`. Can you provide a link that downloads a different filename?

**Comment by j-schwartz** [comment]
So live on http://ka-lite.readthedocs.org/en/latest/installguide/install_all.html#linux site right now you have a command line prompt that download 0-14:

image

if I try to change it, by editing the Github, I see the 0-15 prompt:

image

Running these later commands (with 0-15 on the Github) on a Raspian Pi, I get the following:

image

image

file gets saved as:
deb-pi-installer-0-15

image


running with the downloaded file:
image

**Comment by MCGallaspy** [comment]
> right now you have a command line prompt that downloads 0-14:

Fixed. We'll formulate more accurate instructions, since the behavior of wget is seemingly to name the output file based on the url -- instead we'd like it to have the filename on the server (the one we indicated in the docs).

**Comment by MCGallaspy** [comment]
Fixed in #4729.

**Comment by benjaoming** [comment]
@j-schwartz thanks for the thorough report! @MCGallaspy's fix is now on http://ka-lite.readthedocs.org/en/0.15.x/installguide/install_all.html#raspberry-pi

**Pull request closed without merging**
