### PR TITLE
Fixed some alignments in sidebar

### PR DESCRIPTION
**Pull request by Antrikshy**
Moved sidebar tab chevron up by a few pixels and changed padding for
sidebar descriptions to make them look slightly cleaner. They were annoying me a bit.

My first pull request!

### CODE REVIEW

**Comment by aronasorman** [comment]
Can you post screenshots of what you did @Antrikshy?

**Comment by Antrikshy** [comment]
screen shot 2015-01-12 at 1 35 15 pm

Very minor changes. The arrow is now centered, the description paragraph has a slight gap on top. It was hugging the title before.

**Comment by aronasorman** [comment]
Eli gave the thumbs up on this, so merging! Congrats @Antrikshy on your first fix!

**Comment by Antrikshy** [comment]
Woo!

**Pull request merged**
