### PR TITLE
0.14 -- Detailed linux installation instructions & link cleanup

### PR DESCRIPTION
**Pull request by MCGallaspy**
Unsure if there's a corresponding issue for this. @jamalex this incorporates the new download redirect scheme. @EdDixon perhaps you can verify that the instructions here are accurate?

### CODE REVIEW

**Comment by aronasorman** [comment]
Links work, text is sane. Merging.

**Comment by MCGallaspy** [comment]
@benjaoming I believe you had wanted to see the url scheme we came up with.

**Comment by MCGallaspy** [comment]
These can be easily changed at this point, but once they "go public" as it were, it might be more problematic.

**Comment by benjaoming** [comment]
Alright, cool, thanks for that @MCGallaspy 

On a side-note, I would recommend that we fix the on screen information to make documentation redundant. I'm not even sure if the on-screen guide is so bad we need documentation for it.

**Comment by MCGallaspy** [comment]
Yeah, I don't think it's bad or that it needs to be fixed, but I guess it can't hurt to have supplemental explanation? At any rate, I believe @jamalex had requested these changes last week, though please correct me if I misremember it.

**Pull request merged**
