### PR TITLE
Hotfix/2987 inconsistent behaviour of dropdown item selection on coach report pages

### PR DESCRIPTION
**Pull request by MCGallaspy**
Replaces #3030.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Nontrivial failing tests... gotta take a look at it.

**Comment by rtibbles** [comment]
Failed only on 2.6. Restarting in case it was non-deterministic, but it may be a matter of not sleeping long enough?

**Comment by rtibbles** [comment]
One issue here is that the two different "Go" buttons have different behaviour.

Although the bottom go button only appears on this page, we should make both the 'Go' buttons produce the same result on this page (i.e. for the top button including topic info and exercise/video in the get parameters, and for the bottom button changing 'report type', 'facility', and 'group'.)

In addition, the exercise/video selector is no longer being picked up, so it is no longer possible to view tabular coach reports for videos. Not sure when this might have vanished, but assume it was during this process.

**Comment by MCGallaspy** [comment]
> One issue here is that the two different "Go" buttons have different behaviour.
@rtibbles I agree that this is problematic. Seems like a cleaner way to handle the issue would be to attach the content type/topic selectors as a subview to the report type/facility/group menu. I was trying to avoid that as it would require writing a new API endpoint (the information used by the type/topic selectors is currently passed as a context variable to the Django template), but maybe I should drink my own Kool-Aid and get rid of this jQuery spaghetti? The disparity of handling half the UI with Backbone and half without is increasing the complexity here.

**Comment by rtibbles** [comment]
I think a simple hack would be fine here that just makes both the 'Go' buttons do the same thing. We can leave the spaghetti for now, unless it hinders your fixing of this.

**Comment by MCGallaspy** [comment]
I guess my willingness to hack this vs. port it all to Backbone depends on the expected lifetime of these templates/views... Are there specific plans to scrap them and start from scratch? If not I'd rather just take the time right now to fix 'em up all purty.

**Comment by rtibbles** [comment]
The teacher dashboards project will hopefully be burning this down by 0.14.

**Comment by MCGallaspy** [comment]
Okay, hack it is, but if I find myself revisiting this module again then I'm just gonna do it the right way

**Comment by MCGallaspy** [comment]
Maybe a python 2.6 specific issue? The offending test passes on my machine with python 2.7, but I'll take a closer look at it.

**Comment by rtibbles** [comment]
Either a Python 2.6 issue, or it's to do with not waiting long enough for the client side content to change. Which is more likely on Python 2.6 as it is generally slower (the same reason we get more non-deterministic test failures on 2.6).

**Pull request merged**
