### PR TITLE
change initial login message to address the issue in #3874

### PR DESCRIPTION
**Pull request by 66eli77**
change initial login message to address the issue in #3874

### CODE REVIEW

**Comment by radinamatic** [comment]
@66eli77, proposal for a bit more elaborated message in line with what @jamalex suggested in #4023:

```
Congratulations! You have successfully created your Admin account, and you are ready to start using KA Lite. To finish the setup procedure you should: </br></br>
1. Login with the Admin username and password you created (use the LOGIN tab above).</br>
2. Register your device.</br>
3. Start creating the users for your facility and downloading content.
```

**Comment by benjaoming** [comment]
Merging for the alpha3.

Agreeing with the text suggestion, but I think we should put ambitions into creating a better "installation wizard" without all the modal magic? And maybe just push this part to a new issue for 0.15?

**Comment by benjaoming** [comment]
Test failure is about a timeout.

**Comment by benjaoming** [comment]
Cherry-picking this to 0.14.x

**Comment by benjaoming** [comment]
@66eli77 remember to make PRs for the 0.14.x branch

**Pull request merged**
