### PR TITLE
fixes error javascript error.

### PR DESCRIPTION
**Pull request by shubhsingh594**
my last commit was giving timeout in circle ci test, im following the idea suggested in https://github.com/learningequality/ka-lite/pull/4861 to try getting it accepted.

### CODE REVIEW

**Comment by benjaoming** [comment]
> This is a flaw from using Sauce but if you deactivate your own repo's registration with Circle, I think it will work by having the tests run through the PR on learningequality's repo. Try removing your Circle repo and **adding another commit**

...That will force Circle to consider running a new test.

**Comment by shubhsingh594** [comment]
my tests are working fine, on my computer, they are failing to pass circle ci test. 
im trying to put in print statements and check the console output in circle  to know where the problem is.

**Comment by benjaoming** [comment]
rebuild, failure looks like a timeout

**Comment by benjaoming** [comment]
Both errors are to be assumed consistent, because they reappeared.

First err:

```
  Scenario: Content is available        # kalite/distributed/features/learn_content.feature:10
    Given I open some available content # kalite/distributed/features/steps/learn_content.py:14
    Given I open some available content # kalite/distributed/features/steps/learn_content.py:14 2.081s
    Then I should see no alert          # kalite/distributed/features/steps/learn_content.py:31
    Then I should see no alert          # kalite/distributed/features/steps/learn_content.py:31 5.510s
      Traceback (most recent call last):
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/learn_content.py", line 35, in impl
          assert_no_element_by_css_selector(context, ".alert")
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 95, in assert_no_element_by_css_selector
          _assert_no_element_by(context, By.CSS_SELECTOR, css_value, wait_time)
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 85, in _assert_no_element_by
          EC.presence_of_element_located((by, value))
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 91, in until_not
          raise TimeoutException(message)
      TimeoutException: Message
```

...I don't know why we are doing these tests, because waiting for an object to *not* appear seems like a terrible idea anyways. You are more than welcome to add tighter timeouts for this so it succeeds before Selenium raise a TimeoutException. Furthermore, the function `_assert_no_element_by` should perhaps catch this specific exception and consider it a success!?

As for the second error (`NotFound: User playlist progress details with user ID 'bb535b13277645bebdd8da7008b3a58e' and playlist ID 'cc-early-math-two-digit-compare' were not found.`), it's probably related to your local database being populated. You need to ensure that all test data is isolated within your test case.

**Comment by shubhsingh594** [comment]
thankyou @benjaoming  ill try and fix it.

just for information : i'm using this PR to test my commits, once i succeed ill probably just close this and request a  new cleaner PR.

**Comment by shubhsingh594** [comment]
closing this PR, will make a new, cleaner PR. thankyou @benjaoming.

new PR - https://github.com/learningequality/ka-lite/pull/4893

**Pull request closed without merging**
