### PR TITLE
Don't run all our tests with DEBUG=True

### PR DESCRIPTION
**Pull request by rtibbles**
I don't really have any words for this.

image

### CODE REVIEW

**Comment by MCGallaspy** [comment]
I'm keen to merge this, but I'm also keen to see what happens on the build first.

**Comment by rtibbles** [comment]
Yeah, I kind of want to throw 5 bucks at Travis to get them to run this build faster.

**Comment by MCGallaspy** [comment]
I'm running the tests locally, will report.

**Comment by MCGallaspy** [comment]
Oh no, something weird happened and my test output got eaten!

**Comment by aronasorman** [comment]
Only 1 error now!

**Comment by rtibbles** [comment]
No errors now! Should have mentioned that this fixes #3764.

**Comment by aronasorman** [comment]
Let's merge this!

**Pull request merged**
