### PR TITLE
down-scale oversized image

### PR DESCRIPTION
**Pull request by benjaoming**
@jtamiace @66eli77

### CODE REVIEW

**Comment by benjaoming** [comment]
Ah sorry, this was @MCGallaspy making :) Mike, we're not supposed to handle graphics :D

**Comment by MCGallaspy** [comment]
I told them that, but they threatened to withhold my coffee if I didn't do it. :(

**Comment by jamalex** [comment]
Looks good -- can you just fix the tests, and then we can merge?

**Comment by benjaoming** [comment]
@jamalex I changed a .png...

**Comment by rtibbles** [comment]
Should have done [skip ci]...

**Comment by rtibbles** [comment]
Test failures consistent with develop.

**Comment by benjaoming** [comment]
It sounds like we need to test those tests to check that `new failures == old failures`

asd

**Pull request merged**
