### PR TITLE
Unbundle unused playground #3676

### PR DESCRIPTION
**Pull request by benjaoming**
#3676

### CODE REVIEW

**Comment by benjaoming** [comment]
Only two completely unrelated Behave test failures. Would be nice to have these failing tests removed soon!!!

**Comment by MCGallaspy** [comment]
One would hope that a failing test is truly an error instead of random failure; if it's the latter I'll open an issue and try to fix it. In the future if a test fails and you think it's not an actual regression, please open an issue.

**Comment by MCGallaspy** [comment]
Indeed, a legitimate error! But fixed by https://github.com/learningequality/ka-lite/commit/9434bcfcfa327727df4fee880b99cdb47996730c.

**Comment by benjaoming** [comment]
@MCGallaspy I'd normally do that but yesterdays meeting made me confused about whether these are tests that are expected to fail (and also completely unrelated to the contents of this PR) and I thought they would be disabled.

Indeed, failing tests are totally annoying.

**Comment by benjaoming** [comment]
@MCGallaspy seems that travis is finally happy :)

**Pull request merged**
