### PR TITLE
Profiler

### PR DESCRIPTION
**Pull request by MCGallaspy**
Let's discuss the options for profiling. I played around with various methods for a while, and there are 2 that I think have merit:

1. As in `profile_server_start.py`, start the server wrapped in a profiler. Advantage: it's going to profile what's actually happening.  Disadvantage: lots of "noise" -- though clever processing of the results can focus in on what's relevant.

2. Targeted profiling of functions with a decorator. See `kalite/distributed/profiler.py`. Advantage: more specific. Disadvantage: we have to guess where the hotspots are.

As it is, the files the profiler dumps it's data to are relative to the directory from which you start the server. (So for me, it's been dumping everything in the project root.) Is there a better way?

Just for grins, here's some output from profiling `get_content_cache`, sorted by cumulative time spent in each function and restricted to functions in `kalite` or `python-packages`:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.619    0.619   69.442   69.442 /vagrant/kalite/topic_tools/__init__.py:241(get_content_cache)
        2    0.001    0.001   41.930   20.965 python-packages/fle_utils/general.py:252(softload_json)
36965/14795   21.084    0.001   39.694    0.003 python-packages/fle_utils/general.py:223(json_ascii_decoder)
     7377    1.260    0.000   18.381    0.002 /vagrant/kalite/i18n/__init__.py:149(get_id2oklang_map)
    36421    1.355    0.000    9.610    0.000 /vagrant/kalite/i18n/__init__.py:177(get_video_id)
    36421    0.642    0.000    7.826    0.000 /vagrant/kalite/i18n/__init__.py:135(get_file2id_map)
    22131    0.441    0.000    7.287    0.000 /vagrant/kalite/topic_tools/__init__.py:593(is_content_on_disk)
        2    0.004    0.002    7.043    3.522 /vagrant/kalite/i18n/__init__.py:74(get_dubbed_video_map)
     7377    0.080    0.000    4.898    0.001 /vagrant/kalite/topic_tools/__init__.py:232(create_thumbnail_url)
    51044    0.490    0.000    2.810    0.000 /vagrant/kalite/i18n/__init__.py:271(lcode_to_django_lang)
     7377    0.180    0.000    2.549    0.000 /vagrant/kalite/i18n/__init__.py:396(select_best_available_language)
    51506    0.690    0.000    2.244    0.000 /vagrant/kalite/i18n/__init__.py:280(convert_language_code_format)
    14754    0.135    0.000    0.884    0.000 /vagrant/kalite/i18n/__init__.py:479(translate_block)
    12906    0.081    0.000    0.829    0.000 python-packages/django/utils/translation/__init__.py:64(gettext)
    12906    0.079    0.000    0.748    0.000 python-packages/django/utils/translation/trans_real.py:269(gettext)
    12906    0.327    0.000    0.669    0.000 python-packages/django/utils/translation/trans_real.py:241(do_translate)
     7377    0.098    0.000    0.297    0.000 /vagrant/kalite/i18n/__init__.py:213(get_srt_path)
    29511    0.196    0.000    0.284    0.000 python-packages/django/conf/__init__.py:51(__getattr__)
     7377    0.054    0.000    0.185    0.000 python-packages/django/utils/translation/__init__.py:89(activate)
     7377    0.062    0.000    0.132    0.000 python-packages/django/utils/translation/trans_real.py:177(activate)
     7377    0.049    0.000    0.122    0.000 python-packages/django/utils/translation/__init__.py:92(deactivate)
       78    0.015    0.000    0.098    0.001 /vagrant/kalite/i18n/__init__.py:117(get_langcode_map)
     7377    0.050    0.000    0.074    0.000 python-packages/django/utils/translation/trans_real.py:185(deactivate)
      462    0.009    0.000    0.072    0.000 /vagrant/kalite/i18n/__init__.py:277(lcode_to_ietf)
     7377    0.048    0.000    0.070    0.000 python-packages/django/utils/translation/trans_real.py:96(translation)
     7377    0.022    0.000    0.022    0.000 /vagrant/kalite/i18n/__init__.py:166(get_youtube_id)
        1    0.000    0.000    0.000    0.000 python-packages/django/utils/translation/__init__.py:45(__getattr__)
        1    0.000    0.000    0.000    0.000 /vagrant/kalite/i18n/__init__.py:233(get_code2lang_map)
```

More profiling coming soon.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Here's some profile results from server startup, sorted by cumulative time:
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  151.877  151.877 ./kalitectl.py:278(manage)
        1    0.000    0.000  119.706  119.706 ./python-packages/django/core/management/__init__.py:350(execute)
        1    0.000    0.000  119.185  119.185 ./python-packages/django/core/management/base.py:213(run_from_argv)
        1    0.000    0.000  119.175  119.175 ./python-packages/django/core/management/base.py:240(execute)
        1    0.000    0.000  117.759  117.759 ./python-packages/django/core/management/commands/runserver.py:42(handle)
        1    0.000    0.000  117.759  117.759 ./python-packages/django/core/management/commands/runserver.py:72(run)
        1    0.000    0.000  117.759  117.759 ./python-packages/django/utils/autoreload.py:136(main)
        1    0.000    0.000  117.759  117.759 ./python-packages/django/utils/autoreload.py:110(python_reloader)
        1    0.002    0.002  117.758  117.758 ./python-packages/django/utils/autoreload.py:92(reloader_thread)
       37    1.955    0.053   80.985    2.189 ./python-packages/django/utils/autoreload.py:55(code_changed)
    49705   77.655    0.002   77.655    0.002 {posix.stat}
    25129    0.610    0.000   40.581    0.002 /usr/lib/python2.7/genericpath.py:15(exists)
       37   36.771    0.994   36.771    0.994 {time.sleep}
  989/107   11.087    0.011   34.123    0.319 {__import__}
   131/83    0.004    0.000   32.472    0.391 ./python-packages/django/utils/importlib.py:18(import_module)
        2    0.023    0.011   32.170   16.085 ./python-packages/django/core/management/__init__.py:80(get_commands)
   345/71    0.007    0.000   31.042    0.437 ./python-packages/django/conf/__init__.py:51(__getattr__)
      2/1    0.000    0.000   31.040   31.040 ./python-packages/django/conf/__init__.py:30(_setup)
      2/1    0.012    0.006   31.023   31.023 ./python-packages/django/conf/__init__.py:122(__init__)
        1    0.126    0.126   30.984   30.984 ./kalite/settings/__init__.py:1(<module>)
    161/1    0.199    0.001   30.568   30.568 ./python-packages/fle_utils/settingshelper.py:26(import_installed_app_sett
ings)
        1    0.100    0.100   15.648   15.648 ./python-packages/django/contrib/admin/__init__.py:3(<module>)
        1    0.167    0.167   11.367   11.367 ./python-packages/django/contrib/admin/helpers.py:1(<module>)
        1    0.060    0.060    6.069    6.069 ./python-packages/django/forms/__init__.py:11(<module>)
        1    0.054    0.054    5.988    5.988 ./python-packages/django/forms/fields.py:3(<module>)
        1    0.057    0.057    5.452    5.452 ./python-packages/django/forms/util.py:1(<module>)
        1    0.054    0.054    5.049    5.049 ./python-packages/django/utils/timezone.py:4(<module>)
```

**Comment by MCGallaspy** [comment]
Same as above but restricted to functions in `kalite`
```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000  151.877  151.877 ./kalitectl.py:278(manage)
        1    0.126    0.126   30.984   30.984 ./kalite/settings/__init__.py:1(<module>)
        1    0.057    0.057    0.976    0.976 ./kalite/updates/__init__.py:7(<module>)
        1    0.017    0.017    0.800    0.800 ./kalite/updates/models.py:2(<module>)
        1    0.000    0.000    0.760    0.760 ./kalite/updates/models.py:13(UpdateProgressLog)
        1    0.082    0.082    0.469    0.469 ./kalite/caching/__init__.py:19(<module>)
        1    0.123    0.123    0.212    0.212 ./kalite/distributed/settings.py:1(<module>)
        1    0.018    0.018    0.154    0.154 ./kalite/facility/__init__.py:1(<module>)
        1    0.030    0.030    0.136    0.136 ./kalite/facility/models.py:2(<module>)
        1    0.111    0.111    0.122    0.122 ./kalite/i18n/__init__.py:10(<module>)
        1    0.038    0.038    0.121    0.121 ./kalite/settings/base.py:1(<module>)
        1    0.021    0.021    0.118    0.118 ./kalite/updates/videos.py:2(<module>)
        1    0.011    0.011    0.109    0.109 ./kalite/distributed/__init__.py:15(<module>)
        1    0.078    0.078    0.089    0.089 ./kalite/topic_tools/__init__.py:22(<module>)
        1    0.022    0.022    0.058    0.058 ./kalite/playlist/__init__.py:1(<module>)
```

**Comment by MCGallaspy** [comment]
So about a fifth of the total time is spent in the `kalite.settings` module. @benjaoming any inkling why?

**Comment by aronasorman** [comment]
> `49705   77.655    0.002   77.655    0.002 {posix.stat}`

Yep, we got tons of files. And a lot of that is just looking at their attributes. Wonder how we can reduce this time?

**Comment by benjaoming** [comment]
> So about a fifth of the total time is spent in the kalite.settings module. @benjaoming any inkling why?

I would take a wild guess and point to `import_installed_app_settings` which is an annoying function that dynamically loads `xxx.settings` from everything in `INSTALLED_APPS` which may be hidden from what the profiler profiles.

Loading those `xxx.settings` modules will trigger each modules `__init__`, which has been "overloaded" with functionality in all applications.

**Comment by rtibbles** [comment]
Topic_tools is a particular offender. I can work with @MCGallaspy to 'unload' the __init__.pys

**Comment by benjaoming** [comment]
So yes probably there are things that take a lot of time during initialization.. this should not be in kalite.settings (which will not exist in the future) or django.conf.settings...

But apart from that, there are probably things that are preloaded by the server at load-time which would otherwise have been initialized at the first call to a view function... but nonetheless have to be loaded at some point :)

If @MCGallaspy it's possible to quickly verify this theory by digging deeper, please do so :) But I think we can also let it linger until we have refactored into a `kalite_project` and are running `xxx.settings` as a module that is only loaded by the applications themselves...

See also: #2952

**Comment by aronasorman** [comment]
It might be good to create a fork of `runserver` which uses Linux's `inotify` API (instead of `stat`ing each and every file periodically).

**Comment by aronasorman** [comment]
that should reduce our processing.

**Comment by benjaoming** [comment]
@aronasorman this only affects DEBUG mode, right?

**Comment by aronasorman** [comment]
@benjaoming yes, but since most of us devs are running Linux and with DEBUG = True, even just improving this would improve our dev productivity.

**Comment by benjaoming** [comment]
:+1:

**Comment by aronasorman** [comment]
Pushed for 0.15.

**Comment by MCGallaspy** [comment]
Stale

**Pull request closed without merging**
