### PR TITLE
Attempts to ensure against inappropriately flagging topics as complete.

### LINKED ISSUE #4959: Video download: Topic shown as completed but subtopics aren't
## Summary

I've run videoscan a couple of times and I don't believe it annotates the tree correctly, although it completes without errors.

## Branch or installer method

 - Installer: Debian
 - Version: 0.16b1

## How to reproduce

1. Download lots of videos
1. Copy some old stuff into the content folder
1. Run `videoscan`

## Screenshots

Partner contents shown as completed but sub topics aren't:

screenshot from 2016-03-03 15 07 34

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Speculative attempt to prevent uncompleted topics from being shown as complete.

## Reviewer guidance

Stronger checking on files_complete attribute.

## Issues addressed

Tries to fix #4959

### CODE REVIEW

**Comment by benjaoming** [comment]
@rtibbles it's hard to inspect for me, since I don't have access to the original setup... but I can try releasing it as a beta and see if it works...

**Comment by rtibbles** [comment]
Yeah, I couldn't replicate it for much the same reasons.

**Comment by benjaoming** [comment]
Even though this cannot be tested manually, can we safely merge it?

**Comment by rtibbles** [comment]
Shouldn't affect anything.

**Pull request merged**
