### PR TITLE
Fix i18n for exercises (KE templates, and interface text)

### PR DESCRIPTION
**Pull request by rtibbles**

### CODE REVIEW

**Comment by aronasorman** [comment]
Testing now.

**Comment by aronasorman** [comment]
image

**Comment by aronasorman** [comment]
@jinchuika the other half of the i18n bugs that you found.

**Comment by jinchuika** [comment]
@aronasorman Great. Will this be a system update instead of a language pack update?

**Comment by aronasorman** [comment]
Yup, it's a system update. We'll be issuing another update with these fixes.

**Pull request merged**
