### PR TITLE
Fixes to logic in setup management command for loading content packs.

### PR DESCRIPTION
**Pull request by jamalex**
## Summary

@aronasorman knows what's what, and I gotta run. Can add more notes later as needed.

### CODE REVIEW

**Comment by aronasorman** [comment]
This is the situation as I understand it. @jamalex feel free to correct me:

Currently, both the PyPI and deb installer will always ask if a user wishes to download and install `en.zip`, even if `khan_assessment.zip` are installed by the installer/installed beforehand.

They best solution we arrived to, is to reinstate the `assessmentitems.version` file in both `en.zip` and `khan_assessment.zip`, and then have the setup process check for the existence of said file and the version contained, to see if it's up-to-date. If not, then we ask if they want to update their content pack.

**Comment by aronasorman** [comment]
cc: @cpauya @benjaoming @MCGallaspy.

**Comment by aronasorman** [comment]
@jamalex test failures seem related to your changes.

**Comment by aronasorman** [comment]
Tested with the sdist and `en.zip`; works as expected, it skipped the download prompt.

**Comment by aronasorman** [comment]
I get this error with the sdist and `khan_assessment.zip`:

```
Step 5 : RUN kalite manage unpack_assessment_zip ./khan_assessment.zip
 ---> Running in 483a564cbe4e
Error reading secret key file. Generating one now. Error was: [Errno 2] No such file or directory: '/root/.kalite/secretkey.txt'
[WARNING] [2016-04-01 00:09:45,952] kalite: Channel khan does not exist.
[INFO] [2016-04-01 00:09:46,002] kalite: Unpacking...
...............[INFO] [2016-04-01 00:10:02,025] kalite: Scanning items and updating content db...
.[INFO] [2016-04-01 00:10:02,059] kalite: Annotating content for language: en, channel: khan
[ERROR] [2016-04-01 00:10:02,067] kalite: No content database file found
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/kalite/contentload/management/commands/unpack_assessment_zip.py", line 81, in handle
    call_command("annotate_content_items")
  File "/usr/share/kalite/python-packages/django/core/management/__init__.py", line 161, in call_command
    return klass.execute(*args, **defaults)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/kalite/topic_tools/management/commands/annotate_content_items.py", line 43, in handle
    annotate_content_models(database_path=database_path, channel=channel, language=language)
  File "/usr/local/lib/python2.7/dist-packages/kalite/topic_tools/content_models.py", line 128, in wrapper
    output = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/kalite/topic_tools/content_models.py", line 702, in annotate_content_models
    for path, update in content_models:
  File "/usr/local/lib/python2.7/dist-packages/kalite/topic_tools/content_models.py", line 607, in iterator_content_items
    items = Item.select().dicts().iterator()
  File "/usr/share/kalite/dist-packages/peewee.py", line 2797, in iterator
    return iter(self.execute().iterator())
  File "/usr/share/kalite/dist-packages/peewee.py", line 2787, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/usr/share/kalite/dist-packages/peewee.py", line 2470, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/usr/share/kalite/dist-packages/peewee.py", line 3199, in execute_sql
    self.commit()
  File "/usr/share/kalite/dist-packages/peewee.py", line 3048, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/share/kalite/dist-packages/peewee.py", line 3191, in execute_sql
    cursor.execute(sql, params or ())
OperationalError: no such table: item
```

**Comment by aronasorman** [comment]
Adding `--foreground` does not solve the problem.

Seems like it's not finding the `content.db`. I thought we copied it to the right directory @benjaoming? Maybe not so for the sdist?

**Comment by aronasorman** [comment]
For reference, here's the dockerfile I use to test this:

```
ROM gcr.io/google_appengine/python

COPY ka-lite*-static-*.tar.gz .
COPY khan_assessment.zip .
RUN pip install ka-lite*.tar.gz
RUN kalite manage unpack_assessment_zip ./khan_assessment.zip
ENTRYPOINT kalite manage setup
```

**Comment by aronasorman** [comment]
Working with @ralphiee22 to investigate this issue.

We tried to see where kalite is expecting the content db to be, then find out if it exists:

```
>>> os.path.exists('/root/.kalite/database/content_khan_en.sqlite')
False
>>> 
root@4fb0910d6a1b:/home/vmagent/app# find / -name content_khan_en.sqlite
/usr/local/lib/python2.7/dist-packages/kalite/database/templates/content_items/content_khan_en.sqlite
root@4fb0910d6a1b:/home/vmagent/app# 
```

Looks like it doesn't extract it anywhere at all. Expected behaviour @benjaoming? Is this the responsibility of an installer?

**Comment by aronasorman** [comment]
Great success! After ignoring that error it successfully skips the content pack download prompt and continues on.

PR does what it intends to do. Once tests are fixed we can merge this.

**Comment by jamalex** [comment]
> @jamalex test failures seem related to your changes.

@aronasorman Can you point me to the specific failures you're referring to? I'm having trouble parsing out the test results. Only errors I see are:
`[ERROR] [2016-03-31 21:47:16,122] kalite: Failed to end_user_activity upon logout: {'user': [u"Model facility user with pk u'39ce8862ffd94ce4a9ccc0d9df3bea64' does not exist."]}` and some Selenium stuff, which don't seem related.

**Comment by aronasorman** [comment]
Failures are unrelated to changes. Succeeds on Jamie's PC. Merging so we can get 0.16.1 out.

**Pull request merged**
