### PR TITLE
Titles and descriptions are identically styled in sidebar

### LINKED ISSUE #2974: Titles and descriptions are identically styled in sidebar
Expected: Descriptions would be clearly separated from (and perhaps de-emphasized/shrunk with respect to) the titles.

Observed:
image

### PR DESCRIPTION
**Pull request by amodia**
Hi @aronasorman this fixed #2974 

I adjust the `sidebar topic description font size to 0.9em` and  add `margin top 15px`.

i attached a screenshot.
screen shot 2015-02-11 at 1 54 47 pm

### CODE REVIEW

**Comment by jamalex** [comment]
Would be good to have the descriptions slightly lower contrast
(color-wise), as well.

Might be good to get a designer's eye on it -- could you flag someone in,
@aronasorman?

**Comment by amodia** [comment]
Hi @jamalex yeah i think we need a designer's to eye on it for the `contrast color`.

**Comment by MCGallaspy** [comment]
I'm not the designer you're looking for, but I *am* the designer you need. (Or something.) Opened a PR on mrpau's branch.

**Comment by amodia** [comment]
Hi @MCGallaspy done merging your pull request.

**Comment by cpauya** [comment]
Thanks for those designer's eyes @MCGallaspy!  Just what we need indeed. :+1: :smile_cat:

**Pull request merged**
