### PR TITLE
Coverage metrics for 0.15.x #2

### PR DESCRIPTION
**Pull request by benjaoming**
Opening another PR hoping for a Coveralls callback....

### CODE REVIEW

**Comment by benjaoming** [comment]
Now it works!

https://coveralls.io/builds/3485556

**Comment by benjaoming** [comment]
Btw it works like this:

 - Circle runs 2 jobs in parallel, meaning in separate VMs!
 - Each VM creates a coverage report (`coverage run`) and saves it in a file.
 - Each VM uses `COVERAGE_PARALLEL=true` environment for the `coveralls` command which submits the job to coveralls.io
 - After everything is done, a webhook is called (in the `notify` section of `circle.yml`), and coverage.io then combines the metrics.

**Comment by MCGallaspy** [comment]
Why'd ya close this?

**Comment by benjaoming** [comment]
I was using a branch called "0.15.x" and I thought it might confuse me on Monday :)

**Comment by benjaoming** [comment]
#4376

**Pull request closed without merging**
