### PR TITLE
0.16b3

### PR DESCRIPTION
**Pull request by kalitebuilder**
**WARNING!** Merging this, merges and closes all PRs contained in this PR, and they may have a separate review process and amendments following. So don't merge this PR!! :)

Takes over  0.16b2 #4968 

New release, manually brewing the distributions:

 * [x] [ka-lite on pypi](https://pypi.python.org/pypi/ka-lite)
 * [x] [ka-lite-static on pypi](https://pypi.python.org/pypi/ka-lite-static)
 * [x] [ka-lite on Launchpad PPA](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite)
 * [ ] OSX installer
 * [ ] Windows installer

## Known issues

 * [ ] Raspberry Pi still can only download 1 video at a time #4907 
 * [x] Content packs are to be updated, videos show up twice on Video download page
 * [x] After you create the first admin user account, you need to reload the page before clicking Login #4896
 * [x] Video download counts reported misleading #4929 
 * [ ] [See remaining issue list for Milestone](https://github.com/learningequality/ka-lite/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.16.0)

## Included PRs

#5023
#5016 
#4997

## Installer links

  * Debian/Ubuntu: [ka-lite](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite_0.16~b3-0ubuntu1_all.deb) | [ka-lite-bundle](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-bundle_0.16~b3-0ubuntu1_all.deb) | [ka-lite-raspberry-pi](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-raspberry-pi_0.16~b3-0ubuntu1_all.deb)
  * [Windows]() TODO
  * [Mac]() TODO

### CODE REVIEW

**Comment by kalitebuilder** [comment]
Source is up on PyPi. Building debian installers...

**Comment by benjaoming** [comment]
Installers built, PPA refreshed and ready in 10 minutes.

**Comment by benjaoming** [comment]
Something was merged into 0.16.x that doesn't like the PRs merged into this release, but that's life :)

As for the release, 0.16b3 is on Launchpad!

**Comment by benjaoming** [comment]
0.16.0 has subsequently been released, no need to track this further.

**Pull request closed without merging**
