### PR TITLE
Quick fix for resource titles

### PR DESCRIPTION
**Pull request by mrpau-eugene**
## Summary

When trying to select a `Theme` inside `Teach` tab and submits it, the `Show Tabular Reports` displays resource titles in English.

## Reviewer guidance
Just a quick fix.

## Issues addressed
#5494 

pinging @radinamatic @benjaoming for this

### CODE REVIEW

**Comment by benjaoming** [comment]
No errors and 100% coverage, looks good!

**Comment by radinamatic** [comment]
Nice fix @mrpau-eugene! :+1: 

Not sure if there is possibility to fix these remaining strings, it would be a real bonus... :wink: 

Otherwise make sure to grab the latest PO files from Crowdin, as I've translated the `Color legend` by @benjaoming , but it's still showing in English. 

w7 start running - oracle vm virtualbox_541

**Comment by mrpau-eugene** [comment]
@rtibbles is there anyway to internationalize the texts that @radinamatic highlighted which are: `All selected` and `Search`, without touching the bootstrap-multiselect files?

I only managed to translate the `Submit` string since it wasn't wrapped with an `_`.

**Comment by rtibbles** [comment]
@mrpau-eugene looks like you can configure the `allSelectedText` option http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-allSelectedText and the http://davidstutz.github.io/bootstrap-multiselect/#configuration-options-nonSelectedText option? I think that would be the way to internationalize it. Assuming I have got the right plugin here!

**Comment by mrpau-eugene** [comment]
@rtibbles thanks!

**Pull request merged**
