### PR TITLE
Minimal change to homepage to remove outdated image

### PR DESCRIPTION
**Pull request by MCGallaspy**
ss

Not trying to steal anyone's thunder, but I just wanted a minimal fix for #3234 in order to remove the release blocker label. This shouldn't close that issue, just lower the urgency of it.

### CODE REVIEW

**Comment by mjptak** [comment]
rotating thank you art from kids around the world telling you how how
awesome learning with kalite/learning equality...that's what should go
there.  ...or a picture of a cat.

**Comment by aronasorman** [comment]
So minimal!

**Comment by 66eli77** [comment]
could we replace the bbig 'Learn!' button to a image at least? since there is already a learn tab on top. something like this https://drive.google.com/drive/u/1/#folders/0B1eobeaicL7IcnMzMktXM3RzajQ/0BxUUXPepFdM3cW1LZkpmRkRqbkE/0BxUUXPepFdM3MlFQMlRQMEVmMFk/0BxUUXPepFdM3UFBkT1hib1JmRVk

or this
https://drive.google.com/drive/u/1/#folders/0B1eobeaicL7IcnMzMktXM3RzajQ/0BxUUXPepFdM3cW1LZkpmRkRqbkE/0BxUUXPepFdM3NTVXck1aQXBYbzA

**Comment by MCGallaspy** [comment]
@66eli77 one of those resources is a .psd file... can you flatten it?

**Comment by MCGallaspy** [comment]
ss
@66eli77 ta-da

**Comment by rtibbles** [comment]
Not so sure about using this, as the focus here should be on the KA content, rather than FLE, no?

**Comment by MCGallaspy** [comment]
ss
@rtibbles @66eli77 how's this?

**Comment by jamalex** [comment]
> @rtibbles @66eli77 how's this?

Cool image, and might be nice there, but would be nice to:

- Have the background transparent (or the parent white)
- Not have so much vertical space
- Not lose the final "d" of "disconnected"

**Comment by MCGallaspy** [comment]
@jamalex noted

**Comment by MCGallaspy** [comment]
ss

**Comment by MCGallaspy** [comment]
It's ridiculous that this should fail tests. I'd say feel free to merge if you guys think the image is okay.

**Comment by aronasorman** [comment]
Both nondeterministic test failures, what a coincidence.

**Comment by rtibbles** [comment]
Yep, let's merge.

**Pull request merged**
