### PR TITLE
allow for CONTENT_ROOT to be set with an environment variable,

### PR DESCRIPTION
**Pull request by xaiki**
## Summary

*Short description*

## TODO

If not all TODOs are marked, this PR is considered WIP (work in progress)

- [ ] Have **tests** been written for the new code? If you're fixing a bug, write a regression test (or have a really good reason for not writing one... and I mean **really** good!)
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

*If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)*

## Screenshots (if appropriate)

*They're nice. :)*

We use this at endlessm.com to allow sharing content whilst keeping the databases separate (we merge them on launch).

Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>

### CODE REVIEW

**Comment by benjaoming** [comment]
@aronasorman I think we can let this in, please have a look :) My comment is in the previous #5189

**Comment by mariospr** [comment]
It seems like the CI system failed due to a timeout of some sort. Would it be possible to trigger it to run again, to rule out any issue coming directly from the patch itself?

**Comment by aronasorman** [comment]
@mariospr the change seems innocuous enough, and our kalite tests do have these infamous timeout tests. I'll merge this in and make sure this gets in for 0.16.7!

**Comment by mariospr** [comment]
I suspected that could be the case, but being an "outsider" to this project I of course did not dare to make such an assumption. Thanks a lot for merging it! :)

**Pull request merged**
