### PR TITLE
Django js reverse

### PR DESCRIPTION
**Pull request by rtibbles**
Adds Django JS Reverse to expose a Urls object in client side code for access to Django URLs in the browser.

Summary of changes:
* Adds django_js_reverse app
* Ports as many Javascript referenced URLs as possible over to the Urls object.

Note: Tastypie messes it all up. Again.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
@rtibbles What's the note about?

**Comment by rtibbles** [comment]
Oh, just that Tastypie URLs don't work with this plugin - so we still have to manually render them in a Django Template.

**Comment by MCGallaspy** [comment]
Then I feel like I'd rather just not use the plugin, for consistency.

**Comment by rtibbles** [comment]
I would rather have something that was inconsistently useful, rather than consistently terrible. Will see if I can strong arm TastyPie any further though.

**Comment by MCGallaspy** [comment]
It's probably not worth the effort to get TastyPie to play nicely... just a matter of opinion at this point, but I'm willing to defer to you if you think the usefulness outweighs the inconsistency.

**Comment by MCGallaspy** [comment]
I just want to search the codebase for the variables you removed, then I'll be happy to merge this.

**Comment by MCGallaspy** [comment]
Seems like there are some nontrivial errors here. Among others:
```
0 static files copied, 2399 unmodified.
TypeError: argument of type 'module' is not iterable
The command "bin/kalite start --traceback -v 2" exited with 1.
0.18s$ bin/kalite status
Failed to start (check logs) (6)
The command "bin/kalite status" exited with 6.
0.19s$ bin/kalite stop --traceback -v 2
Already stopped. Status was: Failed to start (check logs)
The command "bin/kalite stop --traceback -v 2" exited with 255.
0.24s$ python python-packages/fle_utils/tests.py
```

**Comment by MCGallaspy** [comment]
Still want to merge this @rtibbles?

**Comment by rtibbles** [comment]
Would like to. Will resolve merge conflict.

**Comment by rtibbles** [comment]
Yep. Merge conflict was in requirements.txt. Weak.

**Comment by rtibbles** [comment]
Hopefully tests should be fixed now.

**Comment by MCGallaspy** [comment]
The TransactionManagementError saddens me, but otherwise I think this is ready.

**Pull request merged**
