### PR TITLE
Add clear message functon at the top of the video error message.

### LINKED ISSUE #3122: Language pack error message should not appear at video tab.
Branch: `Develop`
Expected behavior: Language pack error message should not appear when video tab is active.
Steps to reproduce:
 1. make sure the distributed is not connected to central server. 
 2.  log in as admin.
 3. navigate to video and language tab.
 
ka-lite-a

### PR DESCRIPTION
**Pull request by amodia**
Hi @MCGallaspy this fixed #3122 

ka-lite-a

### CODE REVIEW

**Comment by MCGallaspy** [comment]
This isn't a backbone app? :(

**Comment by MCGallaspy** [comment]
I don't think this has the intended behavior... the language packs error message will only disappear when the video packs message error appears. I think a better solution would just be to clear messages after a navigation event, otherwise when navigating back to videos from the language page, the language pack error message will hang around for a few seconds until the video error message appears. Does that make sense?

**Comment by amodia** [comment]
The current behavior is when the video message error appears the languages pack error is not disappear. 

screen shot 2015-02-23 at 4 08 16 pm

**Comment by MCGallaspy** [comment]
Right, so if we could just call `clear_messages` to dismiss outstanding messages when the page loads... kind of like what happens with the Backbone app for  `/learn/`, except different since this isn't Backbone.

**Comment by amodia** [comment]
Ah ok i need to find how this languages pack error message execute.

**Comment by amodia** [comment]
Hi @MCGallaspy i just remove `update_language.js` at update videos html to prevent language error message execute.

**Comment by rtibbles** [comment]
This is the right fix. No reason I can think of for update_languages.js to be in the video updating page.

**Pull request merged**
