### PR TITLE
Docs fixes for pdf

### PR DESCRIPTION
**Pull request by MCGallaspy**
Had to make some changes to make built pdfs look ok.

To build the pdf:
1. Make sure you have `texlive` and some extra dependencies (see [this note](http://sphinx-doc.org/builders.html#sphinx.builders.latex.LaTeXBuilder)).
2. In the sphinx-docs directory run the command `make latexpdf`.
3. Find the pdf in _build/latex directory.

Also, be careful about using non-ASCII characters in the docs, otherwise you will make the latex spirits very sad. See this [thread](http://tex.stackexchange.com/questions/4268/inputenc-error-unicode-char-u8-error-while-trying-to-write-a-degree-symbol).

### CODE REVIEW

**Comment by aronasorman** [comment]
FYI `sphinx' had to download something from the internet:
```
loading intersphinx inventory from http://docs.python.org/objects.inv...
```

So this can't run on a completely offline setting.

**Comment by aronasorman** [comment]
I get this error:
```
updating environment: 0 added, 0 changed, 0 removed
WebDriverException: Message: 'The browser appears to have exited before we could connect. The output was: None' 
looking for now-outdated files... none found
processing KALite.tex... index installguide/install_main installguide/install_windows installguide/install_mac installguide/install_linux installguide/install_rasp_pi installguide/release_notes usermanual/userman_main usermanual/userman_admin usermanual/userman_coach usermanual/userman_learner faq developer_docs/contributing developer_docs/documentation developer_docs/index developer_docs/front_end_code developer_docs/javascript_testing developer_docs/behave_testing 
resolving references...
writing... done
copying images... .screenshot_dump/d67a0dbb-0a4a-48d2-84b3-eb86ccf70dc2.png
Exception occurred:
  File "/usr/lib/python2.6/shutil.py", line 50, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/aron/src/github.com/aronasorman/ka-lite/sphinx-docs/.screenshot_dump/d67a0dbb-0a4a-48d2-84b3-eb86ccf70dc2.png'
The full traceback has been saved in /tmp/sphinx-err-XdNBAf.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [latexpdf] Error 1
```

**Comment by aronasorman** [comment]
Looks like it's looking for `.screenshot_dump/d67a0dbb-0a4a-48d2-84b3-eb86ccf70dc2.png'`.

**Comment by MCGallaspy** [comment]
> So this can't run on a completely offline setting.

That was never an expectation for building the docs.

**Comment by MCGallaspy** [comment]
@aronasorman you're probably getting the error because you're not building the docs in headless mode.

**Comment by aronasorman** [comment]
Getting this error when running `SPHINX_SS_USE_PVD=true make html SPHINXOPTS="-E"`:

```

[7] [8]
Chapter 2.
[9] <acceptconnections.png, id=156, 420.06938pt x 177.66376pt>
<use acceptconnections.png> <use acceptconnections.png>
!pdfTeX error: pdflatex (file ./a4c66ec2-e07f-44cf-a2f5-8612038409df.png): read
ing image file failed
 ==> Fatal error occurred, no output PDF file produced!
make[1]: *** [KALite.pdf] Error 1
make[1]: Leaving directory `/home/aron/src/github.com/aronasorman/ka-lite/sphinx-docs/_build/latex'
make: *** [latexpdf] Error 2
```

**Comment by aronasorman** [comment]
Does this require a running Firefox? Maybe we need to merge #3518 first.

**Comment by aronasorman** [comment]
Found a UI issue (not wrapping). But that's for another issue.

**Pull request merged**
