### PR TITLE
overrided the  search icon size properly

### PR DESCRIPTION
**Pull request by mascot6699**
This request is to correct the issue written below
UI Issue - Improper overriding of search bar #2821

### CODE REVIEW

**Comment by jamalex** [comment]
Cool, thanks, @mascot6699! Do you know whether we need to have that #search-button style in the CSS at all? Any sense of what is different about the control panel page vs other pages that requires it?

**Comment by aronasorman** [comment]
Could you post screenshots too @mascot6699?

**Comment by mascot6699** [comment]
screenshot from 2015-01-03 09 07 34

@aronasorman the screenshot

**Comment by mascot6699** [comment]
@jamalex You are correct the overriding is not required at all remove it completely renders the same output as it does after the correction I made.

Also "input#search" has been overridden like this 
        input#search {
            font: -webkit-small-control;
            margin: 0em;
        }
for font as best practices but that makes the text overflow/cut from the viewport.
Two solutions exists for this either remove this part of css too or extend the search bars width more but that will make the control panel page search bar longer than others

**Comment by jamalex** [comment]
@mascot6699 Great, thanks for trying that! Yes, it seems like both CSS rules could just be removed, unless there's another `input#search` somewhere in the control panel pages.

**Comment by jamalex** [comment]
I think what happened is that we used to import a different version of Bootstrap on the control panel pages, for compatibility with our central, online server (which shares those templates), and these overrides were needed at that time. Now, those pages should all be using Bootstrap 3.

**Comment by mascot6699** [comment]
@jamalex So what should I do now? Close this pull request and make changes in another branch and again open up a new one or there is some other method to follow. It may sound silly but I really don't know how to contribute to others project so bare with me.

**Comment by jamalex** [comment]
Hey @mascot6699! Sorry, I should have given more instructions.

If you make the changes (removing those CSS rules completely, it looks like), commit it, and push that to your adjusting_searchbar branch, it will automatically update this pull request, and then we can merge it.

Thanks again!

**Comment by mascot6699** [comment]
Please review it. I have checked it from my end.

**Comment by jamalex** [comment]
Great, looks good -- thanks again for the contribution!

**Pull request merged**
