### PR TITLE
Delete the query tests.

### PR DESCRIPTION
**Pull request by aronasorman**
Will be moved soon to the benchmark suite.

Many a man-hour has been meted out to this monster.

### CODE REVIEW

**Comment by benjaoming** [comment]
deletion = improvement!

**Comment by rtibbles** [comment]
Are we reviewing our own PRs now, eh?

**Comment by benjaoming** [comment]
Great PR @aronasorman !

**Comment by MCGallaspy** [comment]
Is the FuzzyInt stuff used anywhere else?

**Comment by benjaoming** [comment]
Nope, good spot

```
✗ ack-grep --python FuzzyInt kalite
kalite/testing/utils.py
1:class FuzzyInt(int):
6:        self.assertNumQueries(FuzzyInt(1, 2)):
10:        obj = super(FuzzyInt, cls).__new__(cls, highest)
31:        val = super(FuzzyInt, self).__add__(x)
```

**Pull request merged**
