### PR TITLE
Unbundle all the things

### PR DESCRIPTION
**Pull request by rtibbles**
Attempts to complete the migration to browserify by unbundling the static-libraries folder and moving things to be managed by npm.

Summary of changes:
* Unbundle all possible javascript libraries.
* Make runserver run the build process too.
* Use node-lessify to build less and css assets.
* Removes unnecessary Perseus files.

Ready to go.

### CODE REVIEW

**Comment by aronasorman** [comment]
Can we unbundle the `kalite` app as well? Less code to maintain. :hamster:

**Comment by rtibbles** [comment]
I'll give it a go, but I don't hold out much hope.

**Comment by aronasorman** [comment]
Merge conflict.

**Comment by rtibbles** [comment]
Will fix test errors.

**Pull request merged**
