### PR TITLE
add missing entry for generated manpages

### PR DESCRIPTION
**Pull request by benjaoming**

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Context? What if the man pages don't exist because e.g. I ran the makefile on windows?

**Comment by benjaoming** [comment]
We *could* also host the manpage in the repo so it doesn't need to be generated during `make dist` -- that seems more reasonable actually. Especially because the auto-generated manpage could do with a bit of manual adjustments anyways.

**Comment by MCGallaspy** [comment]
Sounds fine to me.

**Comment by benjaoming** [comment]
Cool, I'll do this for 0.16. For now, it means adding the .gz file and then we should also have a Makefile entry for building the manpages, perhaps together with `make docs` target, perhaps not.. will figure that out.

**Comment by benjaoming** [comment]
Retarget for 0.16

**Pull request closed without merging**
