### PR TITLE
Refactor behave_helper functions; add & amend test cases; fix update_item function

### PR DESCRIPTION
**Pull request by MCGallaspy**
Starts to work on #4716. See commit message for rationale. But still, the troubled test passes even though there's clearly an alert bubble there. So something else is up.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Hm, I think `update_item` is having concurrency issues.

**Comment by rtibbles** [comment]
Trying to write to the database while it is being read?

**Comment by MCGallaspy** [comment]
Turns out it wasn't about concurrency at all.

**Comment by MCGallaspy** [comment]
Regarding the latest test failure: seems like for some amount of time topic_tools tests were not being run at all. From a previous test run:
```
WARNING:kalite:App with label topic_tools is missing a models.py module.
```

**Comment by MCGallaspy** [comment]
See https://github.com/learningequality/ka-lite/pull/4551/files#r46506825

**Comment by rtibbles** [comment]
Yeah these tests need to be fixed up.

I will edit them and make a PR to your branch here.

**Comment by rtibbles** [comment]
Tada: https://github.com/MCGallaspy/ka-lite/pull/25

**Pull request merged**
