### PR TITLE
Translation on Progress Report

### PR DESCRIPTION
**Pull request by 66eli77**
## Summary

pass in the language keyward argument when retrieve content nodes on progress report so that language pack setting will take effect

## TODO

If not all TODOs are marked, this PR is considered WIP (work in progress)

- [ ] Have **tests** been written for the new code? If you're fixing a bug, write a regression test (or have a really good reason for not writing one... and I mean **really** good!)
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst

## Issues addressed

#4980

### CODE REVIEW

**Comment by rtibbles** [comment]
This is the right fix. Test?

I would suggest doing an API only test, with the request language set - and then use mock.patch to check that language argument gets passed into the `get_content_parents` and `get_topic_nodes` functions.

**Comment by 66eli77** [comment]
do you aware that mock.patch not working on two or more imports deep calls @rtibbles

**Comment by rtibbles** [comment]
Really? Seems to work fine for me - e.g. https://github.com/rtibbles/kolibri/blob/frontend_asset_loading/kolibri/utils/test/test_webpack_utils.py#L100

**Comment by 66eli77** [comment]
for some reason, this return false
```
@patch('kalite.topic_tools.content_models.get_content_parents')
    def test_language_setting(self, get_content_parents):
        base_url = self.reverse('api_dispatch_list', kwargs={'resource_name': 'playlist_progress'})
        url = base_url + '?' + urllib.urlencode({'user_id': self.student.id, '_': '1458605610477'})
        resp = self.client.get(url)
       return get_content_parents.called
```
but this return True
```
@patch('kalite.coachreports.models.PlaylistProgress.user_progress')
def test_language_setting(self, user_progress):
        base_url = self.reverse('api_dispatch_list', kwargs={'resource_name': 'playlist_progress'})
        url = base_url + '?' + urllib.urlencode({'user_id': self.student.id, '_': '1458605610477'})
        resp = self.client.get(url)
       return user_progress.called
```

do you have any insights about this?

**Comment by 66eli77** [comment]
nvm, I figured it out, it should be @patch('kalite.coachreports.models.get_content_parents')

**Comment by rtibbles** [comment]
Merging as is in the interests of time. Pity we couldn't properly mock the language in the request though!

**Pull request merged**
