### PR TITLE
Support for Coverage metrics and coveralls reports

### PR DESCRIPTION
**Pull request by benjaoming**
Taking over #4376

### CODE REVIEW

**Comment by rtibbles** [comment]
Doesn't seem to be running tests properly :/

**Comment by benjaoming** [comment]
Re-running them... it worked in the former PR, no reason why it shouldn't work now.

**Comment by rtibbles** [comment]
Must be that Friday afternoon feeling!

**Comment by benjaoming** [comment]
Yes, Circle CI is tired after a long week.

**Comment by rtibbles** [comment]
My assumption here is that it is interacting oddly with SauceConnect? That's the difference I see here between this test run and the previous one.

**Comment by benjaoming** [comment]
Great, now what!? :(

**Comment by rtibbles** [comment]
@benjaoming I will run your PR locally later in the week to debug.

**Comment by benjaoming** [comment]
@rtibbles I've run the coverage commands locally, it's working fine on Coverage 3.7.1 -- I don't know if the problem is that output to stdout/stderr from the test commands is somehow not proxied by Coverage or disappears somewhere else.

**Comment by benjaoming** [comment]
*) But locally, Coverage proxies test output fine, and it used to do so in the previous PR, too.

This sadly made the 21 day no-merge of #4376 even more costly. We should really merge things faster.

**Comment by rtibbles** [comment]
Did you run it locally using SauceConnect? That seems to be the relevant difference, so it would be interesting to debug that.

**Comment by benjaoming** [comment]
@rtibbles no but as you can see from the commits above, I tried removing sauceconnect from circle.yml without results :(

**Comment by benjaoming** [comment]
Seeing that sauceconnect is also a part of `testing.base_environment`, there's still a bit of disabling work to do before verifying if SC is the reason.

**Comment by benjaoming** [comment]
Should perhaps try this with Codecov.io

**Pull request closed without merging**
