### PR TITLE
Re-AMDifies Khan Exercises utils files that had not been properly encoded

### LINKED ISSUE #5036: Where is my orange dot???
## Summary

`/learn/khan/math/arithmetic/multiplication-division/multiplication_fun/number_line/` exercise is missing the essential orange dot. Compare with screenshots from @rtibbles  #4981.
Woff2 font problem?

## Branch or installer method

Upgrade scenario on OSX Yosemite from 0.15 to 0.16 with .pkg build 99.

## Traceback or relevant snippet from server.log

```
Usual WOFF2 font missing errors in the console
```

## How to reproduce

1. Login as Learner.
2. Navigate to /learn/khan/math/arithmetic/multiplication-division/multiplication_fun/number_line/
3. Observe.

#### On Firefox:
where-is-my-orange-dot-ff

#### On Chrome
where-is-my-orange-dot-chrome

## Real-life consequences

Exercise cannot be completed.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Reruns deAMDify on the Khan Exercise utils file. Some of these seemed to be malformed, or possibly even empty.

They are now properly deAMDified and have been confirmed to have content.

## Reviewer guidance

Pull and manually test problematic exercises.

## Issues addressed

Fixes #5036 and #5099 - and many other exercises that were broken.

## Documentation

*If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)*

## Screenshots (if appropriate)

image

image

image

### CODE REVIEW

**Comment by benjaoming** [comment]
Will do a manual test to verify this and merge once confirmed that existing issues are fixed.

Once merged, will release as 0.16.4.

**Comment by jamalex** [comment]
!!!!!

**Comment by jamalex** [comment]
> Once merged, will release as 0.16.4.

The release to end all releases.

**Comment by benjaoming** [comment]
It solves parts of the issues, but it seems now that some piece of the URLs for loading data is missing:

```
Data load failed: "http:/content/assessment/khan/e98/e98730da75ea202f048b860cb802424c71818cf1-data.json" undefined bundle_exercise.js:748:513
```

**Comment by benjaoming** [comment]
Actually from the above example, `/content/assessment/khan/e98/e98730da75ea202f048b860cb802424c71818cf1-data.json` does not exist in any case.

**Comment by benjaoming** [comment]
Similar issues in many other exercises.

    /learn/khan/math/geometry/quadrilaterals-and-polygons/quadrilaterals/quadrilateral_angles/

JS traceback:

    Data load failed: "http:/content/assessment/khan/b3c/b3cc297e950300ff2a0b83cd5bacdfda35ee3472-data.json" undefined bundle_exercise.js:748:513

**Comment by rtibbles** [comment]
Hrm - curiously enough, I *do* have these files in my content folder, and still get the same error.

**Comment by rtibbles** [comment]
Oh, no, I have the one you note above, but many others are missing.

**Comment by rtibbles** [comment]
@benjaoming I redownloaded the English content pack, and it cleared up this issue for the exercise you identified. Can you try the same and double check the other ones you found problematic?

**Comment by benjaoming** [comment]
@rtibbles what concerns me is this:

    http:/content/assessment/khan/
          ^ where is the host name?

There seems to be both a lack of error handling, but also an unintended behavior. I have now tested with the "latest" assessment items pack, but it's the same result, and I wouldn't expect otherwise. The file exists, but the request is mal-formatted.

**Comment by rtibbles** [comment]
Does the item fail to render as a result?

**Comment by benjaoming** [comment]
screenshot from 2016-04-28 23 14 53

**Comment by rtibbles** [comment]
All of the questions rendered fine for me after updating the content pack,
I am unable to replicate this.

The fetching is internal to Perseus, so we cannot catch the error in
question.

**Comment by benjaoming** [comment]
BINGO! I got it working by using a content pack rather than the legacy assessment items whose contents must have drifted.

I'll generate new assessment items manually tomorrow unless someone else beats me to it. I will release after and draft a release announcement to share.

**Comment by benjaoming** [comment]
I should have approached this differently:

1. FIrstly, I ran a diff on everything in the content pack and legacy assessment item zip. They are the same, data is fine.
1. Then, I found out that the unpack_assessment_zip command puts the assessment items in the wrong location.

Should be fixable quite easily... doing that now...

**Comment by benjaoming** [comment]
Error was that the original assessment_zip used to contain a file `channel.name` and the legacy version doesn't. Fixing it in the codebase.

**Pull request merged**
