### PR TITLE
Test for issue 2990

### PR DESCRIPTION
**Pull request by MCGallaspy**
A test for issue #2990 (and the duplicate #2997). This PR could complement #3010, or replace it as it's been suggested to abandon that branch...?

### CODE REVIEW

**Comment by MCGallaspy** [comment]
I renamed this PR because the name was less than good.

**Comment by aronasorman** [comment]
Merge conflict @MCGallaspy

**Comment by MCGallaspy** [comment]
Okay, since I haven't heard anything from the folks over at #3010, I'll close that one. And then I think @jtamiace is working on this issue? So once she makes a PR I'll make a PR to merge this one into that (so it'll have a test).

**Comment by jtamiace** [comment]
Yup, will be working on this over the weekend.

**Comment by MCGallaspy** [comment]
Weird that this is a failure... both 2.6 and 2.7 tests pass.

**Comment by MCGallaspy** [comment]
Tested it out manually, looks fine to me.

**Pull request merged**
