### PR TITLE
Fixes for Exercises

### LINKED ISSUE #2994: Some assessment items missing, no graceful failure.
Branch: develop
Expected Behavior: A perseus exercise should always render a proper assessment item
Current Behavior: Some assessment items appear to be missing still, and our wrapper does not allow for graceful failure when this does happen
Steps to reproduce: Navigate to exercise 'One more, one less'. Answer questions correctly until 404 error appears.
Screenshot(s):

image

### LINKED ISSUE #2996: "Acceptable formats" is no longer in bubble format and no longer accepts interaction
Expected: A nice "Acceptable formats" bubble in the exercise answer area, which displays answer input instructions when hovered/tapped.

Observed:
Ugly plaintext that accepts to interaction:
image

### LINKED ISSUE #3005: No points are being earned for exercises
Expected: Points earned for exercises

Observed: No points earned for exercises

Steps to replicate: Do exercise. No points.

### PR DESCRIPTION
**Pull request by rtibbles**
Fixes #2994, resolves #2996, and should close #3005

Summary of changes:
* Cleans up residual assessmentitems.json and properly adds it to gitignore.
* Adds availability flagging for Khan Exercises (by checking template files on disk)
* Adds availability flagging for Perseus Exercises (by checking existence of assessmentitems in cache)
* Only returns all_assessment_items for Perseus Exercises for ones that exist
* Loads exercise cache on startup
* Fixes Exercise and Content Resource API endpoints to return the right properties (some were missing)
* Reduces the amount of cruft in Exercise Resource class by just importing all properties.
* Try to get another assessmentitem if the requested one 404s.
* Warn users and don't try to render an exercise if the exercise is unavailable or is a perseus exercise and has no assessment items.
* Style acceptable formats tooltips to prompt users
* Focus highlights input boxes

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Looks good, can we write regression tests for this?

**Comment by MCGallaspy** [comment]
Okay, writing a test for #2994 will be hard and error-prone without some sort of testing framework that allows one to easily mock the API, so I'm going to relax my insistence on writing a test for that one, pending outside approval. But I'll write tests for these other two issues.

**Comment by MCGallaspy** [comment]
Okay, after some discussion with @rtibbles we decided to just manually test this for now and add another check next to "Need a better testing framework". The main issue is the availability of testing fixtures, which is beyond the scope of this PR.

**Comment by MCGallaspy** [comment]
Checked it out, looks ok, just a minor styling suggestion. Check out the tooltips in, for example, `/learn/khan/math/pre-algebra/factors-multiples/divisibility_and_factors/divisibility_intuition/`. One of the elements overflows the right margin of the `qtip` element a bit.

**Comment by MCGallaspy** [comment]
Made a PR against your fork.

**Comment by rtibbles** [comment]
Let's hope this sorts out the testing hell. No idea why Python 2.6 is continually erroring out.

**Pull request merged**
