### PR TITLE
Inconsistent behavior of dropdown item selection on coach report pages f...

### PR DESCRIPTION
**Pull request by jesumer**
Hi @aronasorman , 

This is for issue #2987.
I've added a button that refreshing the browser according to to the selected item. Heres the screenshot
screen shot 2015-02-11 at 2 57 35 pm

/review: @arceduardvincent

### CODE REVIEW

**Comment by arceduardvincent** [comment]
Hi @jesumer .
as I inspect the the behaviour that @jamalex talk about, your fix comply the recommendation said.
however could you rename the button id `tabularGo`.

I think it is beneficial that we use generic terms like `display-topic-report`something like that. hence our objective is to display the report under topic selected.

**Comment by MCGallaspy** [comment]
This is problematic, in that the order in which the topic and report dropdowns are selected can cause the `href` value of the `#tabularGo` button to be invalid. For example, selecting a topic and then a report type will result in an invalid URL. Check out how it's handled in handlebars in `ka-lite/kalite/coachreports/static/js/coachreports/base.js` in the `NavigationContainerView` and write a new view there that handles it similarly. Then create a new handlebars template and include it in `tabular_view.html` by attaching your view to an element in there. You can check out how it's done in `ka-lite/kalite/coachreports/templates/coachreports/base.html` for an example.

I also agree @arceduardvincent about the id name.

**Comment by jesumer** [comment]
Hi @MCGallaspy 

My findings was you are right about the invalid url it will resetting to default after selecting first the topic before the report  type. Now I was trying your suggestion to fix this and trying the best way of fixing this. I'm currently working on this.

**Comment by jesumer** [comment]
HI @MCGallaspy ,

My fix on this was as is and changed the id of the button except someone will help and can make your suggestion because it will take me sometime to do that. I need to move into other priority issues.

**Comment by jesumer** [comment]
There's no error here and just a url reset if the user selects the topics first like:
screen shot 2015-02-13 at 11 02 31 am
the user will redirect to this page

screen shot 2015-02-13 at 10 59 33 am
 So if the report type will be the last to select the url will reset as of what is the default url of the report type.

**Comment by arceduardvincent** [comment]
Hi @MCGallaspy 
I would like to work on this issue.

**Comment by MCGallaspy** [comment]
@jesumer you're right, my suggested changes are more involved than I thought. Probably best to just make some quick changes to the template js in this case. Also, did you forget to push some changes that you made here? Seems like something is missing.

**Comment by MCGallaspy** [comment]
If [this](https://github.com/mrpau/ka-lite/pull/3) is merged, it'll automatically be reflected here.

**Comment by MCGallaspy** [comment]
And we can get this PR rolling.

**Pull request closed without merging**
