### PR TITLE
Run tests under coverage, add badge

### PR DESCRIPTION
**Pull request by MCGallaspy**
Replaces #3015.

### CODE REVIEW

**Comment by aronasorman** [comment]
yey

**Comment by aronasorman** [comment]
Does coverage error out at some point due to insufficient test coverage?

**Comment by aronasorman** [comment]
oh, apparently not.

**Comment by aronasorman** [comment]
So it seems like it dumps it to some file, then uploads it to coveralls.io.

Here is the run for the last commit: https://coveralls.io/jobs/4864186

68% coverage is higher than I expected. Although based on the stats, it only covers the actual `bin/kalite` file, and not all of our source files.

**Comment by aronasorman** [comment]
So we may need to find a way to make `coveralls` cover all our source files. Maybe drop straight to `kalitectl.py`?

**Comment by rtibbles** [comment]
Or we could add a coverage config to tell it where the source files we are testing are located?
https://pypi.python.org/pypi/coveralls/1.0a2

**Comment by MCGallaspy** [comment]
Also, it's not gathering coverage data about any js, since we're not running any js tests. Just python. Could artificially inflate the coverage %.

**Comment by benjaoming** [comment]
According to my stats, it's sitting at 23%... run `coverage report` from command line to get the output.

**Comment by benjaoming** [comment]
@MCGallaspy 

These things, I've already done... both added the badge and the --source option.. not sure why you're replacing the PR? Is it okay that I take back this one? ;)

**Comment by MCGallaspy** [comment]
@benjaoming I wanted it to get merged. :( But it's still languishing.

**Comment by MCGallaspy** [comment]
@benjaoming feel free to take it back

**Comment by rtibbles** [comment]
I think this was fixed in a @benjaoming PR eventually. So this is stale.

**Pull request closed without merging**
