### PR TITLE
Video download fixes

### LINKED ISSUE #4933: `Scan content folder for videos` not working
## Summary

For videos in English it does seem to register those downloaded in prior version, but not so for other languages. I have 3 in French and 2 in Danish downloaded in 0.14 installation, but `Scan content folder for videos` seems to register only those in English (`Annotation complete for language: en, channel: khan`). 

No errors in the console, and none that I can see in the server.log.

## Branch or installer method

Upgrade scenario form 0.14.2 to 0.16 (build 66) on OSX Yosemite.

## Traceback or relevant snippet from server.log

```
[INFO] [2016-02-28 05:51:19,181] django.request: HTTP Request /api/videos/topic_tree - Response: 200
[INFO] [2016-02-28 05:51:19,398] cherrypy.access.4348806864: 127.0.0.1 - - [28/Feb/2016:05:51:19] "GET /static/images/distributed/circle-partial.png HTTP/1.1" 304 - "http://127.0.0.1:8008/update/videos/?lang=fr" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"
[INFO] [2016-02-28 05:51:19,399] cherrypy.access.4348806864: 127.0.0.1 - - [28/Feb/2016:05:51:19] "GET /static/images/distributed/circle-empty.png HTTP/1.1" 304 - "http://127.0.0.1:8008/update/videos/?lang=fr" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"
[INFO] [2016-02-28 05:51:19,417] cherrypy.access.4348806864: 127.0.0.1 - - [28/Feb/2016:05:51:19] "GET /static/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 404 1554 "http://127.0.0.1:8008/update/videos/?lang=fr" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"
[INFO] [2016-02-28 05:51:20,640] django.request: HTTP Request /securesync/api/info - Response: 200
[INFO] [2016-02-28 05:51:24,481] django.request: HTTP Request /api/videos/topic_tree - Response: 200
[INFO] [2016-02-28 05:51:27,179] django.request: HTTP Request /api/videos/topic_tree - Response: 200
[INFO] [2016-02-28 05:51:28,759] django.request: HTTP Request /api/videos/topic_tree - Response: 200
[INFO] [2016-02-28 05:51:28,833] cherrypy.access.4348806864: 127.0.0.1 - - [28/Feb/2016:05:51:28] "GET /static/images/distributed/circle-complete.png HTTP/1.1" 304 - "http://127.0.0.1:8008/update/videos/?lang=fr" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:44.0) Gecko/20100101 Firefox/44.0"
[INFO] [2016-02-28 05:51:36,455] django.request: HTTP Request /api/videos/scan - Response: 200
[INFO] [2016-02-28 05:51:40,790] django.request: HTTP Request /api/videos/topic_tree - Response: 200
[INFO] [2016-02-28 05:51:57,716] django.request: HTTP Request /api/cherrypy/getpid - Response: 200
[INFO] [2016-02-28 05:52:57,590] django.request: HTTP Request /api/cherrypy/getpid - Response: 200
[INFO] [2016-02-28 05:54:07,623] django.request: HTTP Request /api/cherrypy/getpid - Response: 200
[INFO] [2016-02-28 05:54:57,452] django.request: HTTP Request /api/cherrypy/getpid - Response: 200
```

## How to reproduce

1. Install 0.14.2 and download some videos in other languages
1. Upgrade to 0.16
1. `Scan content folder for videos`

## Screenshots

scan_yosemite_10_10_5

### LINKED ISSUE #4937: Videos downloaded in a non-english language pack aren't showing up in the topic tree.
## Summary

When I download a video in a non-english lang pack, it's not showing up in the topic tree.

## Branch or installer method

*Please specify if you are using the current `develop` branch or which installation source you were using when the issue occurred.*

0.16.x

## How to reproduce

1. Download a language pack, activate said language
2. Download a video through the video download interface
3. Scroll through topic tree, trying to find the said video in vain

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Properly sets the language codes on the client side, and then properly parses them on the server side in order to ensure that video download, video deletion, and video scanning all actually do this for multiple languages, rather than just English.

## TODO

- [x] Have **tests** been written for the new code?

## Issues addressed

Fixes #4937, fixes #4933, fixes a behaviour noted in #4929 by @radinamatic.

### CODE REVIEW

**Comment by rtibbles** [comment]
@aronasorman Just writing a regression test for this, will let you know when it's done!

**Comment by rtibbles** [comment]
@aronasorman Regression tests added to ensure we are always properly parsing the language and passing it onto the content model functions.

Enjoy the mocking!

**Comment by aronasorman** [comment]
Checked out said branch, unfortunately the videos i try to download are still not showing up in the topic tree. On the progress bar, the video's title is also in English, which might mean that language still isn't getting propagated properly.

**Comment by rtibbles** [comment]
Showing up in Spanish for me.

**Comment by aronasorman** [comment]
Confirmed working. But it introduced another bug wherein the page needs to be refreshed before the availability is reflected through that green half-circular icon.

**Comment by rtibbles** [comment]
Think that bug may have already been there - the dynamic in page updating is not great. Would rather just collapse the topic tree and refresh from the database.

**Comment by aronasorman** [comment]
@rtibbles you mean refetch the entire topic tree? That sounds good, as long as it isn't too slow.

**Comment by rtibbles** [comment]
Each level is lazy loaded, so it would actually just be reloading the topic tree's first level. I am looking to see if there is an efficient way in fancytree to just reload the ones that were selected for download.

**Comment by rtibbles** [comment]
Actually, the problem here, @aronasorman was that it just wasn't working for non-English languages.

**Comment by rtibbles** [comment]
@aronasorman This should be good to merge, unless you have any concerns.

**Pull request merged**
