### PR TITLE
0.17.5b1

### PR DESCRIPTION
**Pull request by benjaoming**
**WARNING!** Merging this, merges and closes all PRs contained in this PR, and they may have a separate review process and amendments following. **So don't merge this PR!!** :)

New release, manually brewing the distributions:
- [x] [ka-lite on pypi](https://pypi.python.org/pypi/ka-lite)
- [x] [ka-lite-static on pypi](https://pypi.python.org/pypi/ka-lite-static)
- [x] [ka-lite on Launchpad PPA](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite)
- [ ] OSX installer
- [ ] Windows installer 

## Known issues

See release notes: http://ka-lite.readthedocs.io/en/develop/installguide/release_notes.html

## Included PRs

Current `0.17.x` branch

## Installer links
- Debian/Ubuntu:
   - [ka-lite-bundle](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-bundle_0.17.5~b1-0ubuntu1_all.deb)
   - [ka-lite-raspberry-pi](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-raspberry-pi_0.17.5~b1-0ubuntu1_all.deb)
   - [ka-lite](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite_0.17.5~b1-0ubuntu1_all.deb)
- [Windows]() TODO
- [Mac]() TODO

### PyPi

```
pip install ka-lite --pre
```

or

```
pip install ka-lite-static --pre  # bundled dependencies
```

### CODE REVIEW

**Comment by benjaoming** [comment]
@holta I have released this on PyPi, are you able to verify with `pip install --pre ka-lite[-static]` ?

**Comment by holta** [comment]
`pip install --pre ka-lite-static` for 0.17.5b1 has effectively been verified as documented @ https://github.com/iiab/iiab/issues/632#issuecomment-403586926

**Comment by benjaoming** [comment]
@holta additionally, the .deb installers are uploaded to the PPA (see PR description)

**Comment by holta** [comment]
> @holta additionally, the .deb installers are built in the PPA (see PR description)

Will 0.17.5b1 appear at https://launchpad.net/%7Elearningequality/+archive/ubuntu/ka-lite ?

(Just curious... 0.17.5 in coming days/weeks is likely more important.)

**Comment by benjaoming** [comment]
Just need to do a more proper test, I'll bump it to a final release and put it in the stable PPA... probably tomorrow :)

**Pull request closed without merging**
