### PR TITLE
Fix for sometimes-failing test

### PR DESCRIPTION
**Pull request by benjaoming**
I don't know if this entirely fixes the problem, but at least if the document isn't fully loaded and the forementioned IndexError occurs, we will retry for 10 seconds because of `WebDriverWait`.

#4736

### CODE REVIEW

**Comment by benjaoming** [comment]
Garh, now it results in this:

```

  Scenario: User alters a star rating       # kalite/distributed/features/content_rating.feature:12
    Given I have filled out a feedback form # kalite/distributed/features/steps/content_rating.py:115
    Given I have filled out a feedback form # kalite/distributed/features/steps/content_rating.py:115 7.830s
    When I alter a star rating              # kalite/distributed/features/steps/content_rating.py:43
    When I alter a star rating              # kalite/distributed/features/steps/content_rating.py:43 2.498s
    Then the altered rating is displayed    # kalite/distributed/features/steps/content_rating.py:52
    Then the altered rating is displayed    # kalite/distributed/features/steps/content_rating.py:52 0.984s
      Assertion Failed: Star rating has value 3, which should be different from the old value 3
```

**Comment by benjaoming** [comment]
And now after a rebuild (the above was also a random thing), we are getting:

```
.Feature: Content Rating # kalite/distributed/features/content_rating.feature:1
  Tests for the content rating form/widget, which should appear on content pages (video, exercises, etc)
  @as_learner
  Scenario: User rates an unrated item  # kalite/distributed/features/content_rating.feature:5
    Given I open some available content # kalite/distributed/features/steps/learn_content.py:19
    Given I open some available content # kalite/distributed/features/steps/learn_content.py:19 1.372s
    Then I see a feedback form          # kalite/distributed/features/steps/content_rating.py:38
    Then I see a feedback form          # kalite/distributed/features/steps/content_rating.py:38 0.933s
    When I fill out the form            # kalite/distributed/features/steps/content_rating.py:108
    When I fill out the form            # kalite/distributed/features/steps/content_rating.py:108 11.978s
      Traceback (most recent call last):
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 110, in impl
          enter_star_ratings(context)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 161, in enter_star_ratings
          rate_id(context, id_)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 182, in rate_id
          WebDriverWait(context.browser, 10).until(rate_element)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 75, in until
          raise TimeoutException(message, screen, stacktrace)
      TimeoutException: Message:
```

**Comment by MCGallaspy** [comment]
I think what's needed is a wait for the all the ajax stuff to finish.

**Comment by MCGallaspy** [comment]
@benjaoming be sure to paste in the link to the job on sauce in the future, so we can see a screencast. Helps to debug this kind of stuff.

**Comment by benjaoming** [comment]
@MCGallaspy can't do that because rebuilding removes the old output? That's why I copy paste it....

**Comment by MCGallaspy** [comment]
I mean when you copy the traceback, get the link at the bottom. It should be persistent. Like this:

```text
      Traceback (most recent call last):
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 110, in impl
          enter_star_ratings(context)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 161, in enter_star_ratings
          rate_id(context, id_)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 182, in rate_id
          WebDriverWait(context.browser, 10).until(rate_element)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 75, in until
          raise TimeoutException(message, screen, stacktrace)
      TimeoutException: Message:

Link to your job: https://saucelabs.com/jobs/4014f5d4089441259b8114804a428996
```

**Comment by MCGallaspy** [comment]
Your fix looks good, looking at other tests.

**Comment by benjaoming** [comment]
There's some easing effect on showing the "difficulty" rating box, which I think is responsible for the failures, but I'm not sure. Added an extra second.

**Comment by benjaoming** [comment]
*Given I have filled out a feedback form* fails in one case, works in the others. Can't recreate it locally.

```
  @as_learner
  Scenario: User alters a star rating       # kalite/distributed/features/content_rating.feature:12
    Given I have filled out a feedback form # kalite/distributed/features/steps/content_rating.py:115
    Given I have filled out a feedback form # kalite/distributed/features/steps/content_rating.py:115 4.290s
      Assertion Failed: FAILED SUB-STEP: When I fill out the form
      Substep info: Traceback (most recent call last):
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 110, in impl
          enter_star_ratings(context)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 161, in enter_star_ratings
          rate_id(context, id_)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 182, in rate_id
          WebDriverWait(context.browser, 10).until(rate_element)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 66, in until
          value = method(self._driver)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/content_rating.py", line 175, in rate_element
          rating_el = [el for el in filter(lambda x: int(x.get_attribute("data-val")) == val, els)][0]
      IndexError: list index out of range

Link to your job: https://saucelabs.com/jobs/2341f42387dd46319a7cd1cc25a4efba
```

**Comment by MCGallaspy** [comment]
I think we can address that error by catching the IndexError... somehow that fix got missed during the merge I guess?

**Comment by MCGallaspy** [comment]
I mean it `rate_element1

**Comment by benjaoming** [comment]
Nah, I just removed it... because when you catch it then `WebDriverWait(context.browser, 10).until(rate_element)` will just timeout, and I guess that if it doesn't exist that's a problem? Let me just try to re-implement it...

**Comment by benjaoming** [comment]
Wow @MCGallaspy you're like a guru :)

Gonna make a push -f...

**Comment by MCGallaspy** [comment]
> because when you catch it then WebDriverWait(context.browser, 10).until(rate_element)

If that times out either the wait time there is not long enough, or there's an actual error in the test logic (like a race condition).

> Wow @MCGallaspy you're like a guru :)

I am a mere mortal who has written many tests... ;)

**Comment by MCGallaspy** [comment]
@rtibbles you had been asking about tests on develop -- this should solve known issues.

**Pull request merged**
