### PR TITLE
fixed update language bug release blocker

### PR DESCRIPTION
**Pull request by jtamiace**

### CODE REVIEW

**Comment by jtamiace** [comment]
I guess I see the advantage of making different branches for different bugs, but this pull request fixes the following bugs:

https://github.com/learningequality/ka-lite/issues/3233#issuecomment-78624210

https://github.com/learningequality/ka-lite/issues/3229#event-255825537

**Comment by aronasorman** [comment]
Screenshots @jtamiace?

**Comment by jtamiace** [comment]
This pic accounts for both bugs:

fix-lang-and-tab-bug

**Comment by aronasorman** [comment]
Looks good to me. Will test locally once the tests pass.

**Comment by aronasorman** [comment]
screen shot 2015-03-18 at 2 43 53 pm

Can confirm fixes.

**Comment by aronasorman** [comment]
Nondeterministic test failures. Merging.

**Pull request merged**
