### PR TITLE
Availability

### LINKED ISSUE #4990: Mismatch between number of videos said will be downloaded and number then queued
## Summary

I was upgrading an installation with all the 0.15 videos to 0.16, and wanting to download just the new videos. At first, the download button claimed only 411 new videos to download, but once the download began, it showed 7000+ in the queue.

It seems to be queuing all selected videos, rather than just the ones that are new?

## Branch or installer method

 - Branch: 0.16.x

## How to reproduce

1. Run 0.16.x branch from source, with content directory already containing many videos
1. Go to video download page, and select all topics, and start download.

## Screenshots

image

image

### LINKED ISSUE #4994: English videos annotated as dubbed in other languages
## Summary

Downloaded a few English videos, but after installing a Spanish language pack, I saw that the same videos appear as already downloaded when I switched the default language to Spanish. Once a deleted 2 of them and re-downloaded, they were correct, dubbed version. The same thing repeated when I re-tested with subsequent French language pack - videos appear as downloaded, when played it is clear that it's the English version, so one needs to go back, delete and re-download to get the dubbed version.     

## Branch or installer method

Both Beta2 in Ubuntu & build 176 on Windows. 

## Traceback or relevant snippet from server.log

```
No visible error in the console and nothing of consequence in the server.log.
```

## How to reproduce

1. Download a couple of English videos.
1. Install language pack & switch the default language.
1. Check the Manange > Videos page and you'll see the same videos (test the play to confirm they are in English).
1. Delete and re-download, and you'll get the dubbed version.

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

Properly stamps availability flags, files_complete etc. on different languages, and ensures that the subtitle fallback annotation works properly.

Also filters retrieval of youtube_ids for downloading and deletion by whether there are any files to download/delete.

Finally, prevents overwriting/download of videos that already exist in the content dir.

## TODO

If not all TODOs are marked, this PR is considered WIP (work in progress)

- [ ] Have **tests** been written for the new code? If you're fixing a bug, write a regression test (or have a really good reason for not writing one... and I mean **really** good!)
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file
- [ ] Add an entry to CHANGELOG.rst

## Issues addressed

Fixes #4994, fixes #4990, and supersedes #5016.

### CODE REVIEW

**Comment by rtibbles** [comment]
Genuine test failure. Fixing.

**Comment by rtibbles** [comment]
Issue here was that we were updating every Video node on annotation, not just those that needed. As @jamalex has previously noted, this can take 45 minutes for every video node.

**Comment by MCGallaspy** [comment]
`killall --wait sc` this command timed out... odd, but otherwise the build passes.

**Comment by rtibbles** [comment]
Also this:
```
======================================================================
FAIL: test_delete_existing_video_file (kalite.updates.tests.api_tests.TestAdminApiCalls)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/ka-lite/kalite/updates/tests/api_tests.py", line 77, in test_delete_existing_video_file
    self.assertFalse(os.path.exists(self.fake_video_file), "Video file should not exist on disk.")
AssertionError: True is not false : Video file should not exist on disk.

----------------------------------------------------------------------
```
Can't replicate locally.

**Comment by rtibbles** [comment]
@MCGallaspy Tests pass!

**Pull request merged**
