### PR TITLE
Fix video player auto-resizing, and set default height, to avoid jump

### PR DESCRIPTION
**Pull request by jamalex**
Fixes https://github.com/learningequality/ka-lite/issues/4336

### CODE REVIEW

**Comment by aronasorman** [comment]
is there an issue for this?

**Comment by jamalex** [comment]
Yes.

**Comment by MCGallaspy** [comment]
Please be sure to set milestone and assignee @jamalex.

**Comment by MCGallaspy** [comment]
Okay, this seems to work fine, except that now there is a lot of whitespace below the footer on _available_ videos _if_ you're not logged in as a learner. Doesn't occur if you're logged in as a learner or viewing an unavailable video. I want to check if it exists on `0.15.x`, and if it does I'll open a separate issue.

I'm disappointed by the test failure here, but it seems to be unrelated.

**Comment by MCGallaspy** [comment]
The whitespace issue does indeed exist on `0.15.x`

**Pull request merged**
