### PR TITLE
test that processes are killed after kalite stop #3550

### PR DESCRIPTION
**Pull request by benjaoming**
test that processes are killed after kalite stop #3550

### CODE REVIEW

**Comment by benjaoming** [comment]
#3550

**Comment by aronasorman** [comment]
Description please :)

**Comment by benjaoming** [comment]
https://www.youtube.com/watch?v=tsbkk4SZAqA

**Comment by benjaoming** [comment]
Sorry I had a cherry pick gone wrong, there was actually comments in the code...

**Comment by aronasorman** [comment]
This failed btw @benjaoming. Your new tests failed! \o/

**Comment by benjaoming** [comment]
I think the unexpected ';' is because of '/bin/sh' executing these lines, not BASH.

**Comment by benjaoming** [comment]
This was randomly broken in a previous travis build... please don't merge

**Comment by aronasorman** [comment]
What's the resolution for this PR? Is this just for testing orphan processes on Travis? We also talked about giving you access to a rackspace server. Maybe that's a better platform for debugging this.

**Comment by benjaoming** [comment]
No solution yet, for all I know, the problem may still be a real problem with kalite and not Travis...

**Comment by aronasorman** [comment]
Yeah, I think it happened in a lot of different systems to make me think that this isn't just a Travis problem.

**Comment by benjaoming** [comment]
Hmm, will create a different PR, seems that github didn't track changes to the branch after closing it...

**Pull request closed without merging**
