### PR TITLE
Sidebar bug fix

### LINKED ISSUE #3221: Sidebar rendering bug
Browser: Firefox 35
Branch: latest develop as of 10 Mar 2015 13:12 PST
Language: German

screen shot 2015-03-10 at 1 11 46 pm

Opening the exercise given in the url, and then opening the sidebar makes the CSS all wrong. The scrollable area only extends up to a certain point, not the entire sidebar.

### PR DESCRIPTION
**Pull request by MCGallaspy**
Just changes the resizing rules of the sidebar. Fixes #3221. Now when you scroll, the height is recalculated. @rtibbles as part of our comprehensive testing initiative, how shall we deal with "bugs" like this? Is it possible to "mock" DOM events, and assert that height will be recalculated? I would probably need to refactor this view to properly test that.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
JS testing's not in `0.13.x`, but I'll open another PR targeting `develop` with a regressions test for this.

**Comment by rtibbles** [comment]
Screenshot?

**Comment by MCGallaspy** [comment]
ss
@rtibbles

**Comment by rtibbles** [comment]
Tests pass. Screenshot shows it fixes the issue. Merging.

**Comment by rtibbles** [comment]
Or not for stability's sake. Will focus on the develop PR.

**Pull request closed without merging**
