### PR TITLE
fix for #4430

### PR DESCRIPTION
**Pull request by 66eli77**

### CODE REVIEW

**Comment by djallado** [comment]
@66eli77, I tested your fix and I observed that the progress bar is now showing but it looks shorter and the `Cancel Video Downloads` button is misaligned.

**Comment by EdDixon** [comment]
@66eli77 @djallado I am testing now and can confirm what @djallado observations above except that the button alignment looks ok in the latest develop installer?

**Comment by EdDixon** [comment]
After a server restart I did encounter the issue with the misaligned button.

**Comment by rtibbles** [comment]
This change is extant on 0.15.x, so not a blocker to merging this PR.

**Comment by rtibbles** [comment]
Opened a separate issue for the progress bar and cancel button: #4486

**Pull request merged**
