### PR TITLE
remove a giant problem in settingshelper, it was loading the same set…

### PR DESCRIPTION
**Pull request by benjaoming**
…tings many times, assertion doesnt work

#3810

### CODE REVIEW

**Comment by benjaoming** [comment]
This PR is really not very important, because I will burn settingshelper down shortly.

**Comment by benjaoming** [comment]
@MCGallaspy this should be easy to merge, I just wanted you to be aware of the issue being solved (which has been an issue forever, I made a backport to 0.13.x as well)

I think the case here is that the way `set.union` works is by reference, and set.add works by value... well, that's my theory, I didn't look it up because it empirically just works for me.

**Comment by MCGallaspy** [comment]
While I think I understand what you're trying to accomplish with this PR *and* while I also acknowledge that `develop` is kind of a mess with failing tests anyway, the fact that this causes new failures is a red flag for me. If, as you say, this will become irrelevant anyway, then I suggest we ignore it and simply wait for the irrelevant-making PR.

**Comment by benjaoming** [comment]
Just put all efforts in #3809 :) It completely removes the dreaded settingshelper

**Pull request closed without merging**
