### PR TITLE
Add --port option and fix issues with proxying django options

### PR DESCRIPTION
**Pull request by benjaoming**
Replaces #3776

### CODE REVIEW

**Comment by MCGallaspy** [comment]
This one's a little fishy. What's the plan for replacing this if/when docopt merges your PR? We'll just have to add it to our TO-DO list? Should we remove `docopt` from our requirements in the meantime?

**Comment by benjaoming** [comment]
@MCGallaspy I'm still importing everything used in `docopt()` from `docopt` (the module).

**Comment by benjaoming** [comment]
But the plan would be to use docopt() as is and then use the exception thrown from docopt to collect the left-over parts of sys.argv and pass to underlying django commands called... i think it's acceptable
 and won't take up more than a couple of LOC.

**Comment by MCGallaspy** [comment]
@benjaoming 
All the test failures here should be fixed in #3867.

**Pull request merged**
