### PR TITLE
Django options were not parsed when they were already matched by doco…

### LINKED ISSUE #3892: Problems with arguments in kalitectl.py
See #3890. In the version of `kalitectl.py` now extant on `develop`, one needs to pass in --options to the kalitectl.py before the command, otherwise it's proxied to django management commands, e.g.:
```sh
kalite --port=1234 start --a-django-option
```
instead of
```sh
kalite start --port=1234 --a-django-option
```

In the version reverted by #3890 that is resolved, but then extra arguments are discarded, so the following two commands (for example) are equivalent:
```sh
kalite test my_test_label
kalite test
```
And this is true for all management commands that take extra arguments.

### PR DESCRIPTION
**Pull request by benjaoming**
…pt parser, only when they were NOT! #3892 

Fixes #3892

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Looks like it pukes on this `bin/kalite start --traceback -v 2`, can you handle single-`-` options?

**Comment by MCGallaspy** [comment]
Otherwise looks ok, very... __functional__.

**Comment by benjaoming** [comment]
Yeah it doesn't like the space between `-v` and `2`. `-v2` works.

**Comment by aronasorman** [comment]
Note: tests are failing because of that: we have `kalite manage test --traceback -v 2` in there.

**Comment by benjaoming** [comment]
Ah yes, makes sense, I already changed them once to --version=2 but them
changed them back to -v 2 thinking that I had finally made the perfect
options parser :D

**Comment by aronasorman** [comment]
Superseded by #3904.

**Pull request closed without merging**
