### PR TITLE
Adding the server restart requirement after language packs download/update to Admin docs

### LINKED ISSUE #4034: Missing instructions for server restart after adding languagepack
As seen in  #4027, it's pretty costly that we're missing an instruction for server restart.

Could someone figure out a nice and visible place for such a message?

### PR DESCRIPTION
**Pull request by radinamatic**
Fixes #4034, problem originally described in  #4027.

### CODE REVIEW

**Comment by benjaoming** [comment]
Added to #3966

**Comment by benjaoming** [comment]
Merged and built:

http://ka-lite.readthedocs.org/en/raspberry_pi_finalizations/usermanual/userman_admin.html#language-packs

However, the links are broken. If you merge my oddly named `raspberry_pi_finalizations` branch and install `pip install -r requirements_sphinx.txt`, you can build the docs locally:

    cd docs/
    make html

**Comment by radinamatic** [comment]
Yeah, the first link is broken, probably because I changed "Restarting..." to "Restart...", I just pushed a commit with the correction.

Or could it be because it's inside the `warning`? Do `notes` and `warnings` accept links, @MCGallaspy?

In my PyCharm normal link is formatted green, while the one I copy inside `warning` stays white.

**Comment by MCGallaspy** [comment]
If you wish to cross-reference locations within documents, use references and the ref role: http://sphinx-doc.org/markup/inline.html#ref-role

**Comment by radinamatic** [comment]
Changed the file using the ref role and rebased some commits, but I'm having problems with `make` and I can't build locally. Could someone check this? @MCGallaspy?

**Comment by MCGallaspy** [comment]
You need to add the `restarting-your-server` label somewhere in the docs for the reference to resolve. Otherwise it's an error.

**Comment by radinamatic** [comment]
Label was already there (line 560):
`.. _restarting-your-server:`

**Comment by MCGallaspy** [comment]
Oversight on my part, then!

**Comment by radinamatic** [comment]
Cool, thanks, as long as it works as it's supposed to!

**Pull request merged**
