### PR TITLE
Import channel test

### PR DESCRIPTION
**Pull request by MCGallaspy**
On this branch, I ran this command:
`python bin\kalite manage contentload --import=D:\ka-lite\import_test\`

Got this output:
```
WARNING:kalite:No metadata for file
WARNING:kalite:No metadata for file
WARNING:kalite:Title missing from file , using file name instead
WARNING:kalite:No metadata for file
WARNING:kalite:Title missing from file , using file name instead
WARNING:kalite:Title missing from file , using file name instead
WARNING:kalite:Removing childless topic: _1
WARNING:kalite:Removing childless topic: _2
INFO:kalite:Downloaded topic_tree data for
            0 exercises
            0 content files
            0 assessment items

```

After staring the server (and changed the settings to use new channel) it's apparently empty.

Archive of `D:\ka-lite\import_test\`: https://www.dropbox.com/s/00ruyucsa8ifraq/import_test.7z?dl=0

Looking in to it. Any insight @rtibbles?

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Ah ha, apparently it's an error to not specify `-c`

**Comment by rtibbles** [comment]
Also, the path should be ```D:\ka-lite\import_test\blah``` where ```blah``` is the root node of the channel topic tree.

**Comment by MCGallaspy** [comment]
Yes, correction, it's not that one must specify the channel, but rather that an empty channel_name causes issue. The channel_name is inferred, but a trailing slash messes up the inference and results in an empty name.

**Comment by rtibbles** [comment]
In fact, I believe import channel will default the channel name to the name of that root directory.

**Comment by MCGallaspy** [comment]
Still on this branch, using same archive and this command `python bin\kalite manage contentload --import=D:\ka-lite\import_test --channel=test --data=D:\ka-lite\import_test`, and changing my CHANNEL (in the kalite.settings.base, so hopefully I'm not missing any derived settings here) to "test", I just get an empty sidebar on the learn tab... what gives? Am I doing something wrong? Do we have a set of instructions for importing channels like this somewhere?

The contentload command has the follow output:
```
WARNING:kalite:No metadata for file test
WARNING:kalite:No metadata for file blah
WARNING:kalite:Title missing from file blah, using file name instead
WARNING:kalite:No metadata for file images
WARNING:kalite:Title missing from file images, using file name instead
WARNING:kalite:Title missing from file test, using file name instead
WARNING:kalite:Removing childless topic: images
INFO:kalite:Downloaded topic_tree data for
            0 exercises
            1 content files
            0 assessment items
```

**Comment by rtibbles** [comment]
These changes look good to merge. We can debug further.

**Pull request merged**
