### PR TITLE
For inclusion: add scandir dependency.

### PR DESCRIPTION
**Pull request by aronasorman**
scandir claims to be faster than os.walk. I have not tested this claim
myself, but I trust reddit.

Oh, and it's also part of python 3.5. Surely we can't say no to that??

PR created for discussion.

### CODE REVIEW

**Comment by aronasorman** [comment]
Pros:

Faster. 

Cons:

Additional dependency. Will slow down startup time.

**Comment by aronasorman** [comment]
I'm merging this after standup if no one has any complaints, as I want to use this for #3699.

**Comment by aronasorman** [comment]
`scandir` has its (pseudo) C extension, but if that's not present it will drop down to its pure python implementation.

**Comment by MCGallaspy** [comment]
Is it a drop-in for `os.walk`? Can you replace existing uses?

**Comment by aronasorman** [comment]
@MCGallaspy yes, I believe it's a drop-in for `os.walk` if you're just looking at files and filenames. If you're inspecting the attributes given by `os.stat`, then it won't work for that.

**Comment by MCGallaspy** [comment]
> The API for scandir.walk() is exactly the same as os.walk()

Looks like it's good to go.

**Comment by rtibbles** [comment]
As part of this PR, could you change, say, the use of os.walk in the content availability stamping (where it is used to add subtitle URLs) and then we could do a direct speed comparison?

**Comment by benjaoming** [comment]
@aronasorman are you sure that the python-only version of scandir has chances of being faster than os.walk?

**Comment by benjaoming** [comment]
I'm in the middle of cleaning up *unused* dependencies so I would rather not like to merge this... it's an unused dep :)

If you schedule a full refactor of the entire project with respect to os.walk, it'd be fine... perhaps an issue fir 0.15 ?

**Comment by aronasorman** [comment]
@benjaoming I've done my best to refactor our use of `os.walk` to use `scandir.walk` in my latest commit. So by this PR it should be a used dependency :)

However, I feel like introducing a dependency so close to the code freeze may be walking a fine line. @benjaoming also brought up a good point of benchmarking the *pure python* version of this module first to see if there are any significant speedups.

**Comment by aronasorman** [comment]
I'll post benchmarks.

**Comment by aronasorman** [comment]
No time to do this. 0.15.

**Comment by MCGallaspy** [comment]
Let's see some comparisons.

**Comment by benjaoming** [comment]
@aronasorman could you resolve the conflicts for this?

**Comment by aronasorman** [comment]
@benjaoming do you want to profile this yourself? If not I don't think this
is important enough for 0.15.

**Comment by benjaoming** [comment]
@aronasorman no, we might differ a bit on issues of bringing about new dependencies ;) that's what deters me from these sort of changes at the moment.. so I think it's fine that we wait.

**Comment by aronasorman** [comment]
Stale. @gwong89 please take a look at this PR, then open another one.

**Pull request closed without merging**
