### PR TITLE
Hotfix for #3171 - fixes breaking error in software-keypad for IE8

### LINKED ISSUE #3171: Cannot input into answer field using Internet Explorer
When using IE I am not able to enter a value into the answer fields while doing an exercise.

### PR DESCRIPTION
**Pull request by rtibbles**
Fixes #3171.

@MCGallaspy I think this is the minimal fix - but needs some testing to make sure that the keypad is still functional in IE8.

### CODE REVIEW

**Comment by aronasorman** [comment]
Since there's no 0.12 branch anymore, let's add the necessary metadata for 0.12.11 here too, before merging.

**Comment by rtibbles** [comment]
Sure, @aronasorman - you want to do it? You have collaborator rights.

**Comment by MCGallaspy** [comment]
This works on IE8

**Comment by aronasorman** [comment]
Added commit from #3305, and an update to `version.py`.

**Comment by aronasorman** [comment]
Ok, whatevs. Nondeterministic test failure. Merging.

**Pull request merged**
