### PR TITLE
Removed sidebar text fading

### LINKED ISSUE #2967: The bottom level of the topic sidebar fades too much when the sidebar is fully extended
Branch: develop
Expected Behavior: Sidebar text at the lowest level should be de-emphasized but still very legible.
Current Behavior: Text is so greyed out it, it is a little hard to read.
Steps to reproduce: Navigate through topic tree to bottom level
Screenshot(s): 
image

### PR DESCRIPTION
**Pull request by Antrikshy**
Sidebar topics no longer fade out when new ones are opened. Fixes #2967.

### CODE REVIEW

**Comment by jtamiace** [comment]
Looks good to me! I agree about the clean look of no fading.

**Comment by MCGallaspy** [comment]
@Antrikshy can you just remove the commented code, then?

**Comment by Antrikshy** [comment]
All right. Not sure why I commented it out.

**Comment by Antrikshy** [comment]
Here you go.

**Comment by MCGallaspy** [comment]
Great

**Pull request merged**
