### PR TITLE
Refactor so convert_urls function can be used elsewhere

### PR DESCRIPTION
**Pull request by MCGallaspy**
Needed to resolve [an issue in the central server](https://github.com/fle-internal/ka-lite-central/issues/238).

### CODE REVIEW

**Comment by aronasorman** [comment]
Can you write a simple test for the `convert_urls` function?

**Comment by jamalex** [comment]
Does this also download these other formats? Or only convert them?

**Comment by aronasorman** [comment]
No downloading going on here @jamalex. It was just refactored out so that the conversion can be used in the central server.

**Comment by MCGallaspy** [comment]
@aronasorman Holding me accountable

**Comment by aronasorman** [comment]
nondeterministic test failure. Merging.

**Pull request merged**
