### PR TITLE
Finally remove batch scripts; moved to installers repo

### PR DESCRIPTION
**Pull request by MCGallaspy**
See https://github.com/learningequality/installers/pull/322

### CODE REVIEW

**Comment by benjaoming** [comment]
Wow, KA Lite, you're growing up to be a real swan :D

**Comment by benjaoming** [comment]
Oops oops oops, did honestly not think this code would come with a test!

```

======================================================================
FAIL: test_scripts_path (kalite.basetests.tests.PathsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/ka-lite/kalite/basetests/tests.py", line 328, in test_scripts_path
    self.check_path(scripts_path, os.X_OK, msg=msg)
  File "/home/ubuntu/ka-lite/kalite/basetests/tests.py", line 99, in check_path
    self.fail(msg)
AssertionError: 1 access to /home/ubuntu/ka-lite/scripts path failed: 

----------------------------------------------------------------------
Ran 206 tests in 329.204s
```

**Comment by benjaoming** [comment]
Could you make another PR with the weird test removed?

**Comment by MCGallaspy** [comment]
Yes, will do.

**Comment by benjaoming** [comment]
Thanks, I shall revert my revert after merging the test :)

**Pull request merged**
