### PR TITLE
Ui cleanup

### LINKED ISSUE #3223: Back arrow doesn't look clickable
Browser: Firefox 35
Branch: develop

Compare the cursor between the two pics:

Cursor on topic --
screen shot 2015-03-10 at 1 18 21 pm

Cursor on back button --
screen shot 2015-03-10 at 1 18 34 pm

Basically, people using the mouse would have a hard time knowing that the back button region is clickable.

### LINKED ISSUE #3245: accessing exercise from progress report leads to incorrect sidebar behavior
screen shot 2015-03-10 at 3 03 52 pm
reproduce:
1.login as learner;
2.go to progress report(make sure you have something to choose)
3.open any drop down list and choose an exercise from it
you will see the sidebar fade are isn't fading, and the sidebar-tab is in 'close' state even though the sidebar is open

### PR DESCRIPTION
**Pull request by MCGallaspy**
Just @Antrikshy's changes from #3343, but with one amendment since I'd like to get this PR merged today. Fixes #3245 and fixes #3223. The back button is now a bootstrap button:
ss

### CODE REVIEW

**Comment by MCGallaspy** [comment]
@rtibbles this what you had in mind?

**Comment by rtibbles** [comment]
Yep, looks much more clickable to me.

**Comment by jamalex** [comment]
Hmm, is the bar itself still clickable as well? If not (or even if so, perhaps), it would be nice to make the button a bit taller (perhaps at least square).

**Comment by MCGallaspy** [comment]
ss
Taller button.

**Comment by rtibbles** [comment]
Let's get this in.

**Comment by Antrikshy** [comment]
Huh. I didn't think of this. Looks nice.

**Pull request merged**
