### PR TITLE
Mobile optimization: Admin pages cleanup

### PR DESCRIPTION
**Pull request by Antrikshy**
This PR comes with a ton of front-end changes to the admin pages. I have significantly cleaned up the messy reports page and other things. These are simple changes to templates and CSS and nothing else. 

I wonder why there are conflicts...

Here are a few screenshots:

#### Facilities and Reports pages (tables cleaned up):
screen shot 2015-02-05 at 10 59 20 am

---

screen shot 2015-02-05 at 11 03 19 am

---

screen shot 2015-02-05 at 11 05 10 am

---

#### Reports page on smaller width viewports:
screen shot 2015-02-05 at 11 24 43 am

---

screen shot 2015-02-05 at 11 04 42 am

Some tables still have green headers, conflicting with @benjaoming's blue colors from PR #2924. I'll fix those in a separate PR very soon because I plan to do some CSS refactoring related to the poorly named `.faded-blue-bg` class that we use across the site.

### CODE REVIEW

**Comment by aronasorman** [comment]
Let's fix this merge conflict when you get in @Antrikshy.

**Comment by Antrikshy** [comment]
Sure! I have two midterms this week so I'm kinda busy, but I'll try to be there tomorrow.

**Comment by Antrikshy** [comment]
Conflicts now fixed. Had to go in and redo some of my previous work because Git created some duplications. But it seems like everything works as it should.

**Comment by MCGallaspy** [comment]
All is well but there are merge conflicts again... Let me merge this locally and see if it passes tests.

**Comment by Antrikshy** [comment]
Git seems confused with this code. Changes are only on the front-end, so the tests should pass anyway.

**Pull request merged**
