### PR TITLE
Upgrade Perseus and fix fonts

### LINKED ISSUE #3587: Not all characters or icons displaying correctly in Windows XP
An issue was discovered during testing of the 13.1 branch on 4/30/2015 that may affect WIndows XP users. However, In discussion with other developers it was decided this is probably not an installer related issue so posting here. The red and green symbols showing correct or incorrect responses to assessment items do not render in windows XP and other symbols or characters may also be affected by this issue. Where expected would be X's or Check Marks we have character place boxes in the assessment dialog as show below. This was tested on several different OS's (MAC, Linux, Windows 7) and was only replicated in Windows XP.

### LINKED ISSUE #4857: Check box is not working, because of which we are unable to go to the next question on version 0.15
Detailed description:
The Check box to select the right option is not working on the exercise: Math --> Basic Geometry --> Shapes --> Classifying Shapes --> Recognizing triangle types
Because of which we are unable to proceed to the next question. 

Expected behavior:
The Check box should work and upon selecting the correct answer, the next question should be displayed.

Actual behavior:
1. On **http://demo.learningequality.org/learn/khan/math/basic-geo/basic-geo-shapes/basic-geo-classifying-shapes/recognizing-triangles/**
The check box seams to not work.
2. On a offline server that we have in one of the schools we are getting:
Unexpected error 504.
3. On one other offline server the check box is not working.

Note:
1. The check box is working for the question shown on the last screenshot. But it does not work on the question shown on the second screenshot.
2. This issue persists on all the offline servers.
3. Hope the same issue might persist on exercises that have check box response. 
4. Version 0.15 used

Please refer the screenshots for more details.

screen shot 2016-02-17 at 11 08 04 am
screen shot 2016-02-17 at 11 08 13 am
screenshot from 2016-02-17 10_56_04

### PR DESCRIPTION
**Pull request by rtibbles**
## Summary

This PR updates our bundled version of Perseus, as we were two major versions behind Khan Academy. It also bundles in Font Awesome, which is required by Perseus (and has been for a long time) but somehow we had ommitted it.

## TODO

- [X] New dependencies (if any) added to requirements file

## Reviewer guidance

A lot of this is boiler plate/built code, in terms of what has actually changed in our codebase, look in `perseus-helpers.js`.

## Issues addressed

Fixes #4857, and fixes #3587.

## Screenshots (if appropriate)

*They're nice. :)*
image

image

### CODE REVIEW

**Comment by rtibbles** [comment]
@radinamatic I can't write automated tests of this - in lieu, could you do a quick pass of exercises (including the font problematic ones) on this?

**Comment by radinamatic** [comment]
Sure, random selection of exercises at my discretion?

**Comment by rtibbles** [comment]
Yes, as well as the specific triangle one in the issue above.

And XP testing for the correct/incorrect icons!

**Comment by benjaoming** [comment]
@rtibbles any known issues about this? looking at the screenshot, it seems that the points box is misplaced?

**Comment by rtibbles** [comment]
Not quite sure what you mean, @benjaoming? The slight misalignment of the crosses and check marks?

**Comment by benjaoming** [comment]
The points collected box used to be above the other boxes?

**Comment by rtibbles** [comment]
It still is - there are two screenshots there :)

**Comment by benjaoming** [comment]
oh strangeness, maybe it's my internet connection that didn't load
everything... I should've taken a screenshot of your screenshot so you
could've known what I meant :D

**Comment by radinamatic** [comment]
Still getting some 404s in the console, but everything displays OK in the UI  @rtibbles! :)

ie8 - winxp 0 16 build 167 running - oracle vm virtualbox_265

**Comment by rtibbles** [comment]
OK, will fix up some of those 404s and merge.

**Comment by radinamatic** [comment]
:+1:

**Comment by rtibbles** [comment]
Merging.

**Pull request merged**
