### PR TITLE
Don't bother including assessment items for blacklisted exercises.

### PR DESCRIPTION
**Pull request by jamalex**
This removes 4706 unneeded assessment items. Will see how much space that saves, shortly.

### CODE REVIEW

**Comment by jamalex** [comment]
Cuts down khan_assessments.zip from 617MB to 491MB. :hand:

**Comment by jamalex** [comment]
@cpauya @benjaoming @MCGallaspy -- there's a new zip in town (same path, but smaller): https://learningequality.org/downloads/ka-lite/0.15/content/

**Comment by benjaoming** [comment]
:hand: 

NICE!!! Welcome the new zip!!!

**Comment by cpauya** [comment]
Yey!  :smiley_cat:

**Comment by jamalex** [comment]
@cpauya @benjaoming Go to sleep, you maniacs! :zzz:

**Pull request merged**
