### PR TITLE
Fix resource titles not displaying on chosen locale

### PR DESCRIPTION
**Pull request by mrpau-eugene**
## Summary

Found the lines where we can make the titles display in the current language

## TODO

If not all TODOs are marked, this PR is considered WIP (work in progress)

- [x] Have you written release notes for the upcoming release?

## Issues addressed

#5494

### CODE REVIEW

**Comment by radinamatic** [comment]
Good job @mrpau-eduard!

I had to change the `api_views.py` file on my Ubuntu VM to view this, but the fix seems to work :+1: 

virtualbox_ubuntu3_04_08_2017_13_14_21

**Comment by radinamatic** [comment]
:100: :+1:

**Comment by mrpau-eugene** [comment]
Done adding @benjaoming 👍

**Comment by benjaoming** [comment]
Great work! Trying to solve some issues on Circle CI - and I was going to push to your branch to continue this PR, but even though I have full access to the mrpau repo, I cannot see your branch. It's quite strange.

``` 
git fetch
git push mrpau hotfix/5494-resource-titles-displaying-in-english-instead-of-chosen-local
error: src refspec hotfix/5494-resource-titles-displaying-in-english-instead-of-chosen-local does not match any.
error: failed to push some refs to 'git@github.com:mrpau/ka-lite.git'
```

Will open another PR...

**Comment by radinamatic** [comment]
Unfortunately, while testing the final installers prior to signing them, this issue resurfaced... :disappointed: 

I'm not completely sure why, since at first the resource titles do display in the chosen locale, but after playing a while by choosing subtopics from the dropdown, and resubmitting, they return to being displayed in English **but only in the table at the bottom**:

virtualbox_msedge - win10_preview_22_08_2017_10_41_58

@mrpau-eugene Could you re-test this and see what did we miss?

**Comment by mrpau-eugene** [comment]
@radinamatic sure! will work on this asap

**Pull request closed without merging**
