### PR TITLE
Remove static file that should not be tracked. Add to git ignore.

### PR DESCRIPTION
**Pull request by benjaoming**
## Summary

Experimenting with fix of broken tests #5169

### CODE REVIEW

**Comment by benjaoming** [comment]
Trying to rebuild without caching...

**Comment by rtibbles** [comment]
This test failure makes no sense, because it is meant to time out in order to assert that there is no such element....

**Comment by benjaoming** [comment]
@rtibbles the messed up thing is that it doesn't happen at all in `develop`, I was looking for an explanation and tried this out... obviously doesn't work.. so might as well close it just in case it causes a new bug in 0.16.x?

**Comment by rtibbles** [comment]
Closing then.

**Pull request closed without merging**
