### PR TITLE
Memory improvements

### PR DESCRIPTION
**Pull request by jamalex**
Two changes here, to help reduce our memory footprint:

- Load JSON text as `str` rather than `unicode` objects (muuuuuuch smaller).
- Don't load unnecessary store stuff.

### CODE REVIEW

**Comment by 66eli77** [comment]
@aronasorman  can this PR be merged soon?

**Comment by aronasorman** [comment]
@66eli77 just fixing the tests. You can try checking out this branch now if you want to confirm if it works for the RPi

**Comment by aronasorman** [comment]
nondeterministic test failures. Merging.

**Comment by aronasorman** [comment]
Tests pass. Thanks force-push!

**Pull request merged**
