### PR TITLE
Add space because of character issue in Swahili translation 

### PR DESCRIPTION
**Pull request by benjaoming**
supersedes #5378

fixes #5323

### CODE REVIEW

**Comment by mrpau-eduard** [comment]
Hi @benjaoming thanks for helping! 
I check the video dowload for Swahili. The issue is still persisting. 
screen shot 2017-01-09 at 5 28 08 pm

**Comment by benjaoming** [comment]
Thanks for testing @mrpau-eduard - wondering why adding the space outside `gettext()` would cause it to persist? You had tested that adding a blank space `" "` fixed it, no?

**Comment by benjaoming** [comment]
@mrpau-eduard - can you take this over? I'm closing it because you found possible issues.. but the current Swahili translation is this:

    Maendeleo yaliyokidhiri:%(percent_complete)5.1%%kamilika%(cur_stage)d ya%(num_stages)d

English is:

    Overall progress: %(percent_complete)5.1f%% complete (%(cur_stage)d of %(num_stages)d)

As I read it, the problem is in the translation string, not something that should be fixed in the code?

**Comment by benjaoming** [comment]
@mrpau-eduard 

I have updated and approved the string in this state:

    Maendeleo yaliyokidhiri: %(percent_complete)5.1%% kamilika (%(cur_stage)d ya %(num_stages)d)

Try rebuilding the content pack and see if it works now?

**Pull request closed without merging**
