### PR TITLE
Fixes #3237: fix the ugliness of the dropdown in the collapsed menu tab. also responsive issue for closed issue #3168.

### LINKED ISSUE #3237: Ugly dropdown menu on small screen
On `develop`, if you resize the screen so that the `navbar-right` items are stacked under the search bar, then expanding the dropdown menu produces undesirable results:
ss

### PR DESCRIPTION
**Pull request by jtamiace**
Fixes #3237 and #3168 . The dropdown is less ugly now, but I couldn't move forward much in this timeframe because there are limitations with bootstrap: can't put a "dropdown" in a "collapsed menu" so that the blue part beneath the navigation tabs doesn't appear. 

dropdown

also placed the learn tab back in the top nav as requested by @jamalex and put the language tab back in the footer (for now): 

mobile version:
mobile-lang

normal size screen:
language footer

in addition here's a responsive fix for the teacher/admin navigation on smaller screens:

The teacher navigation centers, loses the line on the bottom, and buttons are more flat:
teach nav tablet

And a view for mobile:
teach nav mobile

### CODE REVIEW

**Comment by aronasorman** [comment]
Don't forget to add the "Fixes #3237"!

**Comment by rtibbles** [comment]
I get this when logged in as admin:
image

**Comment by rtibbles** [comment]
(Note that the username header expands horizontally on click as well).

**Comment by rtibbles** [comment]
And like this for a teacher:
image

**Comment by rtibbles** [comment]
Also, do you have Nalanda package in your local_settings.py? Wondering why you have 'playlists', 'units', and 'tests' in your nav?

**Comment by jtamiace** [comment]
Oh no... yes I have it configured to Nalanda

**Comment by rtibbles** [comment]
Let's try this again...

**Comment by rtibbles** [comment]
Horizontal expansion a slight concern on the username still:
image

**Comment by rtibbles** [comment]
The only solution I can think of here is to force all the tabs to fill up the same vertical height as each other. Would still look ugly as sin, however.

**Comment by rtibbles** [comment]
Also, on full size viewport: 
image

**Pull request merged**
