### PR TITLE
0.16b2

### PR DESCRIPTION
**Pull request by kalitebuilder**
**WARNING!** Merging this, merges and closes all PRs contained in this PR, and they may have a separate review process and amendments following. So don't merge this PR!! :)

Takes over  0.16b1 #4945

New release, manually brewing the distributions:

 * [x] [ka-lite on pypi](https://pypi.python.org/pypi/ka-lite)
 * [x] [ka-lite-static on pypi](https://pypi.python.org/pypi/ka-lite-static)
 * [x] [ka-lite on Launchpad PPA](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite)
 * [ ] OSX installer
 * [ ] Windows installer

## Known issues

 * [x] Raspberry Pi still can only download 1 video at a time #4892
 * [x] Content packs are to be updated, videos show up twice on Video download page
 * [x] After you create the first admin user account, you need to reload the page before clicking Login #4896
 * [x] Video download counts reported misleading #4929 
 * [ ] [See remaining issue list for Milestone](https://github.com/learningequality/ka-lite/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.16.0)

## Included PRs

 * #4966
 * #4965
 * #4965

## Installer links

  * Debian/Ubuntu: [ka-lite](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite_0.16~b2-0ubuntu1_all.deb) | [ka-lite-bundle](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-bundle_0.16~b2-0ubuntu1_all.deb) | [ka-lite-raspberry-pi](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-raspberry-pi_0.16~b2-0ubuntu1_all.deb)
  * [Windows]() TODO
  * [Mac]() TODO

### CODE REVIEW

**Comment by kalitebuilder** [comment]
having issues building it atm on the temporary build server which is why nothing has been released.

**Comment by MCGallaspy** [comment]
@kalitebuilder / @benjaoming can you indicate what those issues are? We want to take this over from you so we can build a deb.

**Comment by benjaoming** [comment]
Out of bad connectivity, I had to PM a stack trade of a `make assets` failure to @rtibbles -- found it in my logs:

```
8:10:54 PM - me: (kalite)kalitebuilder@overtag:~/ka-lite$ make assets
# Necessary because NPM may have wrong versions in the cache
npm cache clean
npm install --production
npm WARN package.json ka-lite@0.0.0 license should be a valid SPDX license expression
node build.js
Watchify: Found 19 bundles, compiling.
Watchify: Assuming that Khan Util files are already deAMDified
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'loose-envify' from '/home/kalitebuilder/ka-lite/node_modules/react/node_modules/fbjs'
    at /home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/kalitebuilder/ka-lite/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
make: *** [assets] Error 1
```

**Comment by benjaoming** [comment]
Adding `loose-envify` to package.json solves it... I can live with that, but should be solved so `make assets` works on a clean non-dev checkout.

**Comment by benjaoming** [comment]
#4983

**Comment by benjaoming** [comment]
PyPi + PPA updated, inserted .deb links in the description above

@radinamatic @MCGallaspy @cpauya

**Comment by radinamatic** [comment]
Downloading, thanks! :+1:

**Pull request closed without merging**
