### PR TITLE
Remove dateutil, now it's in requirements.txt

### PR DESCRIPTION
**Pull request by benjaoming**
Seems a new dependency was snuck in through 763e153e3f0f7eed768c3eaa53bdb398958dcd15

#3403

### CODE REVIEW

**Comment by benjaoming** [comment]
Preferably, this dependency should be completely removed, it's a bit overkill for these meagre purposes:

```
➜  ka-lite git:(kalite-command-proxy-status) ack-grep dateutil kalite
kalite/main/models.py
10:from dateutil import relativedelta

kalite/updates/api_views.py
4:import dateutil.parser
61:                start_time = make_naive(dateutil.parser.parse(request.GET["start_time"]), get_current_timezone())

kalite/basetests/tests.py
211:        "dateutil": "1.5",

kalite/control_panel/views.py
4:import dateutil
467:        period_end = dateutil.parser.parse(period_end)
468:        period_end = period_end + dateutil.relativedelta.relativedelta(days=+1, microseconds=-1)

kalite/facility/api_resources.py
3:from dateutil.tz import tzlocal
```

**Comment by benjaoming** [comment]
I mean, 3700+ lines of code to parse a date is *too much* IMO.

**Comment by aronasorman** [comment]
I see what you mean. Can we even get `datetime` to replace it? I know we can parse [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) dates there, and we can probably make our own parser using `datetime` as well as long as we know the format of the dates beforehand.

**Comment by benjaoming** [comment]
I've opened up a separate issue on this, but for now, we can safely remove the package in python-packages as it's a dependency. It's still mentioned in LICENSE because we will continue to ship in the static build as long as its a dependency.

**Comment by rtibbles** [comment]
I agree this is unnecessary - especially as we have seen that we cannot rely on server times, let alone their timezones for good timestamping - in fact, a lot of our code assumes as much.

**Comment by benjaoming** [comment]
Merging this, sounds like there's plentiful of agreement to remove dateutil in #4266

**Pull request merged**
