### PR TITLE
0.14 docs fixup

### PR DESCRIPTION
**Pull request by MCGallaspy**
Addresses these two points from #4258:

* PPA and pip instructions, and the "advanced topics" stuff, should move to a separate advanced page (and not show up on this main installers page), as discussed previously with @benjaoming
* "KA Lite is currently not supported on Internet Explorer version 8 or lower. You must use IE9 or later." should be changed to mention that essentially any version of Chrome, Firefox, or Safari should work fine too. We've had people email asking why they can only use IE.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
Remember, once these are merged you'll have to run the playbook in order to build and deploy the updated docs.

**Comment by benjaoming** [comment]
:+1:

In the longer run, we probably need to give a better overview such that installation methods that may be extremely convenient to some aren't hidden behind "Advanced installation". Also, I should make updates that reflect what we're learning with the Raspberry Pi package currently.

**Comment by jamalex** [comment]
What's here looks good, and then there will be a few more things to do, e.g. the PPA instructions should also be moved to this section (can be done as part of updating the Deb links to use the /r/deb-latest-installer redirect) -- I would also recommend having the page be called "Advanced installation methods" rather than the more generic "Advanced topics".

**Comment by MCGallaspy** [comment]
@jamalex okay, as soon as the .deb link exists I will update the docs.

**Comment by benjaoming** [comment]
Merging this, so I can continue the work in a separate PR.

**Pull request merged**
