### PR TITLE
0.17.0b4

### PR DESCRIPTION
**Pull request by benjaoming**
Supersedes #5355

**WARNING!** Merging this, merges and closes all PRs contained in this PR, and they may have a separate review process and amendments following. **So don't merge this PR!!** :)

New release, manually brewing the distributions:
- [x] [ka-lite on pypi](https://pypi.python.org/pypi/ka-lite)
- [x] [ka-lite-static on pypi](https://pypi.python.org/pypi/ka-lite-static)
- [x] [ka-lite on Launchpad PPA](https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite)
- [x] OSX installer
- [x] Windows installer 

## Known issues

See release notes: http://ka-lite.readthedocs.io/en/develop/installguide/release_notes.html

## Installer links
- Debian/Ubuntu:
   - https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-bundle_0.17.0~b4-0ubuntu1_all.deb
   - https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite_0.17.0~b4-0ubuntu1_all.deb
   - https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-raspberry-pi_0.17.0~b4-0ubuntu1_all.deb
- [Windows](https://drive.google.com/open?id=0B5Tyi-tRKOFMaVF0YUtpWlh4YmM)
- [Mac](https://drive.google.com/open?id=0B5Tyi-tRKOFMWElnUXhTNTY0SUk)
### PyPi

NB! Now only serves .whl files.

```
pip install ka-lite --pre
```

or

```
pip install ka-lite-static --pre  # bundled dependencies
```

### CODE REVIEW

**Comment by benjaoming** [comment]
@radinamatic PyPi package up!

**Comment by radinamatic** [comment]
:boom:

**Comment by benjaoming** [comment]
Windows and Mac installer links added :)

**Comment by benjaoming** [comment]
@radinamatic - have you had success with the installers? I mean not to open up specific issues here, but just an overall idea of how it's been, since I gather there hasn't been anything specific related to this prerelease?

**Comment by radinamatic** [comment]
@benjaoming 

I did another round of testing today on both Ubuntu and Windows.

No problems/errors with installers so far, but I'm still unsure what the issue is with contentpacks and subtitles not showing... Not from the straight installer, not by CLI installation of the [`en.zip` contentpack](https://drive.google.com/drive/folders/0B-E59G3J_sXmLUgxdzdHLXpYX1E), not by upgrading from UI, restarting the server, etc... Subs are nowhere to be found! 

It's not a FF vs. Chrome issue, and it's not only in English, today I was unable to see neither [Spanish nor pt-BR,](https://drive.google.com/drive/folders/0B-E59G3J_sXmd2UyblV6a3ZfWnc) all of which I did test the previous contentpack version last week. I'm not so worried about other languages, but the fact that English subs seem unavailable is a release blocker...

@mrpau-eduard @mrpau-richard Are you able to see English subtitles with this latest contentpack?

**Pull request closed without merging**
