### PR TITLE
style changes to homepage for aflatoun

### PR DESCRIPTION
**Pull request by jtamiace**
## Summary

Changes thus far. Tracking from 0.16.x branch

screen shot 2016-07-26 at 4 34 04 pm

## TODO

If not all TODOs are marked, this PR is considered WIP (work in progress)

- [ ] Have **tests** been written for the new code? If you're fixing a bug, write a regression test (or have a really good reason for not writing one... and I mean **really** good!)
- [ ] Has documentation been written/updated?
- [ ] New dependencies (if any) added to requirements file

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

List the issues solved or partly solved by the PR

## Documentation

*If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)*

## Screenshots (if appropriate)

*They're nice. :)*

### CODE REVIEW

**Comment by jamalex** [comment]
Cool! Looks pretty.

A couple notes:
- I see "KA Lite" in the subtitle below the image
- What does the footer look like? Would be good to have LE in there on the platform side, and "Content All Rights Reserved, Aflatoun"

**Comment by jtamiace** [comment]
@jamalex Yeah I wasn't sure how how much of the text especially to "hard code" since it should be available in English and French? Not sure how that's currently being handled.

Here is the mockup of what they wanted by the way:

Word doc of their issues (Aflatoun Resource Feedback)
https://drive.google.com/drive/u/0/folders/0B3sjMmpdLvk4SVBJcTBrTzRMeVk

branding final

**Comment by jtamiace** [comment]
And here's the current footer off this branch

screen shot 2016-07-28 at 9 19 09 am

**Comment by jamalex** [comment]
> I wasn't sure how how much of the text especially to "hard code" since it should be available in English and French? Not sure how that's currently being handled.

That's a really good point -- I'm not certain of the best approach here either, since running it through `gettext` to translate it won't work, as those strings aren't in our PO files from Crowdin. As a hack, something like this could work:

```django
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

{% if LANGUAGE_CODE == "en" %}
English text here.
{% elif LANGUAGE_CODE == "fr" %}
La belle langue.
{% endif %}
```

(Does that sound reasonable, for this Aflatoun hack-branch, @aronasorman?)

**Comment by jamalex** [comment]
Oh, and for the footer: remove the CC image, as it's not CC-licensed.

**Pull request merged**
