### PR TITLE
Do not create a .zip archive for sdist, tar.gz is enough

### PR DESCRIPTION
**Pull request by benjaoming**
## Summary

Save time and space. The .zip files are not necessary for pip to work.

## Reviewer guidance

Please comment if you **do** find them necessary on PyPi.

### CODE REVIEW

**Comment by MCGallaspy** [comment]
I do find it necessary on Windows.

**Comment by MCGallaspy** [comment]
I can always build it myself, but I just now switched to downloading the sdist zipfile from PyPI -- it would be nice to keep it that way.

**Comment by benjaoming** [comment]
Aha! I thought you were building it with `make dist`, I'll make sure it builds zips for PyPi only instead...

**Comment by aronasorman** [comment]
Merge conflicts.

**Comment by benjaoming** [comment]
There we go, resolved

**Comment by MCGallaspy** [comment]
Actually, I couldn't find a good way to download the zipfile (as opposed the tarball) from pypi using `pip download` -- is there an option for specifying the format? If not, it may yet be useful to keep this in the Makefile, so that the buildserver can continue to generate the sdist itself.

**Comment by benjaoming** [comment]
Okay, I was assuming you were doing the other thing.

Would it be okay to add an argument to the dist target, something like `make dist format=zip` ?

In that way, when we make the dist on other systems, we won't needlessly generate zip files, and when we create them on Windows, we won't be needlessly generating tarballs. And you can even do `make dist format=zip,tarball`

**Comment by benjaoming** [comment]
http://stackoverflow.com/a/2826068/405682

**Comment by MCGallaspy** [comment]
Sure, or perhaps we can control it with an environment variable? That would be fine.

**Pull request merged**
