### PR TITLE
Site colors and sidebar overhaul

### PR DESCRIPTION
**Pull request by Antrikshy**
This branch contains some huge design changes. I posted the screenshots to the Design chat earlier, but here they are for convenience.

I have vastly updated the sidebar with this much cleaner look. The horrible less-than/greater-than symbols on the tab have been replaced with IcoMoon icons. I have changed the dark green color used across the site to this fresh new bluish-green I lifted off the Khan Academy site. I also found a new faded-green color for the header and footer to go with it. [Credit to [Coolors.co](http://coolors.co/5aa685-989d8f-8b9ebf-b2d2c1-cde4b7), which you should all check out!]

This is still very much a work in progress. Various Bootstrap and khan-site design elements have yet to be overridden. I want to change the button design around a bit. If anybody catches any green colors or other design elements that go against the new color language, let me know on HipChat. Same goes for any other feedback or ideas.

### CODE REVIEW

**Comment by aronasorman** [comment]
@66eli77 it would be good to test out the new sidebar icon in the mobile app.

**Comment by Antrikshy** [comment]
If the icons inside the sidebar work (for different kinds of items/menus), then the tab arrows should work. They are part of the same set.

**Comment by 66eli77** [comment]
@aronasorman  sure

**Comment by 66eli77** [comment]
just tested your new design on one of the tablets, it looks very nice. Like the shadow touch you made on the arrow tab!!

**Comment by Antrikshy** [comment]
Thanks!

I might poke around with Bootstrap and make more of the site responsive because mobile friendliness is one of the issues. If someone could get the sidebar to scroll horizontally that would be great.

**Comment by jtamiace** [comment]
Looks much better, great improvement! Much softer on the eyes

**Comment by Antrikshy** [comment]
This branch is now "stable" enough in terms of design to be merged. All the work that I was doing is complete for now. I might continue to make some minor changes sometime later, but I think this iteration can be shipped in the upcoming version.

**Pull request merged**
