### PR TITLE
Nalanda rct3 to nalanda

### PR DESCRIPTION
**Pull request by aronasorman**

### CODE REVIEW

**Comment by anuragkanungo** [comment]
@aronasorman @jamalex 

Can this be merged, or need any integration testing?

**Comment by aronasorman** [comment]
@anuragkanungo we might want to do some testing first with Abhinav to see if there are no errors.

**Comment by anuragkanungo** [comment]
@aronasorman @jamalex 
Abhinav has tested and verified. So, please go ahead and merge.

**Comment by jamalex** [comment]
@anuragkanungo Ok, nalanda branch should be updated to the latest nalanda-rct3 now.

**Pull request merged**
