### PR TITLE
Fixed alignment of the sub nav at 480px size viewport.

### LINKED ISSUE #3145: Alignment issue of subnav when resizing to < 480px.
Branch: `develop` for `0.13.x` - February 27 2015

Expected behavior: The subnav should be aligned

Actual behavior:
This size 480px is for `Low end windows phone`.
screen shot 2015-02-27 at 11 52 30 am

Steps to reproduce:

1. Login as teacher user.
2. Go to the manage tab.
3. Resize to 480px or less and notice.

### PR DESCRIPTION
**Pull request by jesumer**
Hi @aronasorman, This fixed #3145. 

screen shot 2015-02-27 at 2 53 28 pm

Steps to reproduce:

1. Login as teacher user.
2. Go to the manage tab.
3. It's now aligned

/review: @arceduardvincent

### CODE REVIEW

**Comment by rtibbles** [comment]
Unfortunately, the images and text in these tabs are now misaligned from center.

**Comment by rtibbles** [comment]
Can you attach an updated screenshot, @jesumer?

**Comment by jesumer** [comment]
Yes. Here is my screenshot at Firefox v36.0(left-side) and chrome v40.0.2214.115(right-side).
screen shot 2015-03-02 at 9 55 01 am

**Comment by rtibbles** [comment]
Looks good at 480px. Merging.

**Comment by rtibbles** [comment]
My one concern here is that below 480px it still messes up, but will open a separate issue.

**Comment by jesumer** [comment]
@rtibbles 
Yeah that is for small mobile phones and I guess that is a separate issue because we consider also the main nav for that.

**Pull request merged**
