### PR TITLE
Run both cherrypy and chronograph in same process #3550 #3601 #3827, …

### PR DESCRIPTION
**Pull request by benjaoming**
…add --foreground option and respect --port option and env KALITE_LISTEN_PORT

This PR centralizes the whole daemon behavior to one single call in kalitectl and removes lots of chained calls.

It also adds a `--foreground` option to run kalite in the foreground instead of going to daemon mode.

Tasks:

 * [x] Add `--foreground` option to `kalite start`.
 * [ ] Default logging to ~/.kalite/kalite.log and have "Already stopped (check logs)" message output path to log.
 * [x] Put deprecation warnings in kaserve etc.

Solves: #3550 #3601 #3827

### CODE REVIEW

**Comment by benjaoming** [comment]
This includes #3809

**Comment by MCGallaspy** [comment]
A few small comments, and let me test it out, but otherwise good to go. Nice!

**Comment by MCGallaspy** [comment]
Tried running "python.exe kalite start" in Windows 8, everything worked okay, but the process never relinquished control back to the terminal...

**Comment by MCGallaspy** [comment]
I guess I shoulda just used `kalite.bat`. Works ok, but has the opposite problem of not really accepting input (with e.g. breaks "kalite manage setup"). But given that start, stop, and status all require no input, I think that's okay for now.

Seems great. A++++ would merge.

**Comment by benjaoming** [comment]
@MCGallaspy the input problem on Windows 8 was also an issue before, right? Would you be able to do a basic test of `raw_input` and see where the chain falls off? Would it be that `subprocess.Popen` can't handle it?

**Comment by MCGallaspy** [comment]
Will this 
>Default logging to ~/.kalite/kalite.log and have "Already stopped (check logs)" message output path to log.

Appear here or in a separate PR?

**Pull request merged**
