### PR TITLE
enable login right after superuser is created

### PR DESCRIPTION
**Pull request by 66eli77**
## Summary

fix issue #4879
The current behavior will be, right after the superuser is created, the login modal will pop up.

## TODO

If not all TODOs are marked, this PR is considered WIP (work in progress)

- [ ] Have **tests** been written for the new code? If you're fixing a bug, write a regression test (or have a really good reason for not writing one... and I mean **really** good!)

## Reviewer guidance

*If you PR has a significant size, give the reviewer some helpful remarks*

## Issues addressed

#4879

### CODE REVIEW

**Comment by benjaoming** [comment]
Thanks for the quick attention! Looks like a simple solution, assuming you already verified manually -- will merge once tests have been proven to be okay!

**Comment by benjaoming** [comment]
@66eli77 test failure is legit:

```


  Scenario: Create superuser with correct username and password and re-enter password  # kalite/distributed/features/superuser_create.feature:47
    Given superuser is deleted                                                         # kalite/distributed/features/steps/superuser_create.py:22
    Given superuser is deleted                                                         # kalite/distributed/features/steps/superuser_create.py:22 0.004s
    And I am on the homepage                                                           # kalite/distributed/features/steps/generic.py:4
    And I am on the homepage                                                           # kalite/distributed/features/steps/generic.py:4 1.640s
    Then I should see a modal                                                          # kalite/distributed/features/steps/superuser_create.py:28
    Then I should see a modal                                                          # kalite/distributed/features/steps/superuser_create.py:28 0.133s
    When I enter username correctly                                                    # kalite/distributed/features/steps/superuser_create.py:74
    When I enter username correctly                                                    # kalite/distributed/features/steps/superuser_create.py:74 5.470s
    And I enter password correctly                                                     # kalite/distributed/features/steps/superuser_create.py:78
    And I enter password correctly                                                     # kalite/distributed/features/steps/superuser_create.py:78 6.940s
    And I re-enter password correctly                                                  # kalite/distributed/features/steps/superuser_create.py:82
    And I re-enter password correctly                                                  # kalite/distributed/features/steps/superuser_create.py:82 6.720s
    When I click the create button                                                     # kalite/distributed/features/steps/superuser_create.py:36
    When I click the create button                                                     # kalite/distributed/features/steps/superuser_create.py:36 0.599s
    Then the modal will dismiss                                                        # kalite/distributed/features/steps/superuser_create.py:86
    Then the modal will dismiss                                                        # kalite/distributed/features/steps/superuser_create.py:86 30.146s
      Traceback (most recent call last):
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1173, in run
          match.run(runner.context)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/behave/model.py", line 1589, in run
          self.func(context, *args, **kwargs)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/superuser_create.py", line 90, in impl
          is_border_red(context, id_)
        File "/home/ubuntu/ka-lite/kalite/distributed/features/steps/superuser_create.py", line 113, in is_border_red
          assert find_id_with_wait(context, field_id), "border field is None!"
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 222, in find_id_with_wait
          return _find_elem_with_wait(context, (By.ID, id_str), **kwargs)
        File "/home/ubuntu/ka-lite/kalite/testing/behave_helpers.py", line 267, in _find_elem_with_wait
          EC.presence_of_element_located(by)
        File "/home/ubuntu/virtualenvs/venv-2.7.9/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 75, in until
          raise TimeoutException(message, screen, stacktrace)
      TimeoutException: Message: 
      Stacktrace:
          at <anonymous class>.FirefoxDriver.prototype.findElementInternal_ (file:///tmp/anonymous70500940298031427webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10659)
          at <anonymous class>.FirefoxDriver.prototype.findElement (file:///tmp/anonymous70500940298031427webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10668)
          at <anonymous class>.DelayedCommand.prototype.executeInternal_/h (file:///tmp/anonymous70500940298031427webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12534)
          at <anonymous class>.DelayedCommand.prototype.executeInternal_ (file:///tmp/anonymous70500940298031427webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12539)
          at <anonymous class>.DelayedCommand.prototype.execute/< (file:///tmp/anonymous70500940298031427webdriver-profile/extensions/fxdriver@googlecode.com/components/command-processor.js:12481)

Link to your job: https://saucelabs.com/jobs/3978954385594c3ea464f9afc6c234e1
Installed 0 object(s) from 0 fixture(s)
    Given I am on the homepage                                                         # None
    Then there should be no modal displayed                                            # None
```

**Comment by 66eli77** [comment]
I didn't encounter this behavior during my manual testing, might be the way I wrote the test causes this failure. Working on it now

**Comment by 66eli77** [comment]
ah, that's not true, I encounter it this time manually run kalite

**Comment by benjaoming** [comment]
Great stuff, made a rebuild and now it passes, thanks for fixing quickly!

**Pull request merged**
